// Command adrmap generates the ADR knowledge-graph map (docs/adr/MAP.md) from the curated
// ontology docs/adr/topics.json (ADR-0109). MAP.md is a GENERATED navigation router — a mermaid
// subsystem graph + a by-topic index + an ADR→subsystem reverse index — never hand-edited.
//
//	go run ./tools/adrmap            # regenerate MAP.md (also validates coverage; fatal on a gap)
//	go run ./tools/adrmap -check     # validate only, and fail if MAP.md is stale (no write)
//
// Coverage is enforced: every ADR file must appear in >=1 subsystem, every referenced ADR must
// exist, and every depends_on target must be a defined subsystem. Stdlib only — no deps, so it
// runs anywhere without go.sum churn.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

type ontology struct {
	Note       string                `json:"note"`
	Subsystems map[string]*subsystem `json:"subsystems"`
}

type subsystem struct {
	Title     string   `json:"title"`
	Adrs      []int    `json:"adrs"`
	DependsOn []string `json:"depends_on"`
}

var (
	fileRe  = regexp.MustCompile(`^(\d{4})-(.+)\.md$`)
	titleRe = regexp.MustCompile(`^#\s*ADR\s*(\d{4})\s*[—-]\s*(.+)$`)
)

func main() {
	adrDir := flag.String("adr", "docs/adr", "the docs/adr directory")
	check := flag.Bool("check", false, "validate + fail if MAP.md is stale, do not write")
	flag.Parse()

	onto := loadOntology(filepath.Join(*adrDir, "topics.json"))
	adrs := scanADRs(*adrDir) // number -> {slug, title}

	validate(onto, adrs) // fatal on any coverage/reference gap

	out := render(onto, adrs)
	mapPath := filepath.Join(*adrDir, "MAP.md")
	if *check {
		cur, _ := os.ReadFile(mapPath)
		if string(cur) != out {
			fatalf("%s is STALE — run `task adr:index` and commit (topics.json changed but MAP.md was not regenerated)", mapPath)
		}
		fmt.Printf("adrmap: %d ADRs across %d subsystems; MAP.md is fresh\n", len(adrs), len(onto.Subsystems))
		return
	}
	if err := os.WriteFile(mapPath, []byte(out), 0o644); err != nil {
		fatalf("write %s: %v", mapPath, err)
	}
	fmt.Printf("adrmap: wrote %s (%d ADRs across %d subsystems)\n", mapPath, len(adrs), len(onto.Subsystems))
}

type adrMeta struct {
	slug, title string
}

func loadOntology(path string) *ontology {
	raw, err := os.ReadFile(path)
	if err != nil {
		fatalf("read %s: %v", path, err)
	}
	var o ontology
	if err := json.Unmarshal(raw, &o); err != nil {
		fatalf("parse %s: %v", path, err)
	}
	return &o
}

func scanADRs(dir string) map[int]adrMeta {
	ents, err := os.ReadDir(dir)
	if err != nil {
		fatalf("read dir %s: %v", dir, err)
	}
	out := map[int]adrMeta{}
	for _, e := range ents {
		m := fileRe.FindStringSubmatch(e.Name())
		if m == nil {
			continue
		}
		n, _ := strconv.Atoi(m[1])
		if n == 0 {
			continue // 0000-template.md is not an ADR
		}
		title := ""
		if raw, err := os.ReadFile(filepath.Join(dir, e.Name())); err == nil {
			first := strings.SplitN(string(raw), "\n", 2)[0]
			if tm := titleRe.FindStringSubmatch(first); tm != nil {
				title = strings.TrimSpace(tm[2])
			}
		}
		out[n] = adrMeta{slug: strings.TrimSuffix(e.Name(), ".md"), title: title}
	}
	return out
}

func validate(o *ontology, adrs map[int]adrMeta) {
	var errs []string
	names := map[string]bool{}
	for name := range o.Subsystems {
		names[name] = true
	}
	tagged := map[int]bool{}
	for name, s := range o.Subsystems {
		for _, n := range s.Adrs {
			if _, ok := adrs[n]; !ok {
				errs = append(errs, fmt.Sprintf("subsystem %q references ADR %04d which does not exist", name, n))
			}
			tagged[n] = true
		}
		for _, dep := range s.DependsOn {
			if !names[dep] {
				errs = append(errs, fmt.Sprintf("subsystem %q depends_on %q which is not a defined subsystem", name, dep))
			}
		}
	}
	// Coverage: every ADR file must be tagged into at least one subsystem (this is the gate that
	// forces a new ADR to be placed on the map — the whole point, ADR-0109).
	for n := range adrs {
		if !tagged[n] {
			errs = append(errs, fmt.Sprintf("ADR %04d is not assigned to any subsystem in topics.json — add it", n))
		}
	}
	if len(errs) > 0 {
		sort.Strings(errs)
		fatalf("topics.json is invalid:\n  - %s", strings.Join(errs, "\n  - "))
	}
}

func render(o *ontology, adrs map[int]adrMeta) string {
	names := make([]string, 0, len(o.Subsystems))
	for name := range o.Subsystems {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("<!-- GENERATED by `task adr:index` from topics.json — DO NOT EDIT. Edit topics.json. (ADR-0109) -->\n")
	b.WriteString("# ADR Map — the knowledge graph\n\n")
	b.WriteString("A **generated navigation router** over the ADR corpus (ADR-0109): a subsystem graph, a\n")
	b.WriteString("by-topic index, and an ADR→subsystem reverse index. It is a *router*, not a reader — it points\n")
	b.WriteString("you at the 3–5 relevant ADRs to open, and surfaces *adjacent* subsystems whose decisions a new\n")
	b.WriteString("design must reconcile with. Chronological list: [README.md](README.md); phase view: [../roadmap.md](../roadmap.md).\n\n")

	// ── the subsystem graph ──────────────────────────────────────────────────
	b.WriteString("## Subsystem graph\n\n")
	b.WriteString("```mermaid\ngraph TD\n")
	for _, name := range names {
		s := o.Subsystems[name]
		b.WriteString(fmt.Sprintf("  %s[\"%s<br/><small>%s</small>\"]\n", nodeID(name), name, adrLabel(s.Adrs)))
	}
	b.WriteString("\n")
	for _, name := range names {
		for _, dep := range o.Subsystems[name].DependsOn {
			b.WriteString(fmt.Sprintf("  %s --> %s\n", nodeID(name), nodeID(dep)))
		}
	}
	b.WriteString("```\n\n")

	// ── by-topic index ───────────────────────────────────────────────────────
	b.WriteString("## By subsystem\n\n")
	for _, name := range names {
		s := o.Subsystems[name]
		b.WriteString(fmt.Sprintf("### %s\n\n%s.\n\n", name, s.Title))
		if len(s.DependsOn) > 0 {
			deps := append([]string(nil), s.DependsOn...)
			sort.Strings(deps)
			b.WriteString(fmt.Sprintf("*Depends on:* %s\n\n", strings.Join(deps, ", ")))
		}
		nums := append([]int(nil), s.Adrs...)
		sort.Ints(nums)
		for _, n := range nums {
			b.WriteString(fmt.Sprintf("- [ADR-%04d](%s.md) — %s\n", n, adrs[n].slug, adrs[n].title))
		}
		b.WriteString("\n")
	}

	// ── reverse index: ADR → subsystems ──────────────────────────────────────
	b.WriteString("## By ADR (reverse index)\n\n")
	b.WriteString("| ADR | Subsystems |\n|---|---|\n")
	rev := map[int][]string{}
	for _, name := range names {
		for _, n := range o.Subsystems[name].Adrs {
			rev[n] = append(rev[n], name)
		}
	}
	revNums := make([]int, 0, len(rev))
	for n := range rev {
		revNums = append(revNums, n)
	}
	sort.Ints(revNums)
	for _, n := range revNums {
		subs := rev[n]
		sort.Strings(subs)
		b.WriteString(fmt.Sprintf("| [%04d](%s.md) | %s |\n", n, adrs[n].slug, strings.Join(subs, ", ")))
	}
	return b.String()
}

// adrLabel renders a subsystem's ADR numbers for the mermaid node, wrapped so a dense node
// (e.g. policy-governance) stays legible.
func adrLabel(nums []int) string {
	ns := append([]int(nil), nums...)
	sort.Ints(ns)
	parts := make([]string, len(ns))
	for i, n := range ns {
		parts[i] = fmt.Sprintf("%04d", n)
	}
	var lines []string
	for i := 0; i < len(parts); i += 6 {
		end := i + 6
		if end > len(parts) {
			end = len(parts)
		}
		lines = append(lines, strings.Join(parts[i:end], " "))
	}
	return strings.Join(lines, "<br/>")
}

func nodeID(name string) string { return strings.ReplaceAll(name, "-", "_") }

func fatalf(format string, a ...any) {
	fmt.Fprintf(os.Stderr, "adrmap: "+format+"\n", a...)
	os.Exit(1)
}
