/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Views */
        get: operations["listViews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description View name (the `view://<name>` reference without scheme). */
                name: components["parameters"]["ViewName"];
            };
            cookie?: never;
        };
        /** Get a View (versioned, CaC-declared graph query) */
        get: operations["getView"];
        /**
         * Declare a View's selector (bumps the version on change)
         * @description Direct (api-path) declaration. Views owned by the Git-declared desired state (declaredBy=cac) are Git-only (charter §2.1) and this endpoint refuses them with 409 — edit the declarations repo instead.
         */
        put: operations["declareView"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views/{name}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description View name (the `view://<name>` reference without scheme). */
                name: components["parameters"]["ViewName"];
            };
            cookie?: never;
        };
        /** Resolve the View's live Entity set */
        get: operations["resolveView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get one Entity with its Facets and per-attribute Provenance */
        get: operations["getEntity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desired-state/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diff a declared desired state against the graph's Views
         * @description Dry run of reconciliation (charter §1.2: drift is the diff). Entries report the action, the selector change, and the live member count — blast radius before anything executes.
         */
        post: operations["desiredStatePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desired-state/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reconcile the graph's Views to a declared desired state
         * @description Applies the plan — creates/updates/adopts declared Views (owned as declaredBy=cac) and prunes cac Views no longer declared. api-declared Views are never pruned. Per-View failures are reported on their plan entries; the rest still applies.
         */
        post: operations["desiredStateApply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credential-refs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List CredentialRef pointers the Principal may read */
        get: operations["listCredentialRefs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credential-refs/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        /**
         * Get one CredentialRef pointer (reader grant required)
         * @description Returns pointer + injection policy metadata only. There is no endpoint that returns secret material — no such code path exists (charter §2.5, ADR-0009).
         */
        get: operations["getCredentialRef"];
        /** Declare a CredentialRef pointer (admin grant required) */
        put: operations["declareCredentialRef"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent Run summaries */
        get: operations["listRuns"];
        put?: never;
        /** Start a Run of the Phase-0 Workflow against a View */
        post: operations["startRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        /** Get a Run summary */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        /**
         * Live SSE tail of the Run's full task-event stream
         * @description Replays from the first event and follows live (NATS-backed). Never truncated — the full stream of any Run is reachable (ADR-0003 L1/L2). Ends with a `stream-end` event once the Run's stream closes.
         */
        get: operations["tailRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pinned Contracts
         * @description Every pinned Contract and Facet schema (charter §1.5, ADR-0015): the JSON Schema document, its sha256 pin, version, and derivation rung. The SchemaForm/SchemaTable rendering source (ADR-0003 L7/L8).
         */
        get: operations["listContracts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triggers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List declared Triggers
         * @description Triggers are CaC-only (ADR-0010): declared in the Git desired-state repo, where review authorizes the Principal binding. This surface is read-only; there is no API write path.
         */
        get: operations["listTriggers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triggers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        /**
         * Get one Trigger with its live schedule state
         * @description The declaration plus the Temporal Schedule's observed state — paused, next fire times, and the workflow ids of recent fired Runs: the Trigger → Run rung of the descent ladder (charter §1.8).
         */
        get: operations["getTrigger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List declared Workflows
         * @description Workflows are CaC-only in v1 (ADR-0011): declared in the Git desired-state repo. This surface is read-only.
         */
        get: operations["listWorkflows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        /** Get one Workflow declaration */
        get: operations["getWorkflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{name}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start one execution of a Workflow
         * @description The launching Principal rides every actuation Step's credential `use` check (charter §2.5), exactly as if it had started each Run directly.
         */
        post: operations["startWorkflowRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent WorkflowRuns */
        get: operations["listWorkflowRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get one WorkflowRun with per-Step outcomes
         * @description The Workflow → Run rung of the descent ladder (charter §1.8): each actuation Step links its Run id (tail its events via /runs/{id}/events), each Gate Step its Gate.
         */
        get: operations["getWorkflowRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Gates (the approval inbox) */
        get: operations["listGates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gates/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve or deny a pending Gate
         * @description Requires an authenticated Principal that the Gate's approver policy authorizes — listed explicitly or a member of an approver team (checked through the platform Authorizer, ADR-0009/0011). The decision is delivered to the waiting Workflow as a signal; the Workflow records it (202).
         */
        post: operations["decideGate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            message: string;
        };
        /** @description Per-attribute stamp — which Run/Syncer wrote the value, when, from which Source (charter §2.1). Always exactly one answer. */
        Provenance: {
            /** @enum {string} */
            writerKind: "syncer" | "run";
            writerRef: string;
            sourceId?: string;
            /** Format: date-time */
            at: string;
        };
        Entity: {
            id: string;
            kind: string;
            identityKeys: {
                [key: string]: string;
            };
            labels: {
                [key: string]: string;
            };
        };
        Facet: {
            namespace: string;
            /** @description The Facet document fragment (schema attaches per namespace, §1.1). */
            value: unknown;
            provenance: components["schemas"]["Provenance"];
        };
        EntityDocument: {
            entity: components["schemas"]["Entity"];
            facets: components["schemas"]["Facet"][];
        };
        FacetPredicate: {
            namespace: string;
            path?: string;
            /** @description JSON value the addressed field must equal. */
            equals: unknown;
        };
        /** @description Structured selector data — deliberately not an expression language (charter non-goal; ADR-0003 review). */
        ViewSelector: {
            kinds?: string[];
            labels?: {
                [key: string]: string;
            };
            facets?: components["schemas"]["FacetPredicate"][];
        };
        View: {
            name: string;
            /** Format: int64 */
            version: number;
            selector: components["schemas"]["ViewSelector"];
            /**
             * @description Which declaration path owns this View — cac (Git-declared desired state, charter §1.2) or api. cac Views are Git-only.
             * @enum {string}
             */
            readonly declaredBy?: "api" | "cac";
        };
        ViewDeclaration: {
            name: string;
            selector: components["schemas"]["ViewSelector"];
        };
        CredentialInjection: {
            /** @description Field within the backend material. */
            key: string;
            /** @enum {string} */
            as: "env" | "file";
            /** @description Env var name or path under the pod credentials mount. */
            name: string;
        };
        /** @description Pointer + injection policy to brokered secret material (charter §2.5). Material never persists in the platform and has no read path. */
        CredentialRef: {
            name: string;
            ownerTeam: string;
            /** @enum {string} */
            backend: "k8s-secret" | "vault" | "workload-identity";
            /** @description Backend-shaped address (k8s-secret: namespace, name). */
            locator: Record<string, never>;
            injection: components["schemas"]["CredentialInjection"][];
            /** @enum {string} */
            readonly declaredBy?: "api" | "cac";
        };
        /** @description The full declared desired state (charter §1.2). */
        DesiredState: {
            views: components["schemas"]["ViewDeclaration"][];
            credentialRefs?: components["schemas"]["CredentialRef"][];
            triggers?: components["schemas"]["Trigger"][];
            workflows?: components["schemas"]["Workflow"][];
        };
        PlanEntry: {
            /** @enum {string} */
            kind?: "view" | "credential-ref" | "trigger" | "workflow";
            name: string;
            /** @enum {string} */
            action: "create" | "update" | "adopt" | "noop" | "delete";
            /**
             * Format: int64
             * @description Live Entity count the relevant selector matches now.
             */
            memberCount: number;
            oldSelector?: components["schemas"]["ViewSelector"];
            newSelector?: components["schemas"]["ViewSelector"];
            error?: string;
        };
        Plan: {
            entries: components["schemas"]["PlanEntry"][];
        };
        ViewResolution: {
            view: components["schemas"]["View"];
            entities: components["schemas"]["Entity"][];
        };
        /** @description One Step against a View (charter §2.3: Step = Actuator + content + params). Params are interpreted by the named Actuator; their pinned JSON-Schema Contract documents land with the Phase-2 Contract machinery. */
        StartRun: {
            viewName: string;
            /**
             * @default ansible
             * @enum {string}
             */
            actuator: "ansible" | "script" | "opentofu";
            /** @description Actuator-interpreted Step params (e.g. script source). */
            params?: Record<string, never>;
            /**
             * Format: int64
             * @description Partition the target set across this many parallel execution Jobs (clamped to the target count).
             * @default 1
             */
            slices: number;
            /** @description CredentialRef names to project into the execution pods. The launching Principal needs the `use` grant on each (checked at dispatch; use never implies read — charter §2.5). */
            credentialRefs?: string[];
        };
        Run: {
            id: string;
            workflowId: string;
            /** @enum {string} */
            status: "pending" | "running" | "succeeded" | "failed" | "canceled";
            viewRef?: string;
            /** Format: int64 */
            viewVersion?: number;
            /** @description Name of the Trigger that fired this Run; absent for manual/API launches (charter §1.8 descent, Trigger → Run). */
            triggeredBy?: string;
            /** @description The WorkflowRun this Run executed under, when it ran as a Workflow Step (charter §1.8 descent, Workflow → Run). */
            workflowRunId?: string;
            /** @description The Step within that Workflow. */
            stepName?: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string;
        };
        /** @description A pinned JSON Schema document on a Step's inputs/outputs or a Facet namespace (charter §1.5, §2.2) — data, never a language class. */
        Contract: {
            /** @description e.g. actuators/script.input or facets/os.kernel */
            name: string;
            /** Format: int64 */
            version: number;
            /**
             * @description Derivation-ladder provenance of the schema (§2.2).
             * @enum {string}
             */
            rung: "hand-written" | "tool-derived" | "mcp-declared";
            /** @description sha256 over the exact document bytes, hex. */
            hash: string;
            /** @description The JSON Schema document. */
            schema: Record<string, never>;
        };
        /** @description Anything that starts a Run (charter §2). v1 kind is `schedule` — a Temporal Schedule fires Runs with these launch parameters, executing as the declared service Principal (ADR-0010). */
        Trigger: {
            name: string;
            /** @enum {string} */
            kind: "schedule";
            cron: string;
            paused?: boolean;
            viewName: string;
            actuator?: string;
            params?: Record<string, never>;
            /** Format: int64 */
            slices?: number;
            credentialRefs?: string[];
            /** @description Service identity the fired Runs execute as; its `use` grants are checked at dispatch exactly like an API launch (§2.5). */
            principal?: string;
        };
        TriggerDetail: {
            trigger: components["schemas"]["Trigger"];
            schedule?: components["schemas"]["TriggerScheduleState"];
        };
        /** @description A Temporal-backed DAG of Steps with Gates (charter §2, ADR-0011). CaC-only in v1. */
        Workflow: {
            name: string;
            steps: components["schemas"]["Step"][];
        };
        /** @description One DAG node — an actuation (Actuator + params against a View, charter §2.3) or a Gate; exactly one shape is set. */
        Step: {
            name: string;
            /** @description Step names that must reach a terminal state first. */
            needs?: string[];
            /**
             * @description Edge condition on the needs' outcomes; success is the default (all needs succeeded).
             * @enum {string}
             */
            when?: "success" | "failure" | "always";
            gate?: components["schemas"]["GateSpec"];
            viewName?: string;
            actuator?: string;
            params?: Record<string, never>;
            /** Format: int64 */
            slices?: number;
            credentialRefs?: string[];
        };
        GateSpec: {
            approvers: components["schemas"]["GateApprovers"];
            /**
             * Format: int64
             * @description Expire (treat as denial) after this long pending; 0 waits forever.
             */
            timeoutSeconds?: number;
        };
        /** @description Who may decide: Principals listed explicitly, or members of the listed teams (checked through the platform Authorizer). */
        GateApprovers: {
            principals?: string[];
            teams?: string[];
        };
        Gate: {
            id: string;
            workflowRunId: string;
            step: string;
            /** @enum {string} */
            status: "pending" | "approved" | "denied" | "expired";
            approvers: components["schemas"]["GateApprovers"];
            decidedBy?: string;
            note?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            decidedAt?: string;
        };
        GateDecision: {
            approve: boolean;
            note?: string;
        };
        WorkflowRun: {
            id: string;
            workflowName: string;
            temporalId?: string;
            /** @enum {string} */
            status: "pending" | "running" | "succeeded" | "failed" | "canceled";
            principal?: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string;
        };
        WorkflowRunDetail: {
            workflowRun: components["schemas"]["WorkflowRun"];
            steps: {
                name: string;
                /** @description Terminal outcome from the WorkflowRun summary (succeeded, failed, skipped); absent while the execution is live — descend into the linked Run or Gate for live state. */
                status?: string;
                /** @description The Step's Run (actuation Steps). */
                runId?: string;
                /** @description The Step's Gate (Gate Steps). */
                gateId?: string;
            }[];
        };
        /** @description Observed Temporal Schedule state; absent when the schedule has not been reconciled yet (e.g. within one interval of declaring). */
        TriggerScheduleState: {
            paused?: boolean;
            nextFireTimes?: string[];
            /** @description Workflow executions recently started by this Trigger. */
            recentRuns?: {
                workflowId: string;
                /** Format: date-time */
                at: string;
            }[];
        };
    };
    responses: {
        /** @description The named object does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request is malformed */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The object is owned by another declaration path */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The Principal lacks the required grant */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A Bearer token was presented but could not be verified (invalid, expired, or wrong issuer/audience). Written by the Principal middleware — a bad credential is 401, never downgraded to anonymous; an absent credential is anonymous and denied per-grant (403). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description View name (the `view://<name>` reference without scheme). */
        ViewName: string;
        RunID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listViews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every View, ordered by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"][];
                };
            };
        };
    };
    getView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description View name (the `view://<name>` reference without scheme). */
                name: components["parameters"]["ViewName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The View */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    declareView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description View name (the `view://<name>` reference without scheme). */
                name: components["parameters"]["ViewName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewSelector"];
            };
        };
        responses: {
            /** @description The declared View with its current version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    resolveView: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                /** @description View name (the `view://<name>` reference without scheme). */
                name: components["parameters"]["ViewName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The live Entity set and the View version it came from */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewResolution"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Entity document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDocument"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    desiredStatePlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesiredState"];
            };
        };
        responses: {
            /** @description The reconciliation plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    desiredStateApply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesiredState"];
            };
        };
        responses: {
            /** @description The realized plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listCredentialRefs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pointer metadata only — material has no read path. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialRef"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getCredentialRef: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The pointer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialRef"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    declareCredentialRef: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialRef"];
            };
        };
        responses: {
            /** @description The declared pointer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialRef"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent Runs, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
        };
    };
    startRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRun"];
            };
        };
        responses: {
            /** @description The created Run */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Run summary (events stream separately) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    tailRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream; each `data:` line is a RunEvent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listContracts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pinned Contracts, ordered by name and version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"][];
                };
            };
        };
    };
    listTriggers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every declared Trigger. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trigger"][];
                };
            };
        };
    };
    getTrigger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Trigger and its schedule state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listWorkflows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every declared Workflow. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"][];
                };
            };
        };
    };
    getWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Workflow. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    startWorkflowRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The created WorkflowRun. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listWorkflowRuns: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent executions, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"][];
                };
            };
        };
    };
    getWorkflowRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The execution and its Steps. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRunDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listGates: {
        parameters: {
            query?: {
                status?: "pending" | "approved" | "denied" | "expired";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gates, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gate"][];
                };
            };
        };
    };
    decideGate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GateDecision"];
            };
        };
        responses: {
            /** @description Decision accepted and signaled to the Workflow. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
