/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Views */
        get: operations["listViews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description View name (the `view://<name>` reference without scheme). */
                name: components["parameters"]["ViewName"];
            };
            cookie?: never;
        };
        /** Get a View (versioned, CaC-declared graph query) */
        get: operations["getView"];
        /**
         * Declare a View's selector (bumps the version on change)
         * @description Direct (api-path) declaration. Views owned by the Git-declared desired state (declaredBy=cac) are Git-only (charter §2.1) and this endpoint refuses them with 409 — edit the declarations repo instead.
         */
        put: operations["declareView"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views/{name}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description View name (the `view://<name>` reference without scheme). */
                name: components["parameters"]["ViewName"];
            };
            cookie?: never;
        };
        /** Resolve the View's live Entity set */
        get: operations["resolveView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get one Entity with its Facets and per-attribute Provenance */
        get: operations["getEntity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desired-state/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diff a declared desired state against the graph's Views
         * @description Dry run of reconciliation (charter §1.2: drift is the diff). Entries report the action, the selector change, and the live member count — blast radius before anything executes.
         */
        post: operations["desiredStatePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desired-state/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reconcile the graph's Views to a declared desired state
         * @description Applies the plan — creates/updates/adopts declared Views (owned as declaredBy=cac) and prunes cac Views no longer declared. api-declared Views are never pruned. Per-View failures are reported on their plan entries; the rest still applies.
         */
        post: operations["desiredStateApply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credential-refs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List CredentialRef pointers the Principal may read */
        get: operations["listCredentialRefs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credential-refs/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        /**
         * Get one CredentialRef pointer (reader grant required)
         * @description Returns pointer + injection policy metadata only. There is no endpoint that returns secret material — no such code path exists (charter §2.5, ADR-0009).
         */
        get: operations["getCredentialRef"];
        /** Declare a CredentialRef pointer (admin grant required) */
        put: operations["declareCredentialRef"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent Run summaries */
        get: operations["listRuns"];
        put?: never;
        /** Start a Run of the Phase-0 Workflow against a View */
        post: operations["startRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        /** Get a Run summary */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request cancellation of a running Run
         * @description Signals the Run's Temporal workflow to cancel; the workflow is the single writer of the canceled status and deletes the Run's K8s Job(s) (ADR-0026). A terminal Run is a no-op. 202 = accepted (async).
         */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        /**
         * Live SSE tail of the Run's full task-event stream
         * @description Replays from the first event and follows live (NATS-backed). Never truncated — the full stream of any Run is reachable (ADR-0003 L1/L2). Ends with a `stream-end` event once the Run's stream closes.
         */
        get: operations["tailRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pinned Contracts
         * @description Every pinned Contract and Facet schema (charter §1.5, ADR-0015): the JSON Schema document, its sha256 pin, version, and derivation rung. The SchemaForm/SchemaTable rendering source (ADR-0003 L7/L8).
         */
        get: operations["listContracts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emitters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List declared Emitters
         * @description Emitters are CaC-only event ingest points (ADR-0018). Declarations hold only token hashes — there is no secret to read here (§2.5).
         */
        get: operations["listEmitters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List declared Sites
         * @description Sites are CaC-declared remote execution loci (ADR-0032). The response merges the declaration with live agent status from the liveness KV (§1.2 — status is never persisted to the graph). Declarations hold no secret material (§2.5).
         */
        get: operations["listSites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one declared Site */
        get: operations["getSite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Per-Principal MCP usage accounting
         * @description Aggregated platform-MCP-server tool calls per (Principal, tool) — the charter §1.6 "cost/usage accounting per identity" record (ADR-0021). Phase-4 per-Principal cost analytics builds on it.
         */
        get: operations["listUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The audit stream
         * @description The one audit stream (charter §1.6, ADR-0034): a born-here, append-only, Principal-stamped, ordered ledger of who-did-what-when — the full access log. Cursor-paged by seq (pass the last seq as `since`). Privileged: requires a reader grant on audit:log (deny-by-default, unlike v1's open read endpoints).
         */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify the audit stream's tamper-evidence chain
         * @description Walks the sealed hash chain (ADR-0034, §1.8) and reports whether the ledger is intact: OK, or the first seq where a link is broken (altered content, a removed row, or a truncated tail). Requires a reader grant on audit:log.
         */
        get: operations["verifyAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/forward/{sink}/config": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sink: string;
            };
            cookie?: never;
        };
        /**
         * A SIEM sink's non-secret forwarding config
         * @description The declared Sink's non-secret egress config (kind/driver, endpoint, index, facility) — the stratt-forwarder reads it so the CaC Sink is the single source of truth (ADR-0034). The credential is never here; it is a CredentialRef injected into the forwarder pod (§2.5). Requires the forwarder grant on audit:log.
         */
        get: operations["getForwardConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/forward/{sink}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sink: string;
            };
            cookie?: never;
        };
        /**
         * The next audit batch to ship to a SIEM sink
         * @description Audit events in seq order after the sink's committed offset — the at-least-once egress read (ADR-0034). Repeated calls return the same batch until the forwarder reports delivery; the server owns the cursor. Requires the forwarder grant on audit:log.
         */
        get: operations["getForwardBatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/forward/{sink}/report": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sink: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report a SIEM delivery outcome
         * @description The forwarder reports the result of shipping a batch (ADR-0034, §1.8). A "delivered" report commits the sink's offset to throughSeq (only forward, never rewind) and records the delivery; a "failed" report records the failure for visibility but does NOT advance the offset — a dropped audit record is impossible-by-design, the batch re-ships until it succeeds. Requires the forwarder grant on audit:log.
         */
        post: operations["reportForward"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/forward/{sink}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sink: string;
            };
            cookie?: never;
        };
        /** A SIEM sink's recent delivery outcomes */
        get: operations["listForwardDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List declared Intents (CaC-only, ADR-0023) */
        get: operations["listIntents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List declared Assignments (CaC-only, ADR-0023) */
        get: operations["listAssignments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blueprints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List declared Blueprint versions (CaC-only, ADR-0023) */
        get: operations["listBlueprints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest Intent-compile status — membership deltas, pauses, errors
         * @description The §4.3 "stratt plan renders membership deltas" surface (ADR-0023): per-Assignment join/leave counts, max-delta pauses, and any compile errors from the most recent reconcile pass.
         */
        get: operations["getCompileStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/baselines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List declared Baselines
         * @description Baselines are CaC-only checkable desired state (charter §2.4, ADR-0019): a View selector + check Step + remediation Workflow ref + cadence. This surface is read-only; Git review authorizes the Principal binding.
         */
        get: operations["listBaselines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/baselines/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        /** Get a declared Baseline */
        get: operations["getBaseline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/{framework}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                framework: string;
            };
            cookie?: never;
        };
        /**
         * Compliance rollup for a framework
         * @description Aggregates framework-tagged Baselines (the controls) and their open Findings into a per-View posture score (charter §2.4). A control passes when no target in its View has an open Finding for it. Read-only over the existing Baseline/Finding surface — the benchmark is data, a pack ships the controls (ADR-0033).
         */
        get: operations["getComplianceReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access/recertification/{view}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                view: string;
            };
            cookie?: never;
        };
        /**
         * Access-recertification report for a View
         * @description The current host-access grants across a View (charter §2.4, ADR-0036): every observed access.grants tuple, joined against the desired Intent/Access grants (per-element provenance — which Intent/Assignment declared it), with unmanaged/rogue grants flagged. `grantSetHash` anchors an attestation; `status` is `overdue` when the View has never been attested or the last attestation is older than the recertification cadence — abandoned governance is never silent (§1.8). Read-only over the projected Facets and the audit stream.
         */
        get: operations["getAccessRecertification"];
        put?: never;
        /**
         * Attest a View's access grants (recertification)
         * @description Records a Principal's attestation that the View's current access grants are correct (charter §2.4, ADR-0036). The reviewed grant set is sealed as an object-locked Evidence bundle (WORM, ADR-0029) and the attestation is recorded in the one audit stream (action `access.recertify`, ADR-0034) — a SIEM-forwardable, tamper-evident sign-off. Requires the `runner` grant on the View (§2.5). `grantSetHash` must match the current set, else 409 — attesting stale state is refused (§1.8).
         */
        post: operations["attestAccessRecertification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Findings
         * @description Findings are drift/compliance results (charter §2.4): Entity + Baseline + observed-vs-expected diff + severity + Evidence ref (the check Run). One kind, framework-tagged; resolved Findings are kept as the audit history.
         */
        get: operations["listFindings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a Finding */
        get: operations["getFinding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/{id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get a Finding's Evidence manifest
         * @description The manifest for the Finding's sealed, object-locked audit bundle (charter §2.4, ADR-0029) — object key, sha256 integrity anchor, size, and retain-until. 404 when the Finding has no sealed Evidence.
         */
        get: operations["getFindingEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Download a sealed Evidence bundle (integrity-verified)
         * @description Streams the sealed audit bundle after re-verifying its sha256 against the manifest (§1.8: a tampered object is detected and refused, never served as authentic). 409 when the object fails the integrity check.
         */
        get: operations["downloadEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triggers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List declared Triggers
         * @description Triggers are CaC-only (ADR-0010): declared in the Git desired-state repo, where review authorizes the Principal binding. This surface is read-only; there is no API write path.
         */
        get: operations["listTriggers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triggers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        /**
         * Get one Trigger with its live schedule state
         * @description The declaration plus the Temporal Schedule's observed state — paused, next fire times, and the workflow ids of recent fired Runs: the Trigger → Run rung of the descent ladder (charter §1.8).
         */
        get: operations["getTrigger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List declared Workflows
         * @description Workflows are CaC-only in v1 (ADR-0011): declared in the Git desired-state repo. This surface is read-only.
         */
        get: operations["listWorkflows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        /** Get one Workflow declaration */
        get: operations["getWorkflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{name}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start one execution of a Workflow
         * @description The launching Principal rides every actuation Step's credential `use` check (charter §2.5), exactly as if it had started each Run directly.
         */
        post: operations["startWorkflowRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent WorkflowRuns */
        get: operations["listWorkflowRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get one WorkflowRun with per-Step outcomes
         * @description The Workflow → Run rung of the descent ladder (charter §1.8): each actuation Step links its Run id (tail its events via /runs/{id}/events), each Gate Step its Gate.
         */
        get: operations["getWorkflowRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Gates (the approval inbox) */
        get: operations["listGates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gates/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve or deny a pending Gate
         * @description Requires an authenticated Principal that the Gate's approver policy authorizes — listed explicitly or a member of an approver team (checked through the platform Authorizer, ADR-0009/0011). The decision is delivered to the waiting Workflow as a signal; the Workflow records it (202).
         */
        post: operations["decideGate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            message: string;
        };
        /** @description Per-attribute stamp — which Run/Syncer wrote the value, when, from which Source (charter §2.1). Always exactly one answer. */
        Provenance: {
            /** @enum {string} */
            writerKind: "syncer" | "run";
            writerRef: string;
            sourceId?: string;
            /** Format: date-time */
            at: string;
        };
        Entity: {
            id: string;
            kind: string;
            identityKeys: {
                [key: string]: string;
            };
            labels: {
                [key: string]: string;
            };
        };
        Facet: {
            namespace: string;
            /** @description The Facet document fragment (schema attaches per namespace, §1.1). */
            value: unknown;
            provenance: components["schemas"]["Provenance"];
        };
        EntityDocument: {
            entity: components["schemas"]["Entity"];
            facets: components["schemas"]["Facet"][];
        };
        FacetPredicate: {
            namespace: string;
            path?: string;
            /** @description JSON value the addressed field must equal. */
            equals: unknown;
        };
        /** @description Structured selector data — deliberately not an expression language (charter non-goal; ADR-0003 review). */
        ViewSelector: {
            kinds?: string[];
            labels?: {
                [key: string]: string;
            };
            facets?: components["schemas"]["FacetPredicate"][];
        };
        View: {
            name: string;
            /** Format: int64 */
            version: number;
            selector: components["schemas"]["ViewSelector"];
            /**
             * @description Which declaration path owns this View — cac (Git-declared desired state, charter §1.2) or api. cac Views are Git-only.
             * @enum {string}
             */
            readonly declaredBy?: "api" | "cac";
        };
        ViewDeclaration: {
            name: string;
            selector: components["schemas"]["ViewSelector"];
        };
        CredentialInjection: {
            /** @description Field within the backend material. */
            key: string;
            /** @enum {string} */
            as: "env" | "file";
            /** @description Env var name or path under the pod credentials mount. */
            name: string;
        };
        /** @description Pointer + injection policy to brokered secret material (charter §2.5). Material never persists in the platform and has no read path. */
        CredentialRef: {
            name: string;
            ownerTeam: string;
            /** @enum {string} */
            backend: "k8s-secret" | "vault" | "workload-identity";
            /** @description Backend-shaped address (k8s-secret: namespace, name). */
            locator: Record<string, never>;
            injection: components["schemas"]["CredentialInjection"][];
            /** @enum {string} */
            readonly declaredBy?: "api" | "cac";
        };
        /** @description The full declared desired state (charter §1.2). */
        DesiredState: {
            views: components["schemas"]["ViewDeclaration"][];
            credentialRefs?: components["schemas"]["CredentialRef"][];
            triggers?: components["schemas"]["Trigger"][];
            workflows?: components["schemas"]["Workflow"][];
            emitters?: components["schemas"]["Emitter"][];
            baselines?: components["schemas"]["Baseline"][];
            mcpServers?: components["schemas"]["MCPServer"][];
            intents?: components["schemas"]["Intent"][];
            assignments?: components["schemas"]["Assignment"][];
            blueprints?: components["schemas"]["Blueprint"][];
            sites?: components["schemas"]["Site"][];
        };
        PlanEntry: {
            /** @enum {string} */
            kind?: "view" | "credential-ref" | "trigger" | "workflow" | "emitter" | "baseline" | "mcp-server" | "intent" | "assignment" | "blueprint" | "site";
            name: string;
            /** @enum {string} */
            action: "create" | "update" | "adopt" | "noop" | "delete";
            /**
             * Format: int64
             * @description Live Entity count the relevant selector matches now.
             */
            memberCount: number;
            oldSelector?: components["schemas"]["ViewSelector"];
            newSelector?: components["schemas"]["ViewSelector"];
            /** @description A parametrized View whose membership binds at launch — memberCount is not meaningful and is omitted (ADR-0024). */
            paramDependent?: boolean;
            error?: string;
        };
        Plan: {
            entries: components["schemas"]["PlanEntry"][];
        };
        ViewResolution: {
            view: components["schemas"]["View"];
            entities: components["schemas"]["Entity"][];
        };
        /** @description One Step: an Actuator against a View (charter §2.3: Actuator + content + params), or a targetless Connector Action (Action + params, ADR-0031). Set viewName+actuator OR action, not both. */
        StartRun: {
            viewName?: string;
            /**
             * @default ansible
             * @enum {string}
             */
            actuator: "ansible" | "script" | "opentofu" | "mcp";
            /** @description A Connector Action (namespaced, e.g. certissuer/revoke). When set, this is a targetless typed operation — viewName/actuator are ignored and the CredentialRef `use` grant is the authz gate, not runner-on-View. */
            action?: string;
            /** @description Ask a DryRunnable Action to plan without side effects. */
            dryRun?: boolean;
            /** @description Actuator- or Action-interpreted Step params. */
            params?: Record<string, never>;
            /**
             * Format: int64
             * @description Partition the target set across this many parallel execution Jobs (clamped to the target count).
             * @default 1
             */
            slices: number;
            /** @description CredentialRef names to project into the execution pods. The launching Principal needs the `use` grant on each (checked at dispatch; use never implies read — charter §2.5). */
            credentialRefs?: string[];
        };
        Run: {
            id: string;
            workflowId: string;
            /** @enum {string} */
            status: "pending" | "running" | "succeeded" | "failed" | "canceled";
            viewRef?: string;
            /** Format: int64 */
            viewVersion?: number;
            /** @description Name of the Trigger that fired this Run; absent for manual/API launches (charter §1.8 descent, Trigger → Run). */
            triggeredBy?: string;
            /** @description Name of the Baseline whose cadence ran this check; absent for everything else (charter §1.8 descent, Baseline → Run). */
            baseline?: string;
            /** @description The WorkflowRun this Run executed under, when it ran as a Workflow Step (charter §1.8 descent, Workflow → Run). */
            workflowRunId?: string;
            /** @description The Step within that Workflow. */
            stepName?: string;
            /** @description An Action Run's typed output values, validated against the Action's output Contract (charter §2.2, ADR-0031); absent for Actuator Runs. */
            outputs?: Record<string, never>;
            /** @description The execution loci this Run touched (charter §1.8 descent, ADR-0032): ["local"], a Site name, or a union when per-target routing fanned the Run across Sites. Absent for legacy Runs and targetless Actions. */
            sites?: string[];
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string;
        };
        /** @description A remote execution locus — a satellite dispatcher reachable over a NATS leaf (charter §2.3, ADR-0032). CaC-declared; live up/down status is ephemeral (NATS KV), surfaced via the `live` field on reads. */
        Site: {
            name: string;
            /** @enum {string} */
            mode: "push" | "pull";
            /** @description The K8s namespace the Site's agent runs Jobs in. */
            namespace?: string;
            description?: string;
            /** @enum {string} */
            declaredBy?: "cac" | "api";
            /** @description Whether an agent for this Site is currently heartbeating (read-only, from the liveness KV; never persisted to the graph, §1.2). */
            live?: boolean;
        };
        Emitter: {
            name: string;
            /** @enum {string} */
            kind: "webhook" | "alertmanager";
            /** @description hex(sha256(token)) — never the token itself (§2.5). */
            tokenHash: string;
        };
        /** @description A CaC-declared external MCP server the mcp Actuator may invoke (charter §2.3, ADR-0022). stdio servers carry their entire source in the declaration — Git review authorizes exactly what the sandbox runs. rev keys the pinned tool Contracts (rung 3, drift blocking). */
        MCPServer: {
            name: string;
            /** @enum {string} */
            transport: "stdio" | "http";
            /** Format: int64 */
            rev: number;
            /** @description stdio server source (Git-reviewed, run verbatim). */
            script?: string;
            /** @description http server URL. */
            endpoint?: string;
            /** @description CredentialRef pointer for the http bearer token (never material, §2.5). */
            tokenRef?: {
                credentialRef: string;
                key: string;
            };
        };
        /** @description A declarative document of *what* (charter §2.4), bound to a View by an Assignment. CaC-only. v1: Intent/Application. */
        Intent: {
            name: string;
            kind: string;
            spec?: Record<string, never>;
            /** @enum {string} */
            onRemove?: "retain" | "revert" | "remove";
        };
        /** @description Binds an Intent to a cac-declared View, pinning a Blueprint version (charter §2.4). CaC-only. */
        Assignment: {
            name: string;
            intent: string;
            view: string;
            blueprint: string;
            /** Format: int64 */
            blueprintVersion: number;
            environments?: string[];
            /** @description Per-Assignment max-delta gate fraction override (§4.3). */
            maxDelta?: number;
            /**
             * Format: int64
             * @description Acknowledgement token to unblock a paused large delta.
             */
            ackDelta?: number;
        };
        /** @description A versioned composition (Intent × Assignment × View membership → Baselines + remediation refs), routed by capability-scoped Facets (charter §2.4). CaC-only. */
        Blueprint: {
            name: string;
            /** Format: int64 */
            version: number;
            for: string;
            /** @enum {string} */
            severity?: "info" | "warning" | "critical";
            /** Format: int64 */
            dampingObservations?: number;
            routes: components["schemas"]["BlueprintRoute"][];
        };
        BlueprintRoute: {
            match?: components["schemas"]["FacetPredicate"][];
            observe: components["schemas"]["FacetExpectation"];
            /** @enum {string} */
            claim: "exclusive" | "additive";
            /** @description Declared Workflow that remediates this route's Findings — a ref only (§5 Flow 2). */
            remediationWorkflow?: string;
        };
        FacetExpectation: {
            namespace: string;
            path?: string;
            equals?: unknown;
            contains?: unknown;
        };
        /** @description One Intent-compile pass summary (charter §4.3, ADR-0023). */
        CompileStatus: {
            /** Format: date-time */
            compiledAt?: string;
            /** Format: int64 */
            compiledBaselines?: number;
            errors?: string[];
            deltas?: components["schemas"]["AssignmentDelta"][];
        };
        AssignmentDelta: {
            assignment: string;
            /** Format: int64 */
            memberCount: number;
            joins?: string[];
            leaves?: string[];
            unrouted?: string[];
            paused?: boolean;
            note?: string;
        };
        /** @description One (Principal, tool) aggregate of platform-MCP-server calls (charter §1.6 accounting per identity, ADR-0021). */
        UsageEntry: {
            principal: string;
            /** @description human | service | agent (§2.5 — informational). */
            principalKind?: string;
            tool: string;
            /** Format: int64 */
            calls: number;
            /** Format: int64 */
            errors: number;
            /** Format: date-time */
            lastCall: string;
        };
        /** @description One entry in the audit stream (charter §1.6, ADR-0034): who did what, to what, with what outcome, when. Ordered by seq; hash-chained for tamper-evidence. */
        AuditEvent: {
            /**
             * Format: int64
             * @description Monotonic order + page cursor.
             */
            seq: number;
            /** Format: date-time */
            at: string;
            /** @description Acting identity; empty for an anonymous attempt. */
            principalId?: string;
            principalKind?: string;
            /** @description What was done (e.g. "run.start", "authz.exec-grant", a route pattern). */
            action: string;
            /** @description The target (View */
            object?: string;
            /** @description ok | denied | failed | an HTTP status. */
            outcome?: string;
            /** @description Optional structured context (never secret material, §2.5). */
            detail?: unknown;
            /** @description Whether the tamper-evidence chain covers this event yet. */
            sealed?: boolean;
        };
        /** @description Result of walking the tamper-evidence hash chain (ADR-0034, §1.8): OK, or the first seq where the chain breaks and why. */
        AuditVerification: {
            ok: boolean;
            /**
             * Format: int64
             * @description Highest seq the sealed chain covers.
             */
            sealedThrough: number;
            /**
             * Format: int64
             * @description Sealed events walked.
             */
            events: number;
            /** Format: int64 */
            firstBadSeq?: number;
            reason?: string;
        };
        /** @description A SIEM sink's non-secret forwarding config (ADR-0034) — the driver kind and destination the forwarder ships to. Never carries the credential. */
        ForwardConfig: {
            sink: string;
            /** @description splunk-hec | syslog | otel-logs */
            kind: string;
            endpoint: string;
            index?: string;
            facility?: number;
            insecure?: boolean;
        };
        /** @description A forwarder's report of shipping a batch (ADR-0034, §1.8). */
        ForwardReport: {
            /**
             * Format: int64
             * @description Highest seq in the batch.
             */
            throughSeq: number;
            count: number;
            /** @enum {string} */
            status: "delivered" | "failed";
            /** @description Non-secret failure summary (never the endpoint/token). */
            detail?: string;
        };
        /** @description One recorded SIEM-egress outcome (ADR-0034, §1.8). */
        ForwardDelivery: {
            sink: string;
            /** Format: int64 */
            throughSeq: number;
            count: number;
            status: string;
            detail?: string;
            /** Format: date-time */
            at: string;
        };
        /** @description Checkable desired state (charter §2.4, ADR-0019): View selector + check Step + optional remediation Workflow ref + cadence. v1 is the hand-written rung of the §6 ladder; checks are read-only by construction (ansible check mode, opentofu plan). */
        Baseline: {
            name: string;
            /** @description "" (check Step) or facet-observation (compiler-emitted, graph-side check — ADR-0023). */
            mode?: string;
            /** @description Origin of a compiler-emitted Baseline — the §1.8 descent from a Finding back to its Assignment/Blueprint (ADR-0023). Absent for hand-written Baselines. */
            compiledFrom?: {
                assignment?: string;
                intent?: string;
                blueprint?: string;
                /** Format: int64 */
                blueprintVersion?: number;
                /** Format: int64 */
                route?: number;
            };
            viewName: string;
            /**
             * @default ansible
             * @enum {string}
             */
            actuator: "ansible" | "opentofu";
            params?: Record<string, never>;
            /** Format: int64 */
            slices?: number;
            credentialRefs?: string[];
            /** @description Service identity the checks execute as (§2.5), exactly like a Trigger's. */
            principal?: string;
            /** @description Check cadence (a Temporal Schedule actuates it, §3). */
            cron: string;
            paused?: boolean;
            /**
             * @description Stamped onto every Finding this Baseline raises.
             * @enum {string}
             */
            severity: "info" | "warning" | "critical";
            /**
             * Format: int64
             * @description Flap damping (charter §4.3) — a Finding opens only after this many consecutive drifted observations. Default 1.
             */
            dampingObservations?: number;
            /** @description Declared Workflow that remediates this Baseline's Findings — a ref only, never auto-launched (§5 Flow 2, remediation behind Gates). */
            remediationWorkflow?: string;
            /** @description Compliance tag (e.g. cis) — Findings are framework-tagged (§2.4). */
            framework?: string;
        };
        /** @description The manifest for a Finding's sealed, object-locked audit bundle (charter §2.4, ADR-0029). The immutable bundle lives in the object store; this is the graph's pointer to it. sha256 is the tamper-evidence anchor. */
        Evidence: {
            id: string;
            findingId: string;
            baseline: string;
            target: string;
            objectKey: string;
            /** @description hex(sha256(bundle)) — the integrity/tamper-evidence anchor. */
            sha256: string;
            /** Format: int64 */
            sizeBytes: number;
            /** Format: date-time */
            sealedAt: string;
            /**
             * Format: date-time
             * @description Object-lock retain-until applied at seal time (WORM on a compliant store).
             */
            retainUntil: string;
        };
        /** @description A drift/compliance result (charter §2.4): Entity + Baseline + observed-vs-expected diff + severity + Evidence ref. One kind, framework-tagged. v1 Evidence is the redacted diff snapshot plus the check Run ref (runId). */
        Finding: {
            id: string;
            baseline: string;
            target: string;
            /** @description The Entity the target resolves to via the View's membership; absent for non-Entity targets (e.g. an opentofu workspace). */
            entityId?: string;
            /** @enum {string} */
            status: "pending" | "open" | "resolved";
            /** @enum {string} */
            severity: "info" | "warning" | "critical";
            framework?: string;
            /**
             * Format: int64
             * @description Drifted observations since the last clean one (§4.3 damping counter).
             */
            consecutiveDrifted: number;
            /** @description Latest observed-vs-expected detail (redacted, size-capped visibly). */
            diff?: unknown;
            /** @description The check Run behind the latest observation — the Evidence ref (§1.8). */
            runId?: string;
            /** Format: date-time */
            firstObserved: string;
            /** Format: date-time */
            lastObserved: string;
            /** Format: date-time */
            openedAt?: string;
            /** Format: date-time */
            resolvedAt?: string;
        };
        /** @description A framework's compliance posture (charter §2.4, ADR-0033): the framework-tagged Baselines are the controls, rolled up per View into a score. The benchmark is data — a pack ships the controls. */
        ComplianceReport: {
            framework: string;
            views: components["schemas"]["ComplianceViewScore"][];
        };
        ComplianceViewScore: {
            view: string;
            /**
             * Format: int64
             * @description Framework-tagged Baselines targeting this View.
             */
            controls: number;
            /** Format: int64 */
            passing: number;
            /** Format: int64 */
            failing: number;
            /**
             * Format: double
             * @description passing / controls (1.0 when there are no controls).
             */
            score: number;
            failingControls?: components["schemas"]["FailingControl"][];
        };
        FailingControl: {
            baseline: string;
            /** @enum {string} */
            severity: "info" | "warning" | "critical";
            /**
             * Format: int64
             * @description Open Findings this control has raised across the View's targets.
             */
            openFindings: number;
        };
        /** @description A View's host-access recertification report (charter §2.4, ADR-0036): the current grants with per-element provenance and an attestation anchor. `status` surfaces overdue governance (§1.8). */
        AccessRecertification: {
            view: string;
            /** @description hex(sha256(canonical grant set)) — the value an attestation pins. */
            grantSetHash: string;
            /**
             * Format: int64
             * @description Recertification cadence; a View unattested for longer is overdue.
             */
            cadenceDays: number;
            /**
             * @description overdue when never attested or the last attestation is older than the cadence.
             * @enum {string}
             */
            status: "overdue" | "current";
            /**
             * Format: date-time
             * @description When the View was last attested (absent = never).
             */
            lastAttested?: string;
            lastAttestedBy?: string;
            grants: components["schemas"]["AccessGrantReview"][];
        };
        /** @description One host-access grant under review: the {subject, kind, scope} tuple, the hosts it is observed on, and whether a desired Intent/Access manages it (unmanaged = rogue/undeclared access to review). `subject` is a host-local account, not the platform Principal Named Kind (§2). */
        AccessGrantReview: {
            subject: string;
            /** @enum {string} */
            kind: "sudo" | "group" | "authorized_key" | "account";
            scope: string;
            /** @description Entity ids on which this grant is observed. */
            hosts: string[];
            /** @description True when a desired Intent/Access declares this grant; false = unmanaged/rogue. */
            managed: boolean;
            /** @description The declaring Intent (when managed). */
            intent?: string;
            /** @description The declaring Assignment (when managed). */
            assignment?: string;
        };
        /** @description The grant-set hash the reviewer is attesting; must match the current set (§1.8). */
        AttestRequest: {
            grantSetHash: string;
            /** @description Optional reviewer note (recorded in the audit detail). */
            note?: string;
        };
        /** @description The sealed, audited attestation of a View's access grants (ADR-0036): the object-locked Evidence key + integrity anchor, and the attestor. The audit stream carries the durable record (action access.recertify). */
        AttestationReceipt: {
            view: string;
            grantSetHash: string;
            /** @description Object-store key of the sealed, WORM attestation bundle. */
            evidenceKey: string;
            /** @description hex(sha256(bundle)) — the tamper-evidence anchor. */
            sha256: string;
            /** Format: date-time */
            retainUntil: string;
            attestedBy: string;
        };
        /** @description A pinned JSON Schema document on a Step's inputs/outputs or a Facet namespace (charter §1.5, §2.2) — data, never a language class. */
        Contract: {
            /** @description e.g. actuators/script.input or facets/os.kernel */
            name: string;
            /** Format: int64 */
            version: number;
            /**
             * @description Derivation-ladder provenance of the schema (§2.2).
             * @enum {string}
             */
            rung: "hand-written" | "tool-derived" | "mcp-declared";
            /** @description sha256 over the exact document bytes, hex. */
            hash: string;
            /** @description The JSON Schema document. */
            schema: Record<string, never>;
        };
        /** @description Anything that starts a Run or Workflow (charter §2): kind schedule (Temporal Schedule, ADR-0010) or kind event (Emitter event × CEL rule, ADR-0018), executing as the declared service Principal. */
        Trigger: {
            name: string;
            /** @enum {string} */
            kind: "schedule" | "event";
            cron?: string;
            paused?: boolean;
            /** @description Event source (kind event). */
            emitter?: string;
            /** @description CEL rule over the event payload (kind event). */
            when?: string;
            /** Format: int64 */
            cooldownSeconds?: number;
            /** @description Launch a declared Workflow instead of a single Run. */
            workflowName?: string;
            viewName?: string;
            /** @description Binds a parametrized View's {{.param.x}} placeholders; values may reference the firing event ({{.event.x}}) — ADR-0024. */
            viewParams?: Record<string, never>;
            actuator?: string;
            params?: Record<string, never>;
            /** Format: int64 */
            slices?: number;
            credentialRefs?: string[];
            /** @description Service identity the fired Runs execute as; its `use` grants are checked at dispatch exactly like an API launch (§2.5). */
            principal?: string;
        };
        TriggerDetail: {
            trigger: components["schemas"]["Trigger"];
            schedule?: components["schemas"]["TriggerScheduleState"];
        };
        /** @description A Temporal-backed DAG of Steps with Gates (charter §2, ADR-0011). CaC-only in v1. */
        Workflow: {
            name: string;
            steps: components["schemas"]["Step"][];
        };
        /** @description One DAG node — an actuation (Actuator + params against a View, charter §2.3) or a Gate; exactly one shape is set. */
        Step: {
            name: string;
            /** @description Step names that must reach a terminal state first. */
            needs?: string[];
            /**
             * @description Edge condition on the needs' outcomes; success is the default (all needs succeeded).
             * @enum {string}
             */
            when?: "success" | "failure" | "always";
            gate?: components["schemas"]["GateSpec"];
            viewName?: string;
            actuator?: string;
            params?: Record<string, never>;
            /** Format: int64 */
            slices?: number;
            credentialRefs?: string[];
        };
        GateSpec: {
            approvers: components["schemas"]["GateApprovers"];
            /**
             * Format: int64
             * @description Expire (treat as denial) after this long pending; 0 waits forever.
             */
            timeoutSeconds?: number;
        };
        /** @description Who may decide: Principals listed explicitly, or members of the listed teams (checked through the platform Authorizer). */
        GateApprovers: {
            principals?: string[];
            teams?: string[];
        };
        Gate: {
            id: string;
            workflowRunId: string;
            step: string;
            /** @enum {string} */
            status: "pending" | "approved" | "denied" | "expired";
            approvers: components["schemas"]["GateApprovers"];
            decidedBy?: string;
            note?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            decidedAt?: string;
        };
        GateDecision: {
            approve: boolean;
            note?: string;
        };
        WorkflowRun: {
            id: string;
            workflowName: string;
            temporalId?: string;
            /** @description Trigger that fired this execution (§1.8 descent). */
            triggeredBy?: string;
            /** @enum {string} */
            status: "pending" | "running" | "succeeded" | "failed" | "canceled";
            principal?: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string;
        };
        WorkflowRunDetail: {
            workflowRun: components["schemas"]["WorkflowRun"];
            steps: {
                name: string;
                /** @description Terminal outcome from the WorkflowRun summary (succeeded, failed, skipped); absent while the execution is live — descend into the linked Run or Gate for live state. */
                status?: string;
                /** @description The Step's Run (actuation Steps). */
                runId?: string;
                /** @description The Step's Gate (Gate Steps). */
                gateId?: string;
            }[];
        };
        /** @description Observed Temporal Schedule state; absent when the schedule has not been reconciled yet (e.g. within one interval of declaring). */
        TriggerScheduleState: {
            paused?: boolean;
            nextFireTimes?: string[];
            /** @description Workflow executions recently started by this Trigger. */
            recentRuns?: {
                workflowId: string;
                /** Format: date-time */
                at: string;
            }[];
        };
    };
    responses: {
        /** @description The named object does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request is malformed */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The object is owned by another declaration path */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The Principal lacks the required grant */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A Bearer token was presented but could not be verified (invalid, expired, or wrong issuer/audience). Written by the Principal middleware — a bad credential is 401, never downgraded to anonymous; an absent credential is anonymous and denied per-grant (403). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description View name (the `view://<name>` reference without scheme). */
        ViewName: string;
        RunID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listViews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every View, ordered by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"][];
                };
            };
        };
    };
    getView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description View name (the `view://<name>` reference without scheme). */
                name: components["parameters"]["ViewName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The View */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    declareView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description View name (the `view://<name>` reference without scheme). */
                name: components["parameters"]["ViewName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewSelector"];
            };
        };
        responses: {
            /** @description The declared View with its current version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    resolveView: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                /** @description View name (the `view://<name>` reference without scheme). */
                name: components["parameters"]["ViewName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The live Entity set and the View version it came from */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewResolution"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Entity document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDocument"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    desiredStatePlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesiredState"];
            };
        };
        responses: {
            /** @description The reconciliation plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    desiredStateApply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesiredState"];
            };
        };
        responses: {
            /** @description The realized plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listCredentialRefs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pointer metadata only — material has no read path. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialRef"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getCredentialRef: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The pointer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialRef"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    declareCredentialRef: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialRef"];
            };
        };
        responses: {
            /** @description The declared pointer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialRef"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent Runs, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
        };
    };
    startRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRun"];
            };
        };
        responses: {
            /** @description The created Run */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Run summary (events stream separately) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    tailRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream; each `data:` line is a RunEvent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listContracts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pinned Contracts, ordered by name and version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"][];
                };
            };
        };
    };
    listEmitters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every declared Emitter. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Emitter"][];
                };
            };
        };
    };
    listSites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every declared Site, with live status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"][];
                };
            };
        };
    };
    getSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Site declaration with live status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            /** @description No such Site. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUsage: {
        parameters: {
            query?: {
                principal?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage aggregates, ordered by principal then tool. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageEntry"][];
                };
            };
        };
    };
    listAudit: {
        parameters: {
            query?: {
                /** @description Return events with seq greater than this (the page cursor). */
                since?: number;
                principal?: string;
                action?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events in seq order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    verifyAudit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The verification result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerification"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getForwardConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sink: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sink's forwarding config. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForwardConfig"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getForwardBatch: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                sink: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The next batch (empty when caught up). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    reportForward: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sink: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForwardReport"];
            };
        };
        responses: {
            /** @description Recorded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listForwardDeliveries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sink: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent deliveries, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForwardDelivery"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listIntents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every declared Intent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Intent"][];
                };
            };
        };
    };
    listAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every declared Assignment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"][];
                };
            };
        };
    };
    listBlueprints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every declared Blueprint version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blueprint"][];
                };
            };
        };
    };
    getCompileStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The latest compile pass summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileStatus"];
                };
            };
        };
    };
    listBaselines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every declared Baseline. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Baseline"][];
                };
            };
        };
    };
    getBaseline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Baseline declaration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Baseline"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getComplianceReport: {
        parameters: {
            query?: {
                view?: string;
            };
            header?: never;
            path: {
                framework: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The framework's per-View compliance rollup. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceReport"];
                };
            };
        };
    };
    getAccessRecertification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                view: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The View's access-recertification report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRecertification"];
                };
            };
        };
    };
    attestAccessRecertification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                view: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttestRequest"];
            };
        };
        responses: {
            /** @description The sealed attestation receipt. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttestationReceipt"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    listFindings: {
        parameters: {
            query?: {
                baseline?: string;
                status?: "pending" | "open" | "resolved";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Findings, newest observation first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"][];
                };
            };
        };
    };
    getFinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Finding. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getFindingEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Evidence manifest. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    downloadEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sealed bundle. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: components["responses"]["NotFound"];
            /** @description The object failed its integrity check (tampered). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTriggers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every declared Trigger. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trigger"][];
                };
            };
        };
    };
    getTrigger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Trigger and its schedule state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listWorkflows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every declared Workflow. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"][];
                };
            };
        };
    };
    getWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Workflow. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    startWorkflowRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The created WorkflowRun. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listWorkflowRuns: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent executions, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"][];
                };
            };
        };
    };
    getWorkflowRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The execution and its Steps. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRunDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listGates: {
        parameters: {
            query?: {
                status?: "pending" | "approved" | "denied" | "expired";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gates, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gate"][];
                };
            };
        };
    };
    decideGate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GateDecision"];
            };
        };
        responses: {
            /** @description Decision accepted and signaled to the Workflow. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
