/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as EntitiesIdRouteImport } from './routes/entities/$id'
import { Route as FindingsIndexRouteImport } from './routes/findings/index'
import { Route as FindingsIdRouteImport } from './routes/findings/$id'
import { Route as GraphIndexRouteImport } from './routes/graph/index'
import { Route as IntentsIndexRouteImport } from './routes/intents/index'
import { Route as IntentsNameRouteImport } from './routes/intents/$name'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as RunsIdRouteImport } from './routes/runs/$id'
import { Route as RunsApprovalsRouteImport } from './routes/runs/approvals'
import { Route as ViewsNameRouteImport } from './routes/views/$name'
import { Route as WorkflowRunsIdRouteImport } from './routes/workflow-runs/$id'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as WorkflowsNameRouteImport } from './routes/workflows/$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesIdRoute = EntitiesIdRouteImport.update({
  id: '/entities/$id',
  path: '/entities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsIndexRoute = FindingsIndexRouteImport.update({
  id: '/findings/',
  path: '/findings/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsIdRoute = FindingsIdRouteImport.update({
  id: '/findings/$id',
  path: '/findings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphIndexRoute = GraphIndexRouteImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntentsIndexRoute = IntentsIndexRouteImport.update({
  id: '/intents/',
  path: '/intents/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntentsNameRoute = IntentsNameRouteImport.update({
  id: '/intents/$name',
  path: '/intents/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsApprovalsRoute = RunsApprovalsRouteImport.update({
  id: '/runs/approvals',
  path: '/runs/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewsNameRoute = ViewsNameRouteImport.update({
  id: '/views/$name',
  path: '/views/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRunsIdRoute = WorkflowRunsIdRouteImport.update({
  id: '/workflow-runs/$id',
  path: '/workflow-runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsNameRoute = WorkflowsNameRouteImport.update({
  id: '/workflows/$name',
  path: '/workflows/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connectors': typeof ConnectorsRoute
  '/fleet': typeof FleetRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/findings/$id': typeof FindingsIdRoute
  '/intents/$name': typeof IntentsNameRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/approvals': typeof RunsApprovalsRoute
  '/views/$name': typeof ViewsNameRoute
  '/workflow-runs/$id': typeof WorkflowRunsIdRoute
  '/workflows/$name': typeof WorkflowsNameRoute
  '/findings/': typeof FindingsIndexRoute
  '/graph/': typeof GraphIndexRoute
  '/intents/': typeof IntentsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connectors': typeof ConnectorsRoute
  '/fleet': typeof FleetRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/findings/$id': typeof FindingsIdRoute
  '/intents/$name': typeof IntentsNameRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/approvals': typeof RunsApprovalsRoute
  '/views/$name': typeof ViewsNameRoute
  '/workflow-runs/$id': typeof WorkflowRunsIdRoute
  '/workflows/$name': typeof WorkflowsNameRoute
  '/findings': typeof FindingsIndexRoute
  '/graph': typeof GraphIndexRoute
  '/intents': typeof IntentsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connectors': typeof ConnectorsRoute
  '/fleet': typeof FleetRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/findings/$id': typeof FindingsIdRoute
  '/intents/$name': typeof IntentsNameRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/approvals': typeof RunsApprovalsRoute
  '/views/$name': typeof ViewsNameRoute
  '/workflow-runs/$id': typeof WorkflowRunsIdRoute
  '/workflows/$name': typeof WorkflowsNameRoute
  '/findings/': typeof FindingsIndexRoute
  '/graph/': typeof GraphIndexRoute
  '/intents/': typeof IntentsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/connectors'
    | '/fleet'
    | '/entities/$id'
    | '/findings/$id'
    | '/intents/$name'
    | '/runs/$id'
    | '/runs/approvals'
    | '/views/$name'
    | '/workflow-runs/$id'
    | '/workflows/$name'
    | '/findings/'
    | '/graph/'
    | '/intents/'
    | '/runs/'
    | '/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/connectors'
    | '/fleet'
    | '/entities/$id'
    | '/findings/$id'
    | '/intents/$name'
    | '/runs/$id'
    | '/runs/approvals'
    | '/views/$name'
    | '/workflow-runs/$id'
    | '/workflows/$name'
    | '/findings'
    | '/graph'
    | '/intents'
    | '/runs'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/connectors'
    | '/fleet'
    | '/entities/$id'
    | '/findings/$id'
    | '/intents/$name'
    | '/runs/$id'
    | '/runs/approvals'
    | '/views/$name'
    | '/workflow-runs/$id'
    | '/workflows/$name'
    | '/findings/'
    | '/graph/'
    | '/intents/'
    | '/runs/'
    | '/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConnectorsRoute: typeof ConnectorsRoute
  FleetRoute: typeof FleetRoute
  EntitiesIdRoute: typeof EntitiesIdRoute
  FindingsIdRoute: typeof FindingsIdRoute
  IntentsNameRoute: typeof IntentsNameRoute
  RunsIdRoute: typeof RunsIdRoute
  RunsApprovalsRoute: typeof RunsApprovalsRoute
  ViewsNameRoute: typeof ViewsNameRoute
  WorkflowRunsIdRoute: typeof WorkflowRunsIdRoute
  WorkflowsNameRoute: typeof WorkflowsNameRoute
  FindingsIndexRoute: typeof FindingsIndexRoute
  GraphIndexRoute: typeof GraphIndexRoute
  IntentsIndexRoute: typeof IntentsIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$id': {
      id: '/entities/$id'
      path: '/entities/$id'
      fullPath: '/entities/$id'
      preLoaderRoute: typeof EntitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/': {
      id: '/findings/'
      path: '/findings'
      fullPath: '/findings/'
      preLoaderRoute: typeof FindingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/$id': {
      id: '/findings/$id'
      path: '/findings/$id'
      fullPath: '/findings/$id'
      preLoaderRoute: typeof FindingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph/': {
      id: '/graph/'
      path: '/graph'
      fullPath: '/graph/'
      preLoaderRoute: typeof GraphIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intents/': {
      id: '/intents/'
      path: '/intents'
      fullPath: '/intents/'
      preLoaderRoute: typeof IntentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intents/$name': {
      id: '/intents/$name'
      path: '/intents/$name'
      fullPath: '/intents/$name'
      preLoaderRoute: typeof IntentsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/approvals': {
      id: '/runs/approvals'
      path: '/runs/approvals'
      fullPath: '/runs/approvals'
      preLoaderRoute: typeof RunsApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/views/$name': {
      id: '/views/$name'
      path: '/views/$name'
      fullPath: '/views/$name'
      preLoaderRoute: typeof ViewsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-runs/$id': {
      id: '/workflow-runs/$id'
      path: '/workflow-runs/$id'
      fullPath: '/workflow-runs/$id'
      preLoaderRoute: typeof WorkflowRunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$name': {
      id: '/workflows/$name'
      path: '/workflows/$name'
      fullPath: '/workflows/$name'
      preLoaderRoute: typeof WorkflowsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConnectorsRoute: ConnectorsRoute,
  FleetRoute: FleetRoute,
  EntitiesIdRoute: EntitiesIdRoute,
  FindingsIdRoute: FindingsIdRoute,
  IntentsNameRoute: IntentsNameRoute,
  RunsIdRoute: RunsIdRoute,
  RunsApprovalsRoute: RunsApprovalsRoute,
  ViewsNameRoute: ViewsNameRoute,
  WorkflowRunsIdRoute: WorkflowRunsIdRoute,
  WorkflowsNameRoute: WorkflowsNameRoute,
  FindingsIndexRoute: FindingsIndexRoute,
  GraphIndexRoute: GraphIndexRoute,
  IntentsIndexRoute: IntentsIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
