//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ContractRung.
const (
	HandWritten ContractRung = "hand-written"
	McpDeclared ContractRung = "mcp-declared"
	ToolDerived ContractRung = "tool-derived"
)

// Valid indicates whether the value is a known member of the ContractRung enum.
func (e ContractRung) Valid() bool {
	switch e {
	case HandWritten:
		return true
	case McpDeclared:
		return true
	case ToolDerived:
		return true
	default:
		return false
	}
}

// Defines values for CredentialInjectionAs.
const (
	Env  CredentialInjectionAs = "env"
	File CredentialInjectionAs = "file"
)

// Valid indicates whether the value is a known member of the CredentialInjectionAs enum.
func (e CredentialInjectionAs) Valid() bool {
	switch e {
	case Env:
		return true
	case File:
		return true
	default:
		return false
	}
}

// Defines values for CredentialRefBackend.
const (
	K8sSecret        CredentialRefBackend = "k8s-secret"
	Vault            CredentialRefBackend = "vault"
	WorkloadIdentity CredentialRefBackend = "workload-identity"
)

// Valid indicates whether the value is a known member of the CredentialRefBackend enum.
func (e CredentialRefBackend) Valid() bool {
	switch e {
	case K8sSecret:
		return true
	case Vault:
		return true
	case WorkloadIdentity:
		return true
	default:
		return false
	}
}

// Defines values for CredentialRefDeclaredBy.
const (
	CredentialRefDeclaredByApi CredentialRefDeclaredBy = "api"
	CredentialRefDeclaredByCac CredentialRefDeclaredBy = "cac"
)

// Valid indicates whether the value is a known member of the CredentialRefDeclaredBy enum.
func (e CredentialRefDeclaredBy) Valid() bool {
	switch e {
	case CredentialRefDeclaredByApi:
		return true
	case CredentialRefDeclaredByCac:
		return true
	default:
		return false
	}
}

// Defines values for GateStatus.
const (
	GateStatusApproved GateStatus = "approved"
	GateStatusDenied   GateStatus = "denied"
	GateStatusExpired  GateStatus = "expired"
	GateStatusPending  GateStatus = "pending"
)

// Valid indicates whether the value is a known member of the GateStatus enum.
func (e GateStatus) Valid() bool {
	switch e {
	case GateStatusApproved:
		return true
	case GateStatusDenied:
		return true
	case GateStatusExpired:
		return true
	case GateStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for PlanEntryAction.
const (
	Adopt  PlanEntryAction = "adopt"
	Create PlanEntryAction = "create"
	Delete PlanEntryAction = "delete"
	Noop   PlanEntryAction = "noop"
	Update PlanEntryAction = "update"
)

// Valid indicates whether the value is a known member of the PlanEntryAction enum.
func (e PlanEntryAction) Valid() bool {
	switch e {
	case Adopt:
		return true
	case Create:
		return true
	case Delete:
		return true
	case Noop:
		return true
	case Update:
		return true
	default:
		return false
	}
}

// Defines values for PlanEntryKind.
const (
	PlanEntryKindCredentialRef PlanEntryKind = "credential-ref"
	PlanEntryKindTrigger       PlanEntryKind = "trigger"
	PlanEntryKindView          PlanEntryKind = "view"
	PlanEntryKindWorkflow      PlanEntryKind = "workflow"
)

// Valid indicates whether the value is a known member of the PlanEntryKind enum.
func (e PlanEntryKind) Valid() bool {
	switch e {
	case PlanEntryKindCredentialRef:
		return true
	case PlanEntryKindTrigger:
		return true
	case PlanEntryKindView:
		return true
	case PlanEntryKindWorkflow:
		return true
	default:
		return false
	}
}

// Defines values for ProvenanceWriterKind.
const (
	ProvenanceWriterKindRun    ProvenanceWriterKind = "run"
	ProvenanceWriterKindSyncer ProvenanceWriterKind = "syncer"
)

// Valid indicates whether the value is a known member of the ProvenanceWriterKind enum.
func (e ProvenanceWriterKind) Valid() bool {
	switch e {
	case ProvenanceWriterKindRun:
		return true
	case ProvenanceWriterKindSyncer:
		return true
	default:
		return false
	}
}

// Defines values for RunStatus.
const (
	RunStatusCanceled  RunStatus = "canceled"
	RunStatusFailed    RunStatus = "failed"
	RunStatusPending   RunStatus = "pending"
	RunStatusRunning   RunStatus = "running"
	RunStatusSucceeded RunStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the RunStatus enum.
func (e RunStatus) Valid() bool {
	switch e {
	case RunStatusCanceled:
		return true
	case RunStatusFailed:
		return true
	case RunStatusPending:
		return true
	case RunStatusRunning:
		return true
	case RunStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for StartRunActuator.
const (
	Ansible  StartRunActuator = "ansible"
	Opentofu StartRunActuator = "opentofu"
	Script   StartRunActuator = "script"
)

// Valid indicates whether the value is a known member of the StartRunActuator enum.
func (e StartRunActuator) Valid() bool {
	switch e {
	case Ansible:
		return true
	case Opentofu:
		return true
	case Script:
		return true
	default:
		return false
	}
}

// Defines values for StepWhen.
const (
	Always  StepWhen = "always"
	Failure StepWhen = "failure"
	Success StepWhen = "success"
)

// Valid indicates whether the value is a known member of the StepWhen enum.
func (e StepWhen) Valid() bool {
	switch e {
	case Always:
		return true
	case Failure:
		return true
	case Success:
		return true
	default:
		return false
	}
}

// Defines values for TriggerKind.
const (
	Schedule TriggerKind = "schedule"
)

// Valid indicates whether the value is a known member of the TriggerKind enum.
func (e TriggerKind) Valid() bool {
	switch e {
	case Schedule:
		return true
	default:
		return false
	}
}

// Defines values for ViewDeclaredBy.
const (
	ViewDeclaredByApi ViewDeclaredBy = "api"
	ViewDeclaredByCac ViewDeclaredBy = "cac"
)

// Valid indicates whether the value is a known member of the ViewDeclaredBy enum.
func (e ViewDeclaredBy) Valid() bool {
	switch e {
	case ViewDeclaredByApi:
		return true
	case ViewDeclaredByCac:
		return true
	default:
		return false
	}
}

// Defines values for WorkflowRunStatus.
const (
	WorkflowRunStatusCanceled  WorkflowRunStatus = "canceled"
	WorkflowRunStatusFailed    WorkflowRunStatus = "failed"
	WorkflowRunStatusPending   WorkflowRunStatus = "pending"
	WorkflowRunStatusRunning   WorkflowRunStatus = "running"
	WorkflowRunStatusSucceeded WorkflowRunStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the WorkflowRunStatus enum.
func (e WorkflowRunStatus) Valid() bool {
	switch e {
	case WorkflowRunStatusCanceled:
		return true
	case WorkflowRunStatusFailed:
		return true
	case WorkflowRunStatusPending:
		return true
	case WorkflowRunStatusRunning:
		return true
	case WorkflowRunStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for ListGatesParamsStatus.
const (
	ListGatesParamsStatusApproved ListGatesParamsStatus = "approved"
	ListGatesParamsStatusDenied   ListGatesParamsStatus = "denied"
	ListGatesParamsStatusExpired  ListGatesParamsStatus = "expired"
	ListGatesParamsStatusPending  ListGatesParamsStatus = "pending"
)

// Valid indicates whether the value is a known member of the ListGatesParamsStatus enum.
func (e ListGatesParamsStatus) Valid() bool {
	switch e {
	case ListGatesParamsStatusApproved:
		return true
	case ListGatesParamsStatusDenied:
		return true
	case ListGatesParamsStatusExpired:
		return true
	case ListGatesParamsStatusPending:
		return true
	default:
		return false
	}
}

// Contract A pinned JSON Schema document on a Step's inputs/outputs or a Facet namespace (charter §1.5, §2.2) — data, never a language class.
type Contract struct {
	// Hash sha256 over the exact document bytes, hex.
	Hash string `json:"hash"`

	// Name e.g. actuators/script.input or facets/os.kernel
	Name string `json:"name"`

	// Rung Derivation-ladder provenance of the schema (§2.2).
	Rung ContractRung `json:"rung"`

	// Schema The JSON Schema document.
	Schema  map[string]interface{} `json:"schema"`
	Version int64                  `json:"version"`
}

// ContractRung Derivation-ladder provenance of the schema (§2.2).
type ContractRung string

// CredentialInjection defines model for CredentialInjection.
type CredentialInjection struct {
	As CredentialInjectionAs `json:"as"`

	// Key Field within the backend material.
	Key string `json:"key"`

	// Name Env var name or path under the pod credentials mount.
	Name string `json:"name"`
}

// CredentialInjectionAs defines model for CredentialInjection.As.
type CredentialInjectionAs string

// CredentialRef Pointer + injection policy to brokered secret material (charter §2.5). Material never persists in the platform and has no read path.
type CredentialRef struct {
	Backend    CredentialRefBackend     `json:"backend"`
	DeclaredBy *CredentialRefDeclaredBy `json:"declaredBy,omitempty"`
	Injection  []CredentialInjection    `json:"injection"`

	// Locator Backend-shaped address (k8s-secret: namespace, name).
	Locator   map[string]interface{} `json:"locator"`
	Name      string                 `json:"name"`
	OwnerTeam string                 `json:"ownerTeam"`
}

// CredentialRefBackend defines model for CredentialRef.Backend.
type CredentialRefBackend string

// CredentialRefDeclaredBy defines model for CredentialRef.DeclaredBy.
type CredentialRefDeclaredBy string

// DesiredState The full declared desired state (charter §1.2).
type DesiredState struct {
	CredentialRefs *[]CredentialRef  `json:"credentialRefs,omitempty"`
	Triggers       *[]Trigger        `json:"triggers,omitempty"`
	Views          []ViewDeclaration `json:"views"`
	Workflows      *[]Workflow       `json:"workflows,omitempty"`
}

// Entity defines model for Entity.
type Entity struct {
	Id           string            `json:"id"`
	IdentityKeys map[string]string `json:"identityKeys"`
	Kind         string            `json:"kind"`
	Labels       map[string]string `json:"labels"`
}

// EntityDocument defines model for EntityDocument.
type EntityDocument struct {
	Entity Entity  `json:"entity"`
	Facets []Facet `json:"facets"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Facet defines model for Facet.
type Facet struct {
	Namespace string `json:"namespace"`

	// Provenance Per-attribute stamp — which Run/Syncer wrote the value, when, from which Source (charter §2.1). Always exactly one answer.
	Provenance Provenance `json:"provenance"`

	// Value The Facet document fragment (schema attaches per namespace, §1.1).
	Value interface{} `json:"value"`
}

// FacetPredicate defines model for FacetPredicate.
type FacetPredicate struct {
	// Equals JSON value the addressed field must equal.
	Equals    interface{} `json:"equals"`
	Namespace string      `json:"namespace"`
	Path      *string     `json:"path,omitempty"`
}

// Gate defines model for Gate.
type Gate struct {
	// Approvers Who may decide: Principals listed explicitly, or members of the listed teams (checked through the platform Authorizer).
	Approvers     GateApprovers `json:"approvers"`
	CreatedAt     time.Time     `json:"createdAt"`
	DecidedAt     *time.Time    `json:"decidedAt,omitempty"`
	DecidedBy     *string       `json:"decidedBy,omitempty"`
	Id            string        `json:"id"`
	Note          *string       `json:"note,omitempty"`
	Status        GateStatus    `json:"status"`
	Step          string        `json:"step"`
	WorkflowRunId string        `json:"workflowRunId"`
}

// GateStatus defines model for Gate.Status.
type GateStatus string

// GateApprovers Who may decide: Principals listed explicitly, or members of the listed teams (checked through the platform Authorizer).
type GateApprovers struct {
	Principals *[]string `json:"principals,omitempty"`
	Teams      *[]string `json:"teams,omitempty"`
}

// GateDecision defines model for GateDecision.
type GateDecision struct {
	Approve bool    `json:"approve"`
	Note    *string `json:"note,omitempty"`
}

// GateSpec defines model for GateSpec.
type GateSpec struct {
	// Approvers Who may decide: Principals listed explicitly, or members of the listed teams (checked through the platform Authorizer).
	Approvers GateApprovers `json:"approvers"`

	// TimeoutSeconds Expire (treat as denial) after this long pending; 0 waits forever.
	TimeoutSeconds *int64 `json:"timeoutSeconds,omitempty"`
}

// Plan defines model for Plan.
type Plan struct {
	Entries []PlanEntry `json:"entries"`
}

// PlanEntry defines model for PlanEntry.
type PlanEntry struct {
	Action PlanEntryAction `json:"action"`
	Error  *string         `json:"error,omitempty"`
	Kind   *PlanEntryKind  `json:"kind,omitempty"`

	// MemberCount Live Entity count the relevant selector matches now.
	MemberCount int64  `json:"memberCount"`
	Name        string `json:"name"`

	// NewSelector Structured selector data — deliberately not an expression language (charter non-goal; ADR-0003 review).
	NewSelector *ViewSelector `json:"newSelector,omitempty"`

	// OldSelector Structured selector data — deliberately not an expression language (charter non-goal; ADR-0003 review).
	OldSelector *ViewSelector `json:"oldSelector,omitempty"`
}

// PlanEntryAction defines model for PlanEntry.Action.
type PlanEntryAction string

// PlanEntryKind defines model for PlanEntry.Kind.
type PlanEntryKind string

// Provenance Per-attribute stamp — which Run/Syncer wrote the value, when, from which Source (charter §2.1). Always exactly one answer.
type Provenance struct {
	At         time.Time            `json:"at"`
	SourceId   *string              `json:"sourceId,omitempty"`
	WriterKind ProvenanceWriterKind `json:"writerKind"`
	WriterRef  string               `json:"writerRef"`
}

// ProvenanceWriterKind defines model for Provenance.WriterKind.
type ProvenanceWriterKind string

// Run defines model for Run.
type Run struct {
	FinishedAt *time.Time `json:"finishedAt,omitempty"`
	Id         string     `json:"id"`
	StartedAt  time.Time  `json:"startedAt"`
	Status     RunStatus  `json:"status"`

	// StepName The Step within that Workflow.
	StepName *string `json:"stepName,omitempty"`

	// TriggeredBy Name of the Trigger that fired this Run; absent for manual/API launches (charter §1.8 descent, Trigger → Run).
	TriggeredBy *string `json:"triggeredBy,omitempty"`
	ViewRef     *string `json:"viewRef,omitempty"`
	ViewVersion *int64  `json:"viewVersion,omitempty"`
	WorkflowId  string  `json:"workflowId"`

	// WorkflowRunId The WorkflowRun this Run executed under, when it ran as a Workflow Step (charter §1.8 descent, Workflow → Run).
	WorkflowRunId *string `json:"workflowRunId,omitempty"`
}

// RunStatus defines model for Run.Status.
type RunStatus string

// StartRun One Step against a View (charter §2.3: Step = Actuator + content + params). Params are interpreted by the named Actuator; their pinned JSON-Schema Contract documents land with the Phase-2 Contract machinery.
type StartRun struct {
	Actuator *StartRunActuator `json:"actuator,omitempty"`

	// CredentialRefs CredentialRef names to project into the execution pods. The launching Principal needs the `use` grant on each (checked at dispatch; use never implies read — charter §2.5).
	CredentialRefs *[]string `json:"credentialRefs,omitempty"`

	// Params Actuator-interpreted Step params (e.g. script source).
	Params *map[string]interface{} `json:"params,omitempty"`

	// Slices Partition the target set across this many parallel execution Jobs (clamped to the target count).
	Slices   *int64 `json:"slices,omitempty"`
	ViewName string `json:"viewName"`
}

// StartRunActuator defines model for StartRun.Actuator.
type StartRunActuator string

// Step One DAG node — an actuation (Actuator + params against a View, charter §2.3) or a Gate; exactly one shape is set.
type Step struct {
	Actuator       *string   `json:"actuator,omitempty"`
	CredentialRefs *[]string `json:"credentialRefs,omitempty"`
	Gate           *GateSpec `json:"gate,omitempty"`
	Name           string    `json:"name"`

	// Needs Step names that must reach a terminal state first.
	Needs    *[]string               `json:"needs,omitempty"`
	Params   *map[string]interface{} `json:"params,omitempty"`
	Slices   *int64                  `json:"slices,omitempty"`
	ViewName *string                 `json:"viewName,omitempty"`

	// When Edge condition on the needs' outcomes; success is the default (all needs succeeded).
	When *StepWhen `json:"when,omitempty"`
}

// StepWhen Edge condition on the needs' outcomes; success is the default (all needs succeeded).
type StepWhen string

// Trigger Anything that starts a Run (charter §2). v1 kind is `schedule` — a Temporal Schedule fires Runs with these launch parameters, executing as the declared service Principal (ADR-0010).
type Trigger struct {
	Actuator       *string                 `json:"actuator,omitempty"`
	CredentialRefs *[]string               `json:"credentialRefs,omitempty"`
	Cron           string                  `json:"cron"`
	Kind           TriggerKind             `json:"kind"`
	Name           string                  `json:"name"`
	Params         *map[string]interface{} `json:"params,omitempty"`
	Paused         *bool                   `json:"paused,omitempty"`

	// Principal Service identity the fired Runs execute as; its `use` grants are checked at dispatch exactly like an API launch (§2.5).
	Principal *string `json:"principal,omitempty"`
	Slices    *int64  `json:"slices,omitempty"`
	ViewName  string  `json:"viewName"`
}

// TriggerKind defines model for Trigger.Kind.
type TriggerKind string

// TriggerDetail defines model for TriggerDetail.
type TriggerDetail struct {
	// Schedule Observed Temporal Schedule state; absent when the schedule has not been reconciled yet (e.g. within one interval of declaring).
	Schedule *TriggerScheduleState `json:"schedule,omitempty"`

	// Trigger Anything that starts a Run (charter §2). v1 kind is `schedule` — a Temporal Schedule fires Runs with these launch parameters, executing as the declared service Principal (ADR-0010).
	Trigger Trigger `json:"trigger"`
}

// TriggerScheduleState Observed Temporal Schedule state; absent when the schedule has not been reconciled yet (e.g. within one interval of declaring).
type TriggerScheduleState struct {
	NextFireTimes *[]time.Time `json:"nextFireTimes,omitempty"`
	Paused        *bool        `json:"paused,omitempty"`

	// RecentRuns Workflow executions recently started by this Trigger.
	RecentRuns *[]struct {
		At         time.Time `json:"at"`
		WorkflowId string    `json:"workflowId"`
	} `json:"recentRuns,omitempty"`
}

// View defines model for View.
type View struct {
	// DeclaredBy Which declaration path owns this View — cac (Git-declared desired state, charter §1.2) or api. cac Views are Git-only.
	DeclaredBy *ViewDeclaredBy `json:"declaredBy,omitempty"`
	Name       string          `json:"name"`

	// Selector Structured selector data — deliberately not an expression language (charter non-goal; ADR-0003 review).
	Selector ViewSelector `json:"selector"`
	Version  int64        `json:"version"`
}

// ViewDeclaredBy Which declaration path owns this View — cac (Git-declared desired state, charter §1.2) or api. cac Views are Git-only.
type ViewDeclaredBy string

// ViewDeclaration defines model for ViewDeclaration.
type ViewDeclaration struct {
	Name string `json:"name"`

	// Selector Structured selector data — deliberately not an expression language (charter non-goal; ADR-0003 review).
	Selector ViewSelector `json:"selector"`
}

// ViewResolution defines model for ViewResolution.
type ViewResolution struct {
	Entities []Entity `json:"entities"`
	View     View     `json:"view"`
}

// ViewSelector Structured selector data — deliberately not an expression language (charter non-goal; ADR-0003 review).
type ViewSelector struct {
	Facets *[]FacetPredicate  `json:"facets,omitempty"`
	Kinds  *[]string          `json:"kinds,omitempty"`
	Labels *map[string]string `json:"labels,omitempty"`
}

// Workflow A Temporal-backed DAG of Steps with Gates (charter §2, ADR-0011). CaC-only in v1.
type Workflow struct {
	Name  string `json:"name"`
	Steps []Step `json:"steps"`
}

// WorkflowRun defines model for WorkflowRun.
type WorkflowRun struct {
	FinishedAt   *time.Time        `json:"finishedAt,omitempty"`
	Id           string            `json:"id"`
	Principal    *string           `json:"principal,omitempty"`
	StartedAt    time.Time         `json:"startedAt"`
	Status       WorkflowRunStatus `json:"status"`
	TemporalId   *string           `json:"temporalId,omitempty"`
	WorkflowName string            `json:"workflowName"`
}

// WorkflowRunStatus defines model for WorkflowRun.Status.
type WorkflowRunStatus string

// WorkflowRunDetail defines model for WorkflowRunDetail.
type WorkflowRunDetail struct {
	Steps []struct {
		// GateId The Step's Gate (Gate Steps).
		GateId *string `json:"gateId,omitempty"`
		Name   string  `json:"name"`

		// RunId The Step's Run (actuation Steps).
		RunId *string `json:"runId,omitempty"`

		// Status Terminal outcome from the WorkflowRun summary (succeeded, failed, skipped); absent while the execution is live — descend into the linked Run or Gate for live state.
		Status *string `json:"status,omitempty"`
	} `json:"steps"`
	WorkflowRun WorkflowRun `json:"workflowRun"`
}

// RunID defines model for RunID.
type RunID = string

// ViewName defines model for ViewName.
type ViewName = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListGatesParams defines parameters for ListGates.
type ListGatesParams struct {
	Status *ListGatesParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListGatesParamsStatus defines parameters for ListGates.
type ListGatesParamsStatus string

// ListRunsParams defines parameters for ListRuns.
type ListRunsParams struct {
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`
}

// ResolveViewParams defines parameters for ResolveView.
type ResolveViewParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListWorkflowRunsParams defines parameters for ListWorkflowRuns.
type ListWorkflowRunsParams struct {
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`
}

// DeclareCredentialRefJSONRequestBody defines body for DeclareCredentialRef for application/json ContentType.
type DeclareCredentialRefJSONRequestBody = CredentialRef

// DesiredStateApplyJSONRequestBody defines body for DesiredStateApply for application/json ContentType.
type DesiredStateApplyJSONRequestBody = DesiredState

// DesiredStatePlanJSONRequestBody defines body for DesiredStatePlan for application/json ContentType.
type DesiredStatePlanJSONRequestBody = DesiredState

// DecideGateJSONRequestBody defines body for DecideGate for application/json ContentType.
type DecideGateJSONRequestBody = GateDecision

// StartRunJSONRequestBody defines body for StartRun for application/json ContentType.
type StartRunJSONRequestBody = StartRun

// DeclareViewJSONRequestBody defines body for DeclareView for application/json ContentType.
type DeclareViewJSONRequestBody = ViewSelector

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List pinned Contracts
	// (GET /contracts)
	ListContracts(w http.ResponseWriter, r *http.Request)
	// List CredentialRef pointers the Principal may read
	// (GET /credential-refs)
	ListCredentialRefs(w http.ResponseWriter, r *http.Request)
	// Get one CredentialRef pointer (reader grant required)
	// (GET /credential-refs/{name})
	GetCredentialRef(w http.ResponseWriter, r *http.Request, name string)
	// Declare a CredentialRef pointer (admin grant required)
	// (PUT /credential-refs/{name})
	DeclareCredentialRef(w http.ResponseWriter, r *http.Request, name string)
	// Reconcile the graph's Views to a declared desired state
	// (POST /desired-state/apply)
	DesiredStateApply(w http.ResponseWriter, r *http.Request)
	// Diff a declared desired state against the graph's Views
	// (POST /desired-state/plan)
	DesiredStatePlan(w http.ResponseWriter, r *http.Request)
	// Get one Entity with its Facets and per-attribute Provenance
	// (GET /entities/{id})
	GetEntity(w http.ResponseWriter, r *http.Request, id string)
	// List Gates (the approval inbox)
	// (GET /gates)
	ListGates(w http.ResponseWriter, r *http.Request, params ListGatesParams)
	// Approve or deny a pending Gate
	// (POST /gates/{id}/decision)
	DecideGate(w http.ResponseWriter, r *http.Request, id string)
	// List recent Run summaries
	// (GET /runs)
	ListRuns(w http.ResponseWriter, r *http.Request, params ListRunsParams)
	// Start a Run of the Phase-0 Workflow against a View
	// (POST /runs)
	StartRun(w http.ResponseWriter, r *http.Request)
	// Get a Run summary
	// (GET /runs/{id})
	GetRun(w http.ResponseWriter, r *http.Request, id RunID)
	// Live SSE tail of the Run's full task-event stream
	// (GET /runs/{id}/events)
	TailRunEvents(w http.ResponseWriter, r *http.Request, id RunID)
	// List declared Triggers
	// (GET /triggers)
	ListTriggers(w http.ResponseWriter, r *http.Request)
	// Get one Trigger with its live schedule state
	// (GET /triggers/{name})
	GetTrigger(w http.ResponseWriter, r *http.Request, name string)
	// List Views
	// (GET /views)
	ListViews(w http.ResponseWriter, r *http.Request)
	// Get a View (versioned, CaC-declared graph query)
	// (GET /views/{name})
	GetView(w http.ResponseWriter, r *http.Request, name ViewName)
	// Declare a View's selector (bumps the version on change)
	// (PUT /views/{name})
	DeclareView(w http.ResponseWriter, r *http.Request, name ViewName)
	// Resolve the View's live Entity set
	// (GET /views/{name}/entities)
	ResolveView(w http.ResponseWriter, r *http.Request, name ViewName, params ResolveViewParams)
	// List recent WorkflowRuns
	// (GET /workflow-runs)
	ListWorkflowRuns(w http.ResponseWriter, r *http.Request, params ListWorkflowRunsParams)
	// Get one WorkflowRun with per-Step outcomes
	// (GET /workflow-runs/{id})
	GetWorkflowRun(w http.ResponseWriter, r *http.Request, id string)
	// List declared Workflows
	// (GET /workflows)
	ListWorkflows(w http.ResponseWriter, r *http.Request)
	// Get one Workflow declaration
	// (GET /workflows/{name})
	GetWorkflow(w http.ResponseWriter, r *http.Request, name string)
	// Start one execution of a Workflow
	// (POST /workflows/{name}/runs)
	StartWorkflowRun(w http.ResponseWriter, r *http.Request, name string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListContracts operation middleware
func (siw *ServerInterfaceWrapper) ListContracts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListContracts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCredentialRefs operation middleware
func (siw *ServerInterfaceWrapper) ListCredentialRefs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCredentialRefs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCredentialRef operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialRef(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCredentialRef(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeclareCredentialRef operation middleware
func (siw *ServerInterfaceWrapper) DeclareCredentialRef(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeclareCredentialRef(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DesiredStateApply operation middleware
func (siw *ServerInterfaceWrapper) DesiredStateApply(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DesiredStateApply(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DesiredStatePlan operation middleware
func (siw *ServerInterfaceWrapper) DesiredStatePlan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DesiredStatePlan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEntity operation middleware
func (siw *ServerInterfaceWrapper) GetEntity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEntity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGates operation middleware
func (siw *ServerInterfaceWrapper) ListGates(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGatesParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGates(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DecideGate operation middleware
func (siw *ServerInterfaceWrapper) DecideGate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DecideGate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRuns operation middleware
func (siw *ServerInterfaceWrapper) ListRuns(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRunsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRuns(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartRun operation middleware
func (siw *ServerInterfaceWrapper) StartRun(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartRun(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRun operation middleware
func (siw *ServerInterfaceWrapper) GetRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id RunID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRun(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TailRunEvents operation middleware
func (siw *ServerInterfaceWrapper) TailRunEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id RunID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TailRunEvents(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTriggers operation middleware
func (siw *ServerInterfaceWrapper) ListTriggers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTriggers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrigger operation middleware
func (siw *ServerInterfaceWrapper) GetTrigger(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrigger(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListViews operation middleware
func (siw *ServerInterfaceWrapper) ListViews(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListViews(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetView operation middleware
func (siw *ServerInterfaceWrapper) GetView(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name ViewName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetView(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeclareView operation middleware
func (siw *ServerInterfaceWrapper) DeclareView(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name ViewName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeclareView(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResolveView operation middleware
func (siw *ServerInterfaceWrapper) ResolveView(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name ViewName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ResolveViewParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResolveView(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkflowRuns operation middleware
func (siw *ServerInterfaceWrapper) ListWorkflowRuns(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWorkflowRunsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkflowRuns(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkflowRun operation middleware
func (siw *ServerInterfaceWrapper) GetWorkflowRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkflowRun(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkflows operation middleware
func (siw *ServerInterfaceWrapper) ListWorkflows(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkflows(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkflow operation middleware
func (siw *ServerInterfaceWrapper) GetWorkflow(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkflow(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartWorkflowRun operation middleware
func (siw *ServerInterfaceWrapper) StartWorkflowRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartWorkflowRun(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/contracts", wrapper.ListContracts)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/credential-refs", wrapper.ListCredentialRefs)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/credential-refs/{name}", wrapper.GetCredentialRef)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/credential-refs/{name}", wrapper.DeclareCredentialRef)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/desired-state/apply", wrapper.DesiredStateApply)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/desired-state/plan", wrapper.DesiredStatePlan)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/entities/{id}", wrapper.GetEntity)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/gates", wrapper.ListGates)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/gates/{id}/decision", wrapper.DecideGate)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/runs", wrapper.ListRuns)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/runs", wrapper.StartRun)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/runs/{id}", wrapper.GetRun)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/runs/{id}/events", wrapper.TailRunEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/triggers", wrapper.ListTriggers)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/triggers/{name}", wrapper.GetTrigger)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/views", wrapper.ListViews)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/views/{name}", wrapper.GetView)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/views/{name}", wrapper.DeclareView)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/views/{name}/entities", wrapper.ResolveView)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/workflow-runs", wrapper.ListWorkflowRuns)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/workflow-runs/{id}", wrapper.GetWorkflowRun)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/workflows", wrapper.ListWorkflows)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/workflows/{name}", wrapper.GetWorkflow)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/workflows/{name}/runs", wrapper.StartWorkflowRun)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5HxbbhzJlfZWDvL/AbHgupBUt3+bgh/YklqQ3b9MkBr3gy1AUZmnqsLMisiOiKxSjUBgnmYBg9mD9+Gl",
	"eCWDcyLyVhl1IUVyDPilu8TMuJ3rdy6RX5NULwutUDmbXHxNCmHEEh0a/td1qd6/oR9SJRdJIdwiGSZK",
	"LDG5SGSWDBODv5TSYJZcOFPiMLHpApeCRrhNQW9ZZ6SaJ3d3w+RPEtcfeOzXJEObGlk4qWliegI0LZy4",
	"BcLnlcT1xWTyl/L09GVKf+df+BkMztCgShHW0i106YAXxME4Gcb2yP+7zy7v6GVbaGWRCfCDyK7xlxKt",
	"o3+lWjlU/FMURS5TQQeY/NXSKb62pv2/BmfJRfJ/Jg1xJ/6pnbw1Rhu/VJcKHxcIxi8G0sJS5DNtlpgl",
	"d8PktVazXKbPtAs9/SumvAm9VpjBdANCabdAAxmmuTC8IjCt74bJj9pMZZahep7dXRmpUlmIHHKR3lpw",
	"gW7EYZgboRxt6oN2P+pSZc+zJxK0rKJbptGC0g7wi7S8mX9TonQLbeS/4zNs6BJ+QGHQgNO3qGAtLBQG",
	"LSpHvCwdpLrMM97hFGGFRs4kZnAi1UrkMhsCfimImEPQBtZGqzlIa0s0E1FmktRvMIafjXQOFcmG6zBl",
	"KbMsx7UwCP/4j/8GAVORQWowQ+WkyEmqvjs9G4LCFcmTXqu5ERlm4DRJmdosdWlfgVAgprTnrbH1KyBU",
	"Bhkq2nqBZsSch5PvTl8Oxn9RbHECpYiQr7VyRngF2qZWIRVJ+e9v/vgBbngIZDotl7S4ViDgxmHxwoJU",
	"RensRJeO/k/EEfCjSNEx+20hUoSTdCGMQwN//9vZ+Psh/P1v5+PzAVMiE05UxxaQCzUvxRwhzYW1tONh",
	"UhhdoHHS256FsIv+du1CnH//a9A0CxEevwgWubDf6cahHcICv5BJ3DJvlV3cnhPH8zGI1JXCaUMCRo/G",
	"fFw65YzOaCfajm/RKMxjE5tSzfsTv0EjVyzbo1xkGRoojF6hEmTC9YwP4JkEJ55StGtU5TK5+HOyECob",
	"rb2c0Zpa56OMZkRyPcu0GHlrhFnyKbKlRov6+hrjdYtgXpFpkhUaK71WkjUWjjyfcr/+rnlZKodzNIl3",
	"HpWn+XPlfKoZAo2Gnq/19j5FFn1dS/x7RX8LG+iKh5frilaoVskwmckco7S4xU2fED9KzDP2pFIxK6Yi",
	"vUWVwVI4NFLk9xCht2oFK2G8F9eGfQOUKgtSWui2DbCw1GWH4C2Y0CYhbXtIJw3L7ifWNdnK7Y1daeKP",
	"gV+BrGgJhc5luiGDMzX6FslvWEwNuvrkbT0+H38/GMP/r554BS6Iq9aRUfAHzIUjAWGrtBBk/8GgyJgQ",
	"Me0OtG7z8PY3duT3QWIjypz+v9bmNtciG0k+pdtE+Vspwg+b9oSikMkwSUVKY2g3f1T5pgJBvTlkW9ak",
	"w6U95IFicnpXzyyMERv6d65TMix93vzgaTCyC1FgBiLLDFoLJw0hLhrTOuSfg6iWVjLZOxPhF/MRxTIO",
	"SSPq2owY1jxqjtCmUkwY36Cl+W6ccBi3PLMyz6FiF2T+fbA0oOs8vC3sCk3alnX7AD6RikQ45IyczwPm",
	"P2rGj35AbC4C78dPRND/TYMpYxOSBsxyfY9Jfw4j+rNt8dzvNcbIt17XelZXZlE5q5TzD7jxxjnLJJ1H",
	"5Fed4b2BvYVvpYovkYsp5t80+dbhOYDj5bb2X6+1mzBvgs/sEwhrwu3Frv6tu2HiwcXRrGW8dZCvYRP1",
	"7NGDMHzu7X+J1oo5HrYX1Yuxuf0ue3PXtizKrQYaHSLCVfMmKZzIyx3GxqPTGhzOjJjzj5MAuoRzIl2g",
	"JXfWtrRkf84G46iN9Aeolu1seycprgxmFORgRF5+KYUX6+72GaHxGuxfg2/ADGaMWpaldcBjx5UD2ENZ",
	"ClSPcgDV4cKuYgd6Fz2GKJgO5qAA0/DL+uW7Idl04TC7dB2MmQmHIyfZJcW8vcweNMTjg4j5iv5ZaRcn",
	"KLmrsoM/C1SZZHgbKEFWxUdnRE4fUMZhusMiukhl969L9T47zD42Z90xYfJ6v8MWm9qE38XmyzZTu+L5",
	"80LDUmzA0/WiiX8t5NJSoI1fKLCXLt9wHL3E5RSNraKe8JJDsbTk9zG9pX8ujC7niy6ivKxSB2YQA5JF",
	"vXLHiO5yBo3Pp6XvM+RuB5XeYCptPETx9GvNPdU6R6H2CNcWV6spdrHopsD0MbWR9EeX7gZTrbII39+y",
	"JMOJI+EBYTkDIfIBiJnjWEdayLWaQ1CIV3AKayGdhZk2FDl4Ft43lmwOFCPEVS5U1BObCrUc41pplrfK",
	"mc0x7pVn3rUXP0ufK3V0UVkNr4LJMCmLzP8QmS4o7FFaF2xBcnTxkBYr/90PdmU3riKU5/U9oOARUaFG",
	"vS2zEV3Ia+5rilj78vCTXCF4NAMpvRLSkTmuhHJgMcfUkfoLx45W6fX4GP7viWkUrm/CtMeg6/pdCofy",
	"7GFD47FSYGiXRFGh6ECbrQAdzUg4Z+S0dEiB0LLgdNl6IdMFXJdqcrNRKXIm0nkwwLBgCOsFqiHMjF6G",
	"l290abo5uHOCMXCZr8XG+lRZvgGtEISy60oZt6T0Hl7V8oLv495zbaRD84ctYbR8GJ8NioqbHxZyGfuN",
	"Y2uF9rghnSHGhusyYiZmUkm7uB+a2IEXrCO632umfUjClEr5X7ZMU8SMscRMyJx/pCRP+R5UES82ES6+",
	"cVg0iS/hoIoYoxmvYCcq9NSd7gMnvLxTD1Gxn3LGgT07hOtSvaqy2TM2BqoU+eTy6j3kolRsGDqx/2+A",
	"FkHlhvWc//jP/6J5AgTo7ZFsXFxm/LM/3SOP2djDXZK9jcz6FP65eaWmAeAXTEuCPZwY9AoM0oERilyp",
	"qEd5Bu0iSf3WXprsg4cBGwZQ2IhtTGlu6GnQnO45/6iCJIm5kMo6EMCVzI79eXnh3/kdXIYEO/wKQv0H",
	"fgVcb7WDMVzxDxAGgROWhUHnS2+uri9VM7yiv0nTLlyMQjK7qnPUQZ+FXCif5fWFmoWwODpvXlyKdCEV",
	"mk3UGIYV/eFnnJO8SISycppjK1Xf/MUTKBkmukDl9KyMqmc/kdUlbSdj5SNTcBoKo31lUjkdqh8kUT6n",
	"m9kxkOh5lZJq3ipKKcTMVwo/lxY/+zIhaAUo0kWDv4WDTNqCfPUrKC2GZK9cFrlE6xO65Ju2ksNMuOOR",
	"t+d5pBIViD1qCwALjx8BJ1yo8UPA+554PtTmMkXbYdrZdpXwShjHaSQmixNmjoRXHIjUaGu91i6F2vDq",
	"eY55i9q/11MyWblYFr5y15qDYdBgB85dSiWXJDNnMbuzarUI7Ffn+s24yvqQsq+uby7fgdJZKE2qUPSi",
	"E5201DOQu6vWww7XXw58/Y8CiFcdZMHJbJCWaHlIpY7Qi+PFah4SE4fiHQ6Z9gNMjIU+LIlBFcnBcQrG",
	"sAIJcGiWUok8ZLJn0liu7zxEK/aI8xG+a48MDRPyOJGgLpsj2WSfVoWgEkyGF6BLl+ol2lfAKMRa4i09",
	"D6oFJyKvDEyNU4L416DPjwzopTQMnhmURqxjDGvHpLzKwfftiNo4tn/MJvZu5FzJA7dd02AMqzOgYIlO",
	"9JlEJCtz/BzK9h9xWWgjci6T0gNGNOzIbe1ObGVuoWkcGlZ2Qs3Jq3tShXqHRbOSabtd4OTyzfXo9PTs",
	"dPCsypIaD4YOBo8VWaJubKcK7RHmQpQWs3hOpM7lRLQvUK7K1DNdPcZkjgRsBcK+Auls2895VBHxcbXd",
	"yuUthUTQIFJfj/9+F9x8LI2Mx5WhKME8Gu439UEJ3qATMu8HNzX3jqtnVaLu63cN9D+6HLZ1nmr4np13",
	"l+w7rSmpDGYRdWRLW8cVjKWrfgp+7qvQDqaICgymWqUUOcEGXUASIQIir8WQYyVyCmW8tko1j6qkwi/u",
	"R2nwo1xuJZeOi/j6dn+3PhgkxE/yHcnAVlFAjUoIoNH7+QYCpPfwWdoqiup4pIeH/XvDo+0YvR1y7IjL",
	"D+dZCYD099yt+m8nqGW66LXrgV6rAO04VGEwK1I4eSfdKF6VbuOes/G5xz2FHPM4msSbF5pAq3zTdXz3",
	"60DYaU7tA/Ndj9m9U+/h0w7+tMvY0dLfIx4tvtmDW7xGq/MyvkN2K/fJFzc13FgLwDHniaJ6lp6wlV3n",
	"aCcxt0GqKVNXeqwRcq+ZcMJ34GEup2iEw3zDplEowC+FQUs8blryapSktBrNtchfgUcppy/BIG0yahkf",
	"UspuKqMROpIfvCeueZQugR7N64aKSPdk5ZhG3C2TcYilZxy3BpxIQUcnwXU+DPQ8OxuM4bV4zZYDpILV",
	"WdTl7FQeWuRognNYeKi2UakSz/xpDy2eOpnawYL/zKlWFwTgQLLwOATYSdN9qHhxVKKuxZidcLAnL93n",
	"FELvymiGJuB33KjF/2URH+xtkoz1yR5YgMO0Ji+xZ5GGoVuTVbF4CF19icRtZWVtuVwKs4GTmuND8Awf",
	"gr2VRYHZoIUuZY5bGTdpIZcrDJbVpkiBZJWYy6W69aEJ4QUm10wbP4BhxTE5252h764WsaCTx/SG0au7",
	"sBo9220C7rhXcqYjeQQ+2UiUTi8D5qqL+FfvL3ySbFNgBujTJHMjigWchLSm1GobbA09whpyW6knZrpA",
	"6zzMGIds7inY0pD38USl2ExZbCxnclmIdIGj8/FpMkxKkycXycK5wl5MJuv1eiz48Vib+SSMtZOf3r9+",
	"++HmLY/hurijKIr8q3COjtMCRxfJ6fjMv6cLVAT6LpKX49Pxy8Q337CQTtKQcvaqhpFq6tsVmk2V1q4z",
	"1HR238lU9YpvNdkHZ/L9wJM41tw95KA4NM8XUg0hbH4Y7hFUjepgSjX3iWQ/xY/aLCf+50cxzREMKnpd",
	"zUMKtkphnL6En/7f5KffBGxAdoVnJH1PfpLWva7Pv3XL6Pz09F63Qo5r+qxuPPQ9Xu/GyFWX4nYI2mTc",
	"Fz3d+JZuIlKgmG8LC+YjHG2bZ5bfmXRL7m2+R6jTzeY8C4n298VG6BSayZfoBKNKxi1kAOvG8V7vN837",
	"3enZrr3Up5x0LgnxoJeHBzV3ryJM6VZRCr95u31fR2x4t1GOTb4S9+92Kuw1utIoW80d67Lv0IoVy3B6",
	"XGlAlfFAn6g0Ya7tVnwir9Jgy3QBqc7QB7J8t8pu9elXpuD0t1ElfIddKftWIbuHbMWvjQWyPZuI0Ijv",
	"Do+o7851ZeodOs4VRcUKTkiI0ITSWuVWB3U2NFwq/fPXR7mo+WmYFGXEkvggHPts5nuVP+hs85Qc7u7/",
	"7n9bvOqETkfOTg8LQOva63OK5m8Pj6gvwnZFM7AdxC7hFNlSqr5skskL2a4RQ7IJscT3rmkbuy1Y+FJw",
	"6NBUPoPGbWx24rvY7ISb2GxDfp8lO/GXaUXz4IfN71KRDti5FqZUaFtJNaW5kbC+c4vZGEQhR1uz0qnD",
	"lSSaIRvDFZoRJ/dCrcm/Y7DQnBL11S1p/PZDK9+r0LZmHVgn8xyEP2fMirbvuFwytZ5Gvzp3aZ5Zvbij",
	"cucdbZGTlDMBH6RSHdG9rjLzzAKOCF7YwFynQey4LBST3aLqA42K7huzIXALelZXA2SofXeCjgvIjJy5",
	"uswpZ7PBGN56QQly5HvyQ8jCVYcq2ZYuhJqjR9U+EFxhaH4ODZKkMdNcWAdGZLK0MMWZJt2typahlHVQ",
	"+JhJ/2qy12Hc40jgGzmb7ZSzuguiJ51eAqtc7eSrzO52Avx36N5Wd3KejHBbV5N2kDA062b1a48DisK0",
	"nPCkUJMDVn9Jveh0uHYv7xyGRvf8zsYnYsqc3NDeaItzskl8/V9KNJtmA036rV70W2993H16jvDuXTSt",
	"3pcKpsUQFK7J/4XWlUg4FfLYbPr4uCIHqab6SwASTHXWg0nWvhPx6Cwe7rDw134Ky51NpVuQbqaCnH4T",
	"7nGoRUeg07ywUN0sqMK1GsVZNtS9yyy+7SkYdD3jpaopHIrl0ZdZmlhtEgoBAbIy4cj7ZEjOwzQNZmsh",
	"uaukLv1y06iVcyXyV50EJxtKk1mQDk7OT88HcV+Sygzf+YsHT+FFOrdjjvIi57FvKASKiDTFgphBNsUf",
	"uiFN08D8T47x72Vpvy0oCBd7SGIzVBsQ1aUceFcDKBN6C3YaSm4+OMpO5nIpXdL97kTVfHl6GuuFFF98",
	"L+T39HhfZ+Tz2EtOiR82l9fcZMFdR0cYTVO/HSoOEvmiVWXBuhSvm62fRiHr6Y9SxrNHW7desg9Hwi1E",
	"CMR/kOo+HL0wQUJvYLjEUJUUGiPbaYNt1OYg4qv4+ERwbw9RO/UtXHEbvHWG3JNFUmWH+WbwGNBPtNeK",
	"ALrYxM0rE/+BNQ/aappO/I73JF2LXGxsU9Zj7QMexc5hpvNcr0N57uTD5cebUJwfjOED5wqcKZVHBuTk",
	"XfVdikAjdusbPpm0vsWXKx+tQsfZ5KdzjgqzUOQX8NmPHqHKPofNaJX6sPa6VC9qFqS5tvHo7qOQ+XWp",
	"3vrzH5Qdh1+cJ9bIT90VnsjH3fo9lWhGXOH0G/bTvPLXAj5nwomLz5BLxRlr5jXvbfytosPXBm9u3oIT",
	"Mq80zxOJGeGEvR21t/RtotX+vkdUpEJ/nE8V1Q0ZTW/uRRMdhg/evJMOOtkHzgzwnR7ONq0krttgslt0",
	"mEp2xIT5pK2ql0HYMl6c8VxdKbi8eg98wa31PZ2+r65O8SzFo52fQOnLmS9r1hSsmxEj7nL7pRBlVww8",
	"VI9psr5VgqD0pO+1j76woKveUs8/sgS+GZPc+hd/gw2cXKJt0jlViRxkZkMmiW+11Y3IF52bcOGGFhdV",
	"KzEP97ggfBGse8trV93mY31X98n8SbeVeIdnqQ5G9OCKcqcbd/xY2YRqmTqd4BsnOos9VWWF5K3+iM9O",
	"XOxTQM+haB51HKtl/qrOVvk6qmqtJBYft69bPSn8k+9PfDIRDAArKnkVGb4dsfhLiqGaT9pOBr82PL4n",
	"hWObwf29Tv2R11aFbiuelQZTByeikCMS1UHbYI1D4rv+7mhwNaNdX8zqlVJarcjbF8GDEZO2KTwbnJXW",
	"e6elV7bvTn/LlhAz6Vp3V0TVYF5oIDSMItuRUqDt1HLy+CHMVh/ws2am94lnpyzV2K20NIaMfdUq9NAQ",
	"5zFKg7QzQqFVqeJkWi4L7x7D9kCrUMAY9A3DpN0hHbUQ3F69qrj/oJTBk2YBDvG21R6+g8t563MXfFc0",
	"wAJmekVE6SAVoe3wWy1WIGm9yAu7vYdvslHE4wrSjA7mglq9g/8qOaFOu+TRuaHmSs7xGaIOce96jNnO",
	"Nuz+5MADQOeFD/i6Xbfcw2rZinEknMEJR2v0h5BTWEkBvbh9MPSz1T3CPOJd3fPaQxU/d9pOn0zD+/3R",
	"O5S8afGtUC43IT8auG13IbOjKNCMmFDVXdunq4x1PiYZFaVqd1uxMF9OqCPis6Mj4j0h7q4wtt5B8pwa",
	"/oBAtlV02BPJNsfpaPUxeLve2zOoxS5t2KqsPJ74t5HlU8Zy2wSvax5P1JYXLU3u+jCHkRmyOTWbLfP7",
	"wra//O6vM3NpcfvbzMP6GrOwIGcEPxYiq6+Asi0mU5Nx4BFXO86D77XDZ09hhw8VBVqvjh8n1U8C2Nh3",
	"PWt9dMdvhlNCQSL8TYGJKORkdUZo6X8CAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
