//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CredentialInjectionAs.
const (
	Env  CredentialInjectionAs = "env"
	File CredentialInjectionAs = "file"
)

// Valid indicates whether the value is a known member of the CredentialInjectionAs enum.
func (e CredentialInjectionAs) Valid() bool {
	switch e {
	case Env:
		return true
	case File:
		return true
	default:
		return false
	}
}

// Defines values for CredentialRefBackend.
const (
	K8sSecret        CredentialRefBackend = "k8s-secret"
	Vault            CredentialRefBackend = "vault"
	WorkloadIdentity CredentialRefBackend = "workload-identity"
)

// Valid indicates whether the value is a known member of the CredentialRefBackend enum.
func (e CredentialRefBackend) Valid() bool {
	switch e {
	case K8sSecret:
		return true
	case Vault:
		return true
	case WorkloadIdentity:
		return true
	default:
		return false
	}
}

// Defines values for CredentialRefDeclaredBy.
const (
	CredentialRefDeclaredByApi CredentialRefDeclaredBy = "api"
	CredentialRefDeclaredByCac CredentialRefDeclaredBy = "cac"
)

// Valid indicates whether the value is a known member of the CredentialRefDeclaredBy enum.
func (e CredentialRefDeclaredBy) Valid() bool {
	switch e {
	case CredentialRefDeclaredByApi:
		return true
	case CredentialRefDeclaredByCac:
		return true
	default:
		return false
	}
}

// Defines values for GateStatus.
const (
	GateStatusApproved GateStatus = "approved"
	GateStatusDenied   GateStatus = "denied"
	GateStatusExpired  GateStatus = "expired"
	GateStatusPending  GateStatus = "pending"
)

// Valid indicates whether the value is a known member of the GateStatus enum.
func (e GateStatus) Valid() bool {
	switch e {
	case GateStatusApproved:
		return true
	case GateStatusDenied:
		return true
	case GateStatusExpired:
		return true
	case GateStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for PlanEntryAction.
const (
	Adopt  PlanEntryAction = "adopt"
	Create PlanEntryAction = "create"
	Delete PlanEntryAction = "delete"
	Noop   PlanEntryAction = "noop"
	Update PlanEntryAction = "update"
)

// Valid indicates whether the value is a known member of the PlanEntryAction enum.
func (e PlanEntryAction) Valid() bool {
	switch e {
	case Adopt:
		return true
	case Create:
		return true
	case Delete:
		return true
	case Noop:
		return true
	case Update:
		return true
	default:
		return false
	}
}

// Defines values for PlanEntryKind.
const (
	PlanEntryKindCredentialRef PlanEntryKind = "credential-ref"
	PlanEntryKindTrigger       PlanEntryKind = "trigger"
	PlanEntryKindView          PlanEntryKind = "view"
	PlanEntryKindWorkflow      PlanEntryKind = "workflow"
)

// Valid indicates whether the value is a known member of the PlanEntryKind enum.
func (e PlanEntryKind) Valid() bool {
	switch e {
	case PlanEntryKindCredentialRef:
		return true
	case PlanEntryKindTrigger:
		return true
	case PlanEntryKindView:
		return true
	case PlanEntryKindWorkflow:
		return true
	default:
		return false
	}
}

// Defines values for ProvenanceWriterKind.
const (
	ProvenanceWriterKindRun    ProvenanceWriterKind = "run"
	ProvenanceWriterKindSyncer ProvenanceWriterKind = "syncer"
)

// Valid indicates whether the value is a known member of the ProvenanceWriterKind enum.
func (e ProvenanceWriterKind) Valid() bool {
	switch e {
	case ProvenanceWriterKindRun:
		return true
	case ProvenanceWriterKindSyncer:
		return true
	default:
		return false
	}
}

// Defines values for RunStatus.
const (
	RunStatusCanceled  RunStatus = "canceled"
	RunStatusFailed    RunStatus = "failed"
	RunStatusPending   RunStatus = "pending"
	RunStatusRunning   RunStatus = "running"
	RunStatusSucceeded RunStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the RunStatus enum.
func (e RunStatus) Valid() bool {
	switch e {
	case RunStatusCanceled:
		return true
	case RunStatusFailed:
		return true
	case RunStatusPending:
		return true
	case RunStatusRunning:
		return true
	case RunStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for StartRunActuator.
const (
	Ansible StartRunActuator = "ansible"
	Script  StartRunActuator = "script"
)

// Valid indicates whether the value is a known member of the StartRunActuator enum.
func (e StartRunActuator) Valid() bool {
	switch e {
	case Ansible:
		return true
	case Script:
		return true
	default:
		return false
	}
}

// Defines values for StepWhen.
const (
	Always  StepWhen = "always"
	Failure StepWhen = "failure"
	Success StepWhen = "success"
)

// Valid indicates whether the value is a known member of the StepWhen enum.
func (e StepWhen) Valid() bool {
	switch e {
	case Always:
		return true
	case Failure:
		return true
	case Success:
		return true
	default:
		return false
	}
}

// Defines values for TriggerKind.
const (
	Schedule TriggerKind = "schedule"
)

// Valid indicates whether the value is a known member of the TriggerKind enum.
func (e TriggerKind) Valid() bool {
	switch e {
	case Schedule:
		return true
	default:
		return false
	}
}

// Defines values for ViewDeclaredBy.
const (
	ViewDeclaredByApi ViewDeclaredBy = "api"
	ViewDeclaredByCac ViewDeclaredBy = "cac"
)

// Valid indicates whether the value is a known member of the ViewDeclaredBy enum.
func (e ViewDeclaredBy) Valid() bool {
	switch e {
	case ViewDeclaredByApi:
		return true
	case ViewDeclaredByCac:
		return true
	default:
		return false
	}
}

// Defines values for WorkflowRunStatus.
const (
	WorkflowRunStatusCanceled  WorkflowRunStatus = "canceled"
	WorkflowRunStatusFailed    WorkflowRunStatus = "failed"
	WorkflowRunStatusPending   WorkflowRunStatus = "pending"
	WorkflowRunStatusRunning   WorkflowRunStatus = "running"
	WorkflowRunStatusSucceeded WorkflowRunStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the WorkflowRunStatus enum.
func (e WorkflowRunStatus) Valid() bool {
	switch e {
	case WorkflowRunStatusCanceled:
		return true
	case WorkflowRunStatusFailed:
		return true
	case WorkflowRunStatusPending:
		return true
	case WorkflowRunStatusRunning:
		return true
	case WorkflowRunStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for ListGatesParamsStatus.
const (
	ListGatesParamsStatusApproved ListGatesParamsStatus = "approved"
	ListGatesParamsStatusDenied   ListGatesParamsStatus = "denied"
	ListGatesParamsStatusExpired  ListGatesParamsStatus = "expired"
	ListGatesParamsStatusPending  ListGatesParamsStatus = "pending"
)

// Valid indicates whether the value is a known member of the ListGatesParamsStatus enum.
func (e ListGatesParamsStatus) Valid() bool {
	switch e {
	case ListGatesParamsStatusApproved:
		return true
	case ListGatesParamsStatusDenied:
		return true
	case ListGatesParamsStatusExpired:
		return true
	case ListGatesParamsStatusPending:
		return true
	default:
		return false
	}
}

// CredentialInjection defines model for CredentialInjection.
type CredentialInjection struct {
	As CredentialInjectionAs `json:"as"`

	// Key Field within the backend material.
	Key string `json:"key"`

	// Name Env var name or path under the pod credentials mount.
	Name string `json:"name"`
}

// CredentialInjectionAs defines model for CredentialInjection.As.
type CredentialInjectionAs string

// CredentialRef Pointer + injection policy to brokered secret material (charter §2.5). Material never persists in the platform and has no read path.
type CredentialRef struct {
	Backend    CredentialRefBackend     `json:"backend"`
	DeclaredBy *CredentialRefDeclaredBy `json:"declaredBy,omitempty"`
	Injection  []CredentialInjection    `json:"injection"`

	// Locator Backend-shaped address (k8s-secret: namespace, name).
	Locator   map[string]interface{} `json:"locator"`
	Name      string                 `json:"name"`
	OwnerTeam string                 `json:"ownerTeam"`
}

// CredentialRefBackend defines model for CredentialRef.Backend.
type CredentialRefBackend string

// CredentialRefDeclaredBy defines model for CredentialRef.DeclaredBy.
type CredentialRefDeclaredBy string

// DesiredState The full declared desired state (charter §1.2).
type DesiredState struct {
	CredentialRefs *[]CredentialRef  `json:"credentialRefs,omitempty"`
	Triggers       *[]Trigger        `json:"triggers,omitempty"`
	Views          []ViewDeclaration `json:"views"`
	Workflows      *[]Workflow       `json:"workflows,omitempty"`
}

// Entity defines model for Entity.
type Entity struct {
	Id           string            `json:"id"`
	IdentityKeys map[string]string `json:"identityKeys"`
	Kind         string            `json:"kind"`
	Labels       map[string]string `json:"labels"`
}

// EntityDocument defines model for EntityDocument.
type EntityDocument struct {
	Entity Entity  `json:"entity"`
	Facets []Facet `json:"facets"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Facet defines model for Facet.
type Facet struct {
	Namespace string `json:"namespace"`

	// Provenance Per-attribute stamp — which Run/Syncer wrote the value, when, from which Source (charter §2.1). Always exactly one answer.
	Provenance Provenance `json:"provenance"`

	// Value The Facet document fragment (schema attaches per namespace, §1.1).
	Value interface{} `json:"value"`
}

// FacetPredicate defines model for FacetPredicate.
type FacetPredicate struct {
	// Equals JSON value the addressed field must equal.
	Equals    interface{} `json:"equals"`
	Namespace string      `json:"namespace"`
	Path      *string     `json:"path,omitempty"`
}

// Gate defines model for Gate.
type Gate struct {
	// Approvers Who may decide: Principals listed explicitly, or members of the listed teams (checked through the platform Authorizer).
	Approvers     GateApprovers `json:"approvers"`
	CreatedAt     time.Time     `json:"createdAt"`
	DecidedAt     *time.Time    `json:"decidedAt,omitempty"`
	DecidedBy     *string       `json:"decidedBy,omitempty"`
	Id            string        `json:"id"`
	Note          *string       `json:"note,omitempty"`
	Status        GateStatus    `json:"status"`
	Step          string        `json:"step"`
	WorkflowRunId string        `json:"workflowRunId"`
}

// GateStatus defines model for Gate.Status.
type GateStatus string

// GateApprovers Who may decide: Principals listed explicitly, or members of the listed teams (checked through the platform Authorizer).
type GateApprovers struct {
	Principals *[]string `json:"principals,omitempty"`
	Teams      *[]string `json:"teams,omitempty"`
}

// GateDecision defines model for GateDecision.
type GateDecision struct {
	Approve bool    `json:"approve"`
	Note    *string `json:"note,omitempty"`
}

// GateSpec defines model for GateSpec.
type GateSpec struct {
	// Approvers Who may decide: Principals listed explicitly, or members of the listed teams (checked through the platform Authorizer).
	Approvers GateApprovers `json:"approvers"`

	// TimeoutSeconds Expire (treat as denial) after this long pending; 0 waits forever.
	TimeoutSeconds *int64 `json:"timeoutSeconds,omitempty"`
}

// Plan defines model for Plan.
type Plan struct {
	Entries []PlanEntry `json:"entries"`
}

// PlanEntry defines model for PlanEntry.
type PlanEntry struct {
	Action PlanEntryAction `json:"action"`
	Error  *string         `json:"error,omitempty"`
	Kind   *PlanEntryKind  `json:"kind,omitempty"`

	// MemberCount Live Entity count the relevant selector matches now.
	MemberCount int64  `json:"memberCount"`
	Name        string `json:"name"`

	// NewSelector Structured selector data — deliberately not an expression language (charter non-goal; ADR-0003 review).
	NewSelector *ViewSelector `json:"newSelector,omitempty"`

	// OldSelector Structured selector data — deliberately not an expression language (charter non-goal; ADR-0003 review).
	OldSelector *ViewSelector `json:"oldSelector,omitempty"`
}

// PlanEntryAction defines model for PlanEntry.Action.
type PlanEntryAction string

// PlanEntryKind defines model for PlanEntry.Kind.
type PlanEntryKind string

// Provenance Per-attribute stamp — which Run/Syncer wrote the value, when, from which Source (charter §2.1). Always exactly one answer.
type Provenance struct {
	At         time.Time            `json:"at"`
	SourceId   *string              `json:"sourceId,omitempty"`
	WriterKind ProvenanceWriterKind `json:"writerKind"`
	WriterRef  string               `json:"writerRef"`
}

// ProvenanceWriterKind defines model for Provenance.WriterKind.
type ProvenanceWriterKind string

// Run defines model for Run.
type Run struct {
	FinishedAt *time.Time `json:"finishedAt,omitempty"`
	Id         string     `json:"id"`
	StartedAt  time.Time  `json:"startedAt"`
	Status     RunStatus  `json:"status"`

	// StepName The Step within that Workflow.
	StepName *string `json:"stepName,omitempty"`

	// TriggeredBy Name of the Trigger that fired this Run; absent for manual/API launches (charter §1.8 descent, Trigger → Run).
	TriggeredBy *string `json:"triggeredBy,omitempty"`
	ViewRef     *string `json:"viewRef,omitempty"`
	ViewVersion *int64  `json:"viewVersion,omitempty"`
	WorkflowId  string  `json:"workflowId"`

	// WorkflowRunId The WorkflowRun this Run executed under, when it ran as a Workflow Step (charter §1.8 descent, Workflow → Run).
	WorkflowRunId *string `json:"workflowRunId,omitempty"`
}

// RunStatus defines model for Run.Status.
type RunStatus string

// StartRun One Step against a View (charter §2.3: Step = Actuator + content + params). Params are interpreted by the named Actuator; their pinned JSON-Schema Contract documents land with the Phase-2 Contract machinery.
type StartRun struct {
	Actuator *StartRunActuator `json:"actuator,omitempty"`

	// CredentialRefs CredentialRef names to project into the execution pods. The launching Principal needs the `use` grant on each (checked at dispatch; use never implies read — charter §2.5).
	CredentialRefs *[]string `json:"credentialRefs,omitempty"`

	// Params Actuator-interpreted Step params (e.g. script source).
	Params *map[string]interface{} `json:"params,omitempty"`

	// Slices Partition the target set across this many parallel execution Jobs (clamped to the target count).
	Slices   *int64 `json:"slices,omitempty"`
	ViewName string `json:"viewName"`
}

// StartRunActuator defines model for StartRun.Actuator.
type StartRunActuator string

// Step One DAG node — an actuation (Actuator + params against a View, charter §2.3) or a Gate; exactly one shape is set.
type Step struct {
	Actuator       *string   `json:"actuator,omitempty"`
	CredentialRefs *[]string `json:"credentialRefs,omitempty"`
	Gate           *GateSpec `json:"gate,omitempty"`
	Name           string    `json:"name"`

	// Needs Step names that must reach a terminal state first.
	Needs    *[]string               `json:"needs,omitempty"`
	Params   *map[string]interface{} `json:"params,omitempty"`
	Slices   *int64                  `json:"slices,omitempty"`
	ViewName *string                 `json:"viewName,omitempty"`

	// When Edge condition on the needs' outcomes; success is the default (all needs succeeded).
	When *StepWhen `json:"when,omitempty"`
}

// StepWhen Edge condition on the needs' outcomes; success is the default (all needs succeeded).
type StepWhen string

// Trigger Anything that starts a Run (charter §2). v1 kind is `schedule` — a Temporal Schedule fires Runs with these launch parameters, executing as the declared service Principal (ADR-0010).
type Trigger struct {
	Actuator       *string                 `json:"actuator,omitempty"`
	CredentialRefs *[]string               `json:"credentialRefs,omitempty"`
	Cron           string                  `json:"cron"`
	Kind           TriggerKind             `json:"kind"`
	Name           string                  `json:"name"`
	Params         *map[string]interface{} `json:"params,omitempty"`
	Paused         *bool                   `json:"paused,omitempty"`

	// Principal Service identity the fired Runs execute as; its `use` grants are checked at dispatch exactly like an API launch (§2.5).
	Principal *string `json:"principal,omitempty"`
	Slices    *int64  `json:"slices,omitempty"`
	ViewName  string  `json:"viewName"`
}

// TriggerKind defines model for Trigger.Kind.
type TriggerKind string

// TriggerDetail defines model for TriggerDetail.
type TriggerDetail struct {
	// Schedule Observed Temporal Schedule state; absent when the schedule has not been reconciled yet (e.g. within one interval of declaring).
	Schedule *TriggerScheduleState `json:"schedule,omitempty"`

	// Trigger Anything that starts a Run (charter §2). v1 kind is `schedule` — a Temporal Schedule fires Runs with these launch parameters, executing as the declared service Principal (ADR-0010).
	Trigger Trigger `json:"trigger"`
}

// TriggerScheduleState Observed Temporal Schedule state; absent when the schedule has not been reconciled yet (e.g. within one interval of declaring).
type TriggerScheduleState struct {
	NextFireTimes *[]time.Time `json:"nextFireTimes,omitempty"`
	Paused        *bool        `json:"paused,omitempty"`

	// RecentRuns Workflow executions recently started by this Trigger.
	RecentRuns *[]struct {
		At         time.Time `json:"at"`
		WorkflowId string    `json:"workflowId"`
	} `json:"recentRuns,omitempty"`
}

// View defines model for View.
type View struct {
	// DeclaredBy Which declaration path owns this View — cac (Git-declared desired state, charter §1.2) or api. cac Views are Git-only.
	DeclaredBy *ViewDeclaredBy `json:"declaredBy,omitempty"`
	Name       string          `json:"name"`

	// Selector Structured selector data — deliberately not an expression language (charter non-goal; ADR-0003 review).
	Selector ViewSelector `json:"selector"`
	Version  int64        `json:"version"`
}

// ViewDeclaredBy Which declaration path owns this View — cac (Git-declared desired state, charter §1.2) or api. cac Views are Git-only.
type ViewDeclaredBy string

// ViewDeclaration defines model for ViewDeclaration.
type ViewDeclaration struct {
	Name string `json:"name"`

	// Selector Structured selector data — deliberately not an expression language (charter non-goal; ADR-0003 review).
	Selector ViewSelector `json:"selector"`
}

// ViewResolution defines model for ViewResolution.
type ViewResolution struct {
	Entities []Entity `json:"entities"`
	View     View     `json:"view"`
}

// ViewSelector Structured selector data — deliberately not an expression language (charter non-goal; ADR-0003 review).
type ViewSelector struct {
	Facets *[]FacetPredicate  `json:"facets,omitempty"`
	Kinds  *[]string          `json:"kinds,omitempty"`
	Labels *map[string]string `json:"labels,omitempty"`
}

// Workflow A Temporal-backed DAG of Steps with Gates (charter §2, ADR-0011). CaC-only in v1.
type Workflow struct {
	Name  string `json:"name"`
	Steps []Step `json:"steps"`
}

// WorkflowRun defines model for WorkflowRun.
type WorkflowRun struct {
	FinishedAt   *time.Time        `json:"finishedAt,omitempty"`
	Id           string            `json:"id"`
	Principal    *string           `json:"principal,omitempty"`
	StartedAt    time.Time         `json:"startedAt"`
	Status       WorkflowRunStatus `json:"status"`
	TemporalId   *string           `json:"temporalId,omitempty"`
	WorkflowName string            `json:"workflowName"`
}

// WorkflowRunStatus defines model for WorkflowRun.Status.
type WorkflowRunStatus string

// WorkflowRunDetail defines model for WorkflowRunDetail.
type WorkflowRunDetail struct {
	Steps []struct {
		// GateId The Step's Gate (Gate Steps).
		GateId *string `json:"gateId,omitempty"`
		Name   string  `json:"name"`

		// RunId The Step's Run (actuation Steps).
		RunId *string `json:"runId,omitempty"`

		// Status Terminal outcome from the WorkflowRun summary (succeeded, failed, skipped); absent while the execution is live — descend into the linked Run or Gate for live state.
		Status *string `json:"status,omitempty"`
	} `json:"steps"`
	WorkflowRun WorkflowRun `json:"workflowRun"`
}

// RunID defines model for RunID.
type RunID = string

// ViewName defines model for ViewName.
type ViewName = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListGatesParams defines parameters for ListGates.
type ListGatesParams struct {
	Status *ListGatesParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListGatesParamsStatus defines parameters for ListGates.
type ListGatesParamsStatus string

// ResolveViewParams defines parameters for ResolveView.
type ResolveViewParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DeclareCredentialRefJSONRequestBody defines body for DeclareCredentialRef for application/json ContentType.
type DeclareCredentialRefJSONRequestBody = CredentialRef

// DesiredStateApplyJSONRequestBody defines body for DesiredStateApply for application/json ContentType.
type DesiredStateApplyJSONRequestBody = DesiredState

// DesiredStatePlanJSONRequestBody defines body for DesiredStatePlan for application/json ContentType.
type DesiredStatePlanJSONRequestBody = DesiredState

// DecideGateJSONRequestBody defines body for DecideGate for application/json ContentType.
type DecideGateJSONRequestBody = GateDecision

// StartRunJSONRequestBody defines body for StartRun for application/json ContentType.
type StartRunJSONRequestBody = StartRun

// DeclareViewJSONRequestBody defines body for DeclareView for application/json ContentType.
type DeclareViewJSONRequestBody = ViewSelector

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List CredentialRef pointers the Principal may read
	// (GET /credential-refs)
	ListCredentialRefs(w http.ResponseWriter, r *http.Request)
	// Get one CredentialRef pointer (reader grant required)
	// (GET /credential-refs/{name})
	GetCredentialRef(w http.ResponseWriter, r *http.Request, name string)
	// Declare a CredentialRef pointer (admin grant required)
	// (PUT /credential-refs/{name})
	DeclareCredentialRef(w http.ResponseWriter, r *http.Request, name string)
	// Reconcile the graph's Views to a declared desired state
	// (POST /desired-state/apply)
	DesiredStateApply(w http.ResponseWriter, r *http.Request)
	// Diff a declared desired state against the graph's Views
	// (POST /desired-state/plan)
	DesiredStatePlan(w http.ResponseWriter, r *http.Request)
	// Get one Entity with its Facets and per-attribute Provenance
	// (GET /entities/{id})
	GetEntity(w http.ResponseWriter, r *http.Request, id string)
	// List Gates (the approval inbox)
	// (GET /gates)
	ListGates(w http.ResponseWriter, r *http.Request, params ListGatesParams)
	// Approve or deny a pending Gate
	// (POST /gates/{id}/decision)
	DecideGate(w http.ResponseWriter, r *http.Request, id string)
	// Start a Run of the Phase-0 Workflow against a View
	// (POST /runs)
	StartRun(w http.ResponseWriter, r *http.Request)
	// Get a Run summary
	// (GET /runs/{id})
	GetRun(w http.ResponseWriter, r *http.Request, id RunID)
	// Live SSE tail of the Run's full task-event stream
	// (GET /runs/{id}/events)
	TailRunEvents(w http.ResponseWriter, r *http.Request, id RunID)
	// List declared Triggers
	// (GET /triggers)
	ListTriggers(w http.ResponseWriter, r *http.Request)
	// Get one Trigger with its live schedule state
	// (GET /triggers/{name})
	GetTrigger(w http.ResponseWriter, r *http.Request, name string)
	// Get a View (versioned, CaC-declared graph query)
	// (GET /views/{name})
	GetView(w http.ResponseWriter, r *http.Request, name ViewName)
	// Declare a View's selector (bumps the version on change)
	// (PUT /views/{name})
	DeclareView(w http.ResponseWriter, r *http.Request, name ViewName)
	// Resolve the View's live Entity set
	// (GET /views/{name}/entities)
	ResolveView(w http.ResponseWriter, r *http.Request, name ViewName, params ResolveViewParams)
	// Get one WorkflowRun with per-Step outcomes
	// (GET /workflow-runs/{id})
	GetWorkflowRun(w http.ResponseWriter, r *http.Request, id string)
	// List declared Workflows
	// (GET /workflows)
	ListWorkflows(w http.ResponseWriter, r *http.Request)
	// Get one Workflow declaration
	// (GET /workflows/{name})
	GetWorkflow(w http.ResponseWriter, r *http.Request, name string)
	// Start one execution of a Workflow
	// (POST /workflows/{name}/runs)
	StartWorkflowRun(w http.ResponseWriter, r *http.Request, name string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCredentialRefs operation middleware
func (siw *ServerInterfaceWrapper) ListCredentialRefs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCredentialRefs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCredentialRef operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialRef(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCredentialRef(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeclareCredentialRef operation middleware
func (siw *ServerInterfaceWrapper) DeclareCredentialRef(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeclareCredentialRef(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DesiredStateApply operation middleware
func (siw *ServerInterfaceWrapper) DesiredStateApply(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DesiredStateApply(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DesiredStatePlan operation middleware
func (siw *ServerInterfaceWrapper) DesiredStatePlan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DesiredStatePlan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEntity operation middleware
func (siw *ServerInterfaceWrapper) GetEntity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEntity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGates operation middleware
func (siw *ServerInterfaceWrapper) ListGates(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGatesParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGates(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DecideGate operation middleware
func (siw *ServerInterfaceWrapper) DecideGate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DecideGate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartRun operation middleware
func (siw *ServerInterfaceWrapper) StartRun(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartRun(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRun operation middleware
func (siw *ServerInterfaceWrapper) GetRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id RunID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRun(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TailRunEvents operation middleware
func (siw *ServerInterfaceWrapper) TailRunEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id RunID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TailRunEvents(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTriggers operation middleware
func (siw *ServerInterfaceWrapper) ListTriggers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTriggers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrigger operation middleware
func (siw *ServerInterfaceWrapper) GetTrigger(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrigger(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetView operation middleware
func (siw *ServerInterfaceWrapper) GetView(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name ViewName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetView(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeclareView operation middleware
func (siw *ServerInterfaceWrapper) DeclareView(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name ViewName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeclareView(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResolveView operation middleware
func (siw *ServerInterfaceWrapper) ResolveView(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name ViewName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ResolveViewParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResolveView(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkflowRun operation middleware
func (siw *ServerInterfaceWrapper) GetWorkflowRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkflowRun(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkflows operation middleware
func (siw *ServerInterfaceWrapper) ListWorkflows(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkflows(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkflow operation middleware
func (siw *ServerInterfaceWrapper) GetWorkflow(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkflow(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartWorkflowRun operation middleware
func (siw *ServerInterfaceWrapper) StartWorkflowRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartWorkflowRun(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/credential-refs", wrapper.ListCredentialRefs)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/credential-refs/{name}", wrapper.GetCredentialRef)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/credential-refs/{name}", wrapper.DeclareCredentialRef)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/desired-state/apply", wrapper.DesiredStateApply)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/desired-state/plan", wrapper.DesiredStatePlan)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/entities/{id}", wrapper.GetEntity)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/gates", wrapper.ListGates)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/gates/{id}/decision", wrapper.DecideGate)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/runs", wrapper.StartRun)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/runs/{id}", wrapper.GetRun)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/runs/{id}/events", wrapper.TailRunEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/triggers", wrapper.ListTriggers)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/triggers/{name}", wrapper.GetTrigger)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/views/{name}", wrapper.GetView)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/views/{name}", wrapper.DeclareView)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/views/{name}/entities", wrapper.ResolveView)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/workflow-runs/{id}", wrapper.GetWorkflowRun)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/workflows", wrapper.ListWorkflows)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/workflows/{name}", wrapper.GetWorkflow)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/workflows/{name}/runs", wrapper.StartWorkflowRun)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FzrbhtJdn6Vg04Ai1heJNsJdiXsD9nWGN6deATJmfkxa8Cl7kOyVs2qnqpq0owhIL/yAEHeIe+RR9kn",
	"Cc6p6hu7eJEsKQvkzwyt7rqd63cu1d+SVC8KrVA5m5x+SwphxAIdGv7XVak+vKMfUiWnSSHcPBkmSiww",
	"OU1klgwTg7+V0mCWnDpT4jCx6RwXgka4dUFvWWekmiV3d8PkZ4mrjzz2W5KhTY0snNQ0MT0BmhaO3Bzh",
	"y1Li6nQy+Ut5fPwqpb/zL/wCBqdoUKUIK+nmunTAC+JgnAxje+T/3WeXd/SyLbSyyAR4I7Ir/K1E6+hf",
	"qVYOFf8URZHLVNABJn+1dIpvrWn/0eA0OU3+YdIQd+Kf2smFMdr4pbpU+DRHMH4xkBYWIp9qs8AsuRsm",
	"b7Wa5jJ9pl3om79iypvQK4UZ3KxBKO3maCDDNBeGVwSm9d0w+UGbG5llqJ5nd5dGqlQWIodcpLcWXKAb",
	"cRhmRihHm/qo3Q+6VNnz7IkELavolmm0oLQD/Cotb+ZflSjdXBv5b/gMGzqHNygMGnD6FhWshIXCoEXl",
	"iJelg1SXecY7vEFYopFTiRkcSbUUucyGgF8LIuYQtIGV0WoG0toSzUSUmST1G4zhFyOdQ0Wy4TpMWcgs",
	"y3ElDMLf/v2/QMCNyCA1mKFyUuQkVa+PT4agcEnypFdqZkSGGThNUqbWC13aMxAKxA3teWNs/QoIlUGG",
	"irZeoBkx5+Ho9fGrwfgvii1OoBQR8m09yQdFTJKe0oXRBRonvbb7V1GVi+T01wTVMhkmU5lj8nm4aSmG",
	"yS2u+5bsB4l5xsZJKqbLjUhvUWWwEA6NFDkZqt5UKmoVL9QSlsJ4w6gNqxuUKiPGzhEK3SarhYUulYtM",
	"f9e2f7/ytod00rBsczQvvWxt6mmvSPw2N3appXJo4HcgK1pCoXOZromHN0bfIqmixdSgq08OR+lcGBr3",
	"P//9cvxPgzH8S/XEi0KBxkrrLATSFblwZAGZ0XNBKgUGRcaEIBYPN9gXaN3m4e3v7cjvIxkmS1Hm9P+V",
	"Nre5FtlI8indOspfb+kwe7NuTygKmQyTVKQ0hnbzk8rXlV/pzSHbsiYdLuw+pY7J6V09szBGrOnfuU6F",
	"06bPmzeeBiM7FwVmILLMoLVw1BDilAXKFiLFIf8ctISmkYFKJntnIpdgPqFYxL18W9aC+21GDGseNUdo",
	"UykmjO/Q0nzXTriIkpDxnZZ5DhW7IPPvg6UBbaE7Gb/ko3aFJm3Lun0An0hFIhxyRs5mAUYdNOMnPyA2",
	"F+GhwyciNPWucdOxCUkDprm+x6S/hBH92TZ47vcaY+SF17We1ZVZVM4q5fwzrr1xzjJJ5xH5ZWd4b2Bv",
	"4Vup4kvk4gbz75p84/CMiXm5jf3Xa20nzDudlosACroEwppwO+GAf+tumExFiu5w1v5Ar+/la9hEPXv0",
	"IIxIevtfoLVihvvtRfVibG6/y97ctS2LcqsweolKKP94FxEumzdJ4URebjE2vA/IArNgasSMfxz5mUA4",
	"J9I5WnJnbUtL9udkMI7aSH+AatnOtreS4tJgRrgRI/LyWym8WHe3/6frnz4Cr8H+NfgGzGDKqGVRWgc8",
	"dlw5gB2UJex/kAOoDhd2FTvQ++gxRMF0MHsFmIaf1y/fDcmmC4fZOcsLQQjhktMkEw5HTrJLinl7mT1o",
	"iMcHEfMV/bPSLk5QcldlB38WqDJ6OKwoQVbFA14ip8foUehiHRbRRSq7T3F9tp99bM66Y8Lk9X6HLTa1",
	"Cb+NzedtpnbF85e5hoVYg6fraRNSWMilpdgFv1KsJF2+5tBkgYsbNBb0lOU5vORQLCz5fUxv6Z9zo8vZ",
	"vIsoz6tozAxiQLKoV+4Y0W3OoPH5tPR9htxtodI7TKWNhyiefq25b7TOUagdwrXB1WqKbSy6LjB9TG0k",
	"/dGlu8ZUqyzC9wuWZDhyJDwgLAd1Ih+AmDqOdaSFnILQoBBncAwrIZ2FqTYUOXgW1korlfvn143CUqzC",
	"uCpOBhM3SZe5UFFPbCrUcohrpVkulDPrQ9wrz7xtL36WPlfq6KKyGl4Fk2FSFpn/ITJdUNijtC7YguTo",
	"4iEtVv67H+zKblxFKM/re0DBI6JCjXpbZiO6kNfctxSx9uXhR7lE8GgGUnolZHhyXFKEbzHH1JH6C8eO",
	"VunV+BD+74hpFK6uw7SHoOv6XQqH8uxhQ+OxUmBol0RRoehAm40AHc1IOGfkTemQAqFFwbmY1Vymc7gq",
	"1eR6rVLk5I7zYIBhwRBWc1RDmBq9CC9f69Kk2I3dTwZjOM9XYm0Bv4rU5WvQCkEou6qUcUNK7+FVLS/4",
	"Ie49V0Y6NH/eEEbLh0mGiSlVVNz8sJDL2G0cWyu0xw3pDDE2XJURMzGVStr5/dDEFrxgHdH9XjPtQhKm",
	"VMr/smWaImaMJaZC5vwjJXnKd6CKeP6ecPG1w6JJfAkHVcQYzXgFO1Ghp+50Hznh5Z16iIr9lFMO7Nkh",
	"XJXqrEoQTtkYqFLkk/PLD5CLUrFh6MT+vwdaBJUb1nP+7T/+k+YJEKC3R7JxcZnxz35GU/noA2xPZQ+3",
	"SfYmMutT+JfmlZoGgF8xLQn2cGLQKzBIB0YocqWiHuUZtI0k9Vs7abILHgZsGEBhI7Yxpbmmp0Fzuuf8",
	"SQVJEjMhlXUggItDHfvz6tS/80c4T10pyBf8DkJKHX4HXMKygzFc8g8QBoETloVB56sZrk7ZVzOc0d+k",
	"gUIqhRlQqDS69hHdW62cEWkT9FnIhfJZXp/7nguLo5fNiwuRzqVCs44aw7CiP/yUc5KniVBW3uQcJ1WZ",
	"xvovnkBRnexnr7r07KSpfDgKTkNhtK/wKKf5CF6MfCI3s2MgefN6JNWsldxXiJmvuHwpLX7x5RbQClCk",
	"8wZ0CweZtAU56DMoLYYMr1wUuUTrs7jkkDYywkytw+G2Z3T/0BVPR22us8T4EXCE49kY/BDwDieeBLW5",
	"TNF2OHWyWW25FMZx7ojJ4oSZIYEUByI12lqvqguh1rx6nmPeovaf9A3ZqVwsCl8Bac3B2GewBdwupJIL",
	"EpSTmLFZtkqtu3W4fjOupz6O7Ovou/P3oHQWSjwKvFDTiY5aOhnI3dXlYYfrrwYUyQmgqOGsAyc4gw3S",
	"Ei336dEBenG4WM1CNmJfkMNx0m5UibF4hyUxqCJ5Nc67GFYgAQ7NQiqRh/T1VBrLRZ2HaMUOcT7AYe2Q",
	"oWFCbiYSyWUzJEPsc6kQVILJ8AJ06VK9QHsGDD2sJd7S86BacCTyysDU4CSIf430/MgAWUrDiJmRaMQ6",
	"xgB2TMqrxHvfjqi1Y/vHbGKXRh6V3G7bHw3GsDwBipDoRF9IRLIyxy+h/PkJF4U2Iofr8IBhDHtvW/sQ",
	"W5lbaBowhpWdUDNy5Z5Uochh0Sxl2i67Hp2/uxodH58cD55VWVLjEdDeiLEiS9SNbVWhHcJciNJiFk+E",
	"1AmciPYFylXpeaarB5bMkQCoQNgzkM62/ZyHEhEfV9utXN5SHAQNDIWjtm/rY+pH0sh4MBkqEcyj4W5T",
	"H5TgHToh835EU3PvsCJWJeq+aNfg/YNrYBvnqYbv2Hl3yb7TuiGVwSyijmxp62CCATTJRHXkUHp2cIOo",
	"wGCqVUrhEqzRBSQRwh7yWgw5liKn+MVrq1SzqEoq/Op+kAY/ycVGRumwMK9v97frg0GC+STfkbRrBf1r",
	"VEIAjd7P1xBwvMfM0lahU8cjPTzW3xkTbQbm7ThjSzC+P7lKAKS/526pfzMrLdN5r+0J9EoFaMfxCYNZ",
	"kcLRe+lG8VJ0G/ecjF963FPIMY+jSbx5oQm0ytddx3e/toOt5tQ+MMm1vEeoGzdF1QytPXzewp927Tpa",
	"73vEo8U3u3eLV2h1XsZ3yG7lPknipnAbq/sfcp4oqmfpCVvZdo525nITpJoydaXHGiHhmgknWNIzzOUN",
	"GuEwX7NpFArwa2HQEo8pOp6VYtbKGiqtRjMt8jPwKOX4FRikTUYt40Pq1005NEJH8oP3xDWP0hrQo3nd",
	"RdHHmrVjGnGLTMYhlp5y3BpwIgUdnazWy2Gg58nJYAxvxVu2HCAVLE+iLmer8tAiBxOcw8J9BY1KlXjm",
	"zzto8dQZ1A4W/HvOr7ogAHsyhIchwE5u7mPFi4Oycy3GbIWDPXnpPqcQelsak6TnhWVhhiP+L4v4YGdn",
	"ZO+B2Z4nDQtwmNbkJXYs0jB0Y7IqFg+hq6+LuI1UrC0XC2HWcFRzfAie4UOwt7IoMBu00KXMcSPjJi3k",
	"conBstoUKZCsEnO5VLc+NCG8wOSaauMHMKw4JFG7NfTd1hcWdPKQhjB6dRtWo2fbTcAdN0hOdSSPwCcb",
	"idLpRcBcdeX+8sOpT5KtC8wAfZpkZkQxh6OQ1pRabYKtoUdYQ+4l9cRM52idhxnjkMI9Blsa8j6eqBSb",
	"KYuN5UzOC5HOcfRyfJwMk9LkyWkyd66wp5PJarUaC3481mY2CWPt5McPby8+Xl/wGC6GO4qiyL8K5+g4",
	"LXB0mhyPT/x7ukBFoO80eTU+Hr9KfMcNC+mkW3X1Cud7o0gH+USkG8mP0rq33dh+43rDy+Pje7WjP0Zr",
	"ZL9fveonXqATjDHYi5E61L3DvfZfmvf18cm2vdSnnHRa73nQq/2DmhsN3EbuNTxQFLo59cJv3m52wYs1",
	"75Yn2OTY5BvJ012LcV2CXKErjbLV3LFG6w6tOF9vOFmqNKDKeKBPW5kw12Y3NpFXabBlOodUZ+jDGr6x",
	"YDdatSuUcfyHANe6YvYeu1L2vUJ2D9mKX8YIZHs2EaERr/ePqG+kdGXqPTrOHETFCo5IiNCEQktlZAd1",
	"bixc1fr126Ncf/o8TIoyYkl8SIZ9NvNtpTc6Wz8lh7v7v/u/Fq86vO/I2fF+AWhdJntO0fzD/hH19bKu",
	"aAa2g9gmnCJbSNWXTTJ5IfcxYgc9IZb49iVtIwbvvPCFwdCkp3w+hTuZ7MQ3MtkJ9zHZhvw+Z3Lkr6iJ",
	"5sGb9R9TkQ7Y1RemVGhbKRaluZesvsmG2RhEIUcbs9Kpw60UmiEbwyWaEad6QuXBv2Ow0Jwg87UOafz2",
	"QzfXWehcsg6sk3kOwp8zZkXb1xzOmVpPo1+d6xTPrF7cVLf15qPIScqZgA9SqY7oXlV5WmYB48MXNjDX",
	"aRBb7ovEZLeoWgGjovvOrMEQoJzWuWEZKqEdCHoKmZFTVxe95HQ6GMOFF5QgR74tOwBYzkFXqZd0LtQM",
	"PXz1YcESQ/9r6JEjjbnJhXVgRCZLCzc41aS7VRErFDb2Ch8z6f+b7HUY9zgS+E5Op1vlrK6J96TTS2CV",
	"uZt8k9ndVoD/Ht1FdS3jyQi3cTtlCwlDv2ZWv/Y4oChMy+kv6ay/feGvfhadJsfu/Y390Oiet9c/E1Nm",
	"5IZ2RlucoUvi6/9Wolk3G2iSMfWi39v4f/f5OcK799Eka18qmBZDULgi/xcaGSLhVMhqsunj44ocpLrR",
	"XwOQYKqzHkyydlv8o7N4uMXCX/kpLPe5lG5OupkKcvpNuMehFh2BTvPCQtVcXoVrNYqzbKh79xl8E0ww",
	"6HrKS1VTOBSLg+8zNLHaJKSFA2RlwpH3yZCch2najVZCco9BXQjkvkErZ0rkZ510FxtKk1mQDo5eHr8c",
	"xH1JKjN873vPn8KLdC5IHORFXkbcdkURkaZYEDPIpvhDN6Rpelj/zjH+vSzt9wUF4W4HSWyGag2iupcB",
	"72sAZUKluVKoroTU7Z9PIx/19AfJxsmjrVsv2feO4V4U8CsPlKSHO1MmSGhcCm3VVb6z0flOj17Dxb0A",
	"pOLjE6GPHUTtJN9xyY251hmylhbJPTjM14PHQCKivVYEX8Qmbl6Z+K/oeAxR03Tid7wjB1jkYm2bmgN7",
	"UOBRbKumOs/1KtQOjj6ef7oOlcPBGD5y6OpMqbyjIp/jqpvygUbsZdZ8Mml9/6G4ybFqJDt+BT+eTH58",
	"yUFKFiqQAr740SNU2ZewGa1SH2VdlepFzYI01zYebHwSMr8q1YU//17ZcfjVeWKN/NRd4Yl8waff8IVm",
	"xOUXv2E/zZnvWf6SCSdOv0AuFSdQmde8t/H3ig5fZLq+vgAnZF5pnicSM8IJeztqb+n7RKv9xYGoSIXm",
	"HZ+5qKvFTePgaROshE9wvJcOOsEwB6p8y4CTH0uJqza26ebAbyT7BYIg0lallSBsGS/O8KJOXJ9ffgC+",
	"ctP6wkcfY1eneJZaxtaPMvTl7GKJZt1QsO6UikDezZdC0FcxcF95oElCVvFq6Unf6217YUFXjW+ef2QJ",
	"fKcYQfOv/k4NOLlA22QXqvodyMyGxAbfs6m7JE87d3PCnREwpZpVYh5ulkAusgzNxr2TbWWET/XtwSfz",
	"J90+xy2epToY0YOiTttpFRw/VnBbLVNHt76q21nsqRL9JG/8qY6+sPXY8rPvJnoyngTEEWWFf/YYLtzf",
	"IwqlVhJ/soC1JvoKMsfog/ub4frTdq0Kyka8IQ2mDo5EIUfEu0Fbg8chMVl/bS3Y3tG2j9r0Ut2txsHN",
	"u5pBq6VtCoMGp6X15nrhpe/18R/YNGAmXavTXFTtoIUGgocosi0hH22nlpPHx/QbXXvPmjncJZ6dskGj",
	"yGlpDFm/qrD/UMz/GKUb2hnBsiqVfHRTLgrvL8L2QKuQYA4pl7ZhmLT7GaMWgpshlxX3D0h95XIhXSfz",
	"tes203dntfbxttXMuYXLeetGOt/sCn6SmV4RUTpIRWgS+l6LFUhaL/LCbu7hu2wU8bjy8aNYlLf98ukD",
	"nP2pB9rdVixubLKsLByBZHDEKJn+EGK5pRTQi5cGQz9b3TjGI97XjVA95/VLpxfpyQSp3zS3RZaavq8K",
	"XXBn2qOBinZrGtujAs2ICVVdwHq6BHnns2JRUap2txGDcMdqHYmcHByJ7AgttoUP9Q6eJX7Y8dm0fQFE",
	"K/e4I4JojnPX4cABsK7e2zOoxTZt2EiwPp74twHMU2LoTYI3qc+n6c6JVii23dY2MkM2p2a9YX5f2PZn",
	"Vf0dN64wbH6lc1jfbRMW5JS83Fxk9b0gtsVkajLGt3G14/zjTjt88hR2eF8ytvXq+HFSrCSAjX3X09bn",
	"F/xmOBQPEuHbRyeikJPlCTnl/w0AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
