//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ProvenanceWriterKind.
const (
	ProvenanceWriterKindRun    ProvenanceWriterKind = "run"
	ProvenanceWriterKindSyncer ProvenanceWriterKind = "syncer"
)

// Valid indicates whether the value is a known member of the ProvenanceWriterKind enum.
func (e ProvenanceWriterKind) Valid() bool {
	switch e {
	case ProvenanceWriterKindRun:
		return true
	case ProvenanceWriterKindSyncer:
		return true
	default:
		return false
	}
}

// Defines values for RunStatus.
const (
	Canceled  RunStatus = "canceled"
	Failed    RunStatus = "failed"
	Pending   RunStatus = "pending"
	Running   RunStatus = "running"
	Succeeded RunStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the RunStatus enum.
func (e RunStatus) Valid() bool {
	switch e {
	case Canceled:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// Entity defines model for Entity.
type Entity struct {
	Id           string            `json:"id"`
	IdentityKeys map[string]string `json:"identityKeys"`
	Kind         string            `json:"kind"`
	Labels       map[string]string `json:"labels"`
}

// EntityDocument defines model for EntityDocument.
type EntityDocument struct {
	Entity Entity  `json:"entity"`
	Facets []Facet `json:"facets"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Facet defines model for Facet.
type Facet struct {
	Namespace string `json:"namespace"`

	// Provenance Per-attribute stamp — which Run/Syncer wrote the value, when, from which Source (charter §2.1). Always exactly one answer.
	Provenance Provenance `json:"provenance"`

	// Value The Facet document fragment (schema attaches per namespace, §1.1).
	Value interface{} `json:"value"`
}

// FacetPredicate defines model for FacetPredicate.
type FacetPredicate struct {
	// Equals JSON value the addressed field must equal.
	Equals    interface{} `json:"equals"`
	Namespace string      `json:"namespace"`
	Path      *string     `json:"path,omitempty"`
}

// Provenance Per-attribute stamp — which Run/Syncer wrote the value, when, from which Source (charter §2.1). Always exactly one answer.
type Provenance struct {
	At         time.Time            `json:"at"`
	SourceId   *string              `json:"sourceId,omitempty"`
	WriterKind ProvenanceWriterKind `json:"writerKind"`
	WriterRef  string               `json:"writerRef"`
}

// ProvenanceWriterKind defines model for Provenance.WriterKind.
type ProvenanceWriterKind string

// Run defines model for Run.
type Run struct {
	FinishedAt  *time.Time `json:"finishedAt,omitempty"`
	Id          string     `json:"id"`
	StartedAt   time.Time  `json:"startedAt"`
	Status      RunStatus  `json:"status"`
	ViewRef     *string    `json:"viewRef,omitempty"`
	ViewVersion *int64     `json:"viewVersion,omitempty"`
	WorkflowId  string     `json:"workflowId"`
}

// RunStatus defines model for Run.Status.
type RunStatus string

// StartRun defines model for StartRun.
type StartRun struct {
	ViewName string `json:"viewName"`
}

// View defines model for View.
type View struct {
	Name string `json:"name"`

	// Selector Structured selector data — deliberately not an expression language (charter non-goal; ADR-0003 review).
	Selector ViewSelector `json:"selector"`
	Version  int64        `json:"version"`
}

// ViewResolution defines model for ViewResolution.
type ViewResolution struct {
	Entities []Entity `json:"entities"`
	View     View     `json:"view"`
}

// ViewSelector Structured selector data — deliberately not an expression language (charter non-goal; ADR-0003 review).
type ViewSelector struct {
	Facets *[]FacetPredicate  `json:"facets,omitempty"`
	Kinds  *[]string          `json:"kinds,omitempty"`
	Labels *map[string]string `json:"labels,omitempty"`
}

// RunID defines model for RunID.
type RunID = string

// ViewName defines model for ViewName.
type ViewName = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ResolveViewParams defines parameters for ResolveView.
type ResolveViewParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// StartRunJSONRequestBody defines body for StartRun for application/json ContentType.
type StartRunJSONRequestBody = StartRun

// DeclareViewJSONRequestBody defines body for DeclareView for application/json ContentType.
type DeclareViewJSONRequestBody = ViewSelector

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get one Entity with its Facets and per-attribute Provenance
	// (GET /entities/{id})
	GetEntity(w http.ResponseWriter, r *http.Request, id string)
	// Start a Run of the Phase-0 Workflow against a View
	// (POST /runs)
	StartRun(w http.ResponseWriter, r *http.Request)
	// Get a Run summary
	// (GET /runs/{id})
	GetRun(w http.ResponseWriter, r *http.Request, id RunID)
	// Live SSE tail of the Run's full task-event stream
	// (GET /runs/{id}/events)
	TailRunEvents(w http.ResponseWriter, r *http.Request, id RunID)
	// Get a View (versioned, CaC-declared graph query)
	// (GET /views/{name})
	GetView(w http.ResponseWriter, r *http.Request, name ViewName)
	// Declare a View's selector (bumps the version on change)
	// (PUT /views/{name})
	DeclareView(w http.ResponseWriter, r *http.Request, name ViewName)
	// Resolve the View's live Entity set
	// (GET /views/{name}/entities)
	ResolveView(w http.ResponseWriter, r *http.Request, name ViewName, params ResolveViewParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetEntity operation middleware
func (siw *ServerInterfaceWrapper) GetEntity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEntity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartRun operation middleware
func (siw *ServerInterfaceWrapper) StartRun(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartRun(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRun operation middleware
func (siw *ServerInterfaceWrapper) GetRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id RunID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRun(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TailRunEvents operation middleware
func (siw *ServerInterfaceWrapper) TailRunEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id RunID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TailRunEvents(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetView operation middleware
func (siw *ServerInterfaceWrapper) GetView(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name ViewName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetView(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeclareView operation middleware
func (siw *ServerInterfaceWrapper) DeclareView(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name ViewName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeclareView(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResolveView operation middleware
func (siw *ServerInterfaceWrapper) ResolveView(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name ViewName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ResolveViewParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResolveView(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/entities/{id}", wrapper.GetEntity)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/runs", wrapper.StartRun)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/runs/{id}", wrapper.GetRun)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/runs/{id}/events", wrapper.TailRunEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/views/{name}", wrapper.GetView)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/views/{name}", wrapper.DeclareView)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/views/{name}/entities", wrapper.ResolveView)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFjdbts4Fn6VA+4CkwCy5aTFXrhXmTYddKfIBnbRvZgpEEY8tjiVSJU/do3AwD7EvsO8xzzKPsnikLIs",
	"xUzSTNK5imKR5+c7f9/RDSt03WiFylk2vWENN7xGhyb8N/Pq3Rt6kIpNWcNdyTKmeI1syqRgGTP4xUuD",
	"gk2d8ZgxW5RYc7rhNg2dss5ItWTbbcY+SlxfhLs3TKAtjGyc1CSY3gCJhSNXIlytJK6nef6rn0xeFPR7",
	"eMIrMLhAg6pAWEtXau8gKMTjMctSNoY/j7FyS4dto5XFAMCPXMzwi0fr6L9CK4cqPPKmqWTByYH8N0te",
	"3PTE/t3ggk3Z3/I9uHl8a/NzY7SJqoYofCgRTFQG0kLNq4U2NQq2zdiFdm+1V+KvsYJgE6Cvf8PCgdBo",
	"QWkH+FVaFyLZCiEd58pJtwmZY3SDxskInBQJeDMmBYYLP+MmHONCSFLMq8vB9YOL7Q/RJvrhs1RpFRW/",
	"xupJwrf9jPklJnpQd8v+TtenhH0RmDe68HUbrCFA2AF3b5jiqW3GFrzAWKLSYW0fuviWjvd848bwzYFr",
	"rRGd9KQjIVMO7K/RWr7EdKn3dewOpmRHKw9kU/7ZhheYjFZj9AoVV/H1fSBc7k9uM7bilU80H0r4YAeI",
	"NliwMHwZHo6iJODO8aJECw0a6KzL4I/fT8Ynx+MDn/cO7NQOzL4TikuDguoZE/nyxfOY1kPz/zn/1wUE",
	"HUC9kwth0FoUsJBYCai9dRDujknLA8hS83wwoH3nWqtSDl0OwjQ0+hLNiDtn5LV3CNbxuoH//ee/sC5l",
	"UcLMq3y+UQUaWBvtomPBxQzWJaoMFkbX7eG59qZAOCpKbhwa+OP3UwoJnFVrvrGAX3nhqg1ohcCVXaMZ",
	"/6piNHrg8pCE1G7piQnucORkmB0HINmg8F26+ayNdGh+bnsTKl8TYjY4Q4PIqx5Wt6/NKJMfQr+noX8v",
	"Ix9SYZh5dZhMC6mkLVGcPcLvOzq6dYT7oyRZx523fYAaVIJeBoRUfLK+KBAFitCeZBUeCsonekyhSLQh",
	"jWF89xGNlXFIdoZK5f7xcm+kVA6XaEJMtPm8qPQ6GenUiOhd6Hzs45OKzpzeJkO06rGl+5V3J1MKiFql",
	"G2w6mlhh4WK/v6+zktj57izB+whoE+2E7SX0bLjLnxlaXXnX6kuM1R0H+ZZBuZ+ww0kZU+ZbcEgGhHrj",
	"zpS7/Jj3wB72x7kzvnDeoIAdGiC446FJCqzkNRrusNoEYsYV4NeG2r7UCiqulp4vey1RaTVaal69grM3",
	"s9FkMnkBBsnI41Qv/DNEYz+3EjgSdRrKu4uAdVeehcPd/oV6mFroQ7TPqVhxxL3TdeDS0FTcUR7D2eW7",
	"aRg/JEwAhpOwNLwp4agxmkRLrTLYj5+T8elxBhRfmwFXgsYZaEP0wZkgfgyXJbc4moD1huCOYahkgcri",
	"vj7ZWUOsY3Q6nrCMeVOxKSuda+w0z9fr9ZiH12Ntlnl71+bv370+v5ifhzuEgXQVxoTizpE7vVKbssn4",
	"JJ7TDSreSDZlL8aT8QsWuUBAOt/lcX4jxZZ+WUbORuEI/lCHZD+hO9+xycEKdTqZPN/WMiTVd6wv8VRH",
	"58i/l5OXd8nujM27JSvsOL6uudlEzwJ9aMXS5gnS2UgabQhxM+AzQ9rZ36h/eY5N+tM2Y7nxKu7r2iaC",
	"0Y2VKBet+1GLzbOFoRO/HbY+snx7EP6TZ9PbqTyMeWGQOwzFFuM9eTjeveX+iSkSAAEeS30RGsauxP/d",
	"sgLgSy6VpVPd0AhRfLCsdnH8TjV1D6jkTuskHOGKroF1BnkNFimvaQQdP0d98b6uRNWkBO+P5PE71b4y",
	"AqZ5tLgH7dDDGTYVrQhhmaCQLaShZYluhape6KrSawuVXCEcXZx9mI+uefEZxfEYLnCFBpzxqgh5R4M5",
	"yPBVtcNIL4CrTfBMWjDIi5JfVwhH3Rh+f5K/Pz0ew7kSNjYWDlfx9giVuGqN0aqIS9DMqx+6EBSVtmjj",
	"7BgmzQcuq5lX59H/B3PH4VcXwRpF0cPkSXwju8VW0KzQjCyZGg2OYl4BuQxXxFymV1BJhQREiHWwbfzU",
	"1HlPkZnPz8FxWe0qL4IUAuG4/Tzqm/S01CLOZPMbatv3VuzHSAC/W8m2DSRZs/Hdc1Rk+Cp71JIFFBm8",
	"5q9HAouKEy+NHOiLRxM7wONQ7b4Fbz9lrPGJ6tz1z6iwpWXclWN4S/UaXsNJS7T2H4YFXG/gzFq5VHXo",
	"V9wg/CTdSKtqc/srwStwpbSASjRaqvDV1ZWowBBVkwXVtdPgVU96UJequTcRmC70zz91hzvXt0zevybj",
	"upQICdPRo8IbQ4W3Y5t/ZioPsrJFuM1M6oO71ejo2teNjZ+JojbQiii5WuJxnLT90s37S2KyhsOGudoF",
	"M8XgQuLvKVwla+lYn7XVUsna12x6ktiAP33nUPU25DuCFmZay2gtxnnn2vbRgSgdFLzGMCGf2lNaSDsl",
	"P9jbNjypiwRlYQ7Fm3Fbynkj89UJvf9/AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
