# ADR-0112 B3 — the AWS network module the opentofu-network provider runs. Mounted into the opentofu
# plugin pod at ${STRATT_TOFU_MODULE_ROOT}/aws-network (default /modules/aws-network); invoked as
# params.module = "aws-network".
#
# §7.3/§1.7 pin (ADR-0112 D4): required_providers below pins the aws provider VERSION; the committed
# `.terraform.lock.hcl` (provider HASH pins) is generated by `tofu init` at bring-up and committed —
# it cannot be hand-authored (the hashes must match the real provider). Until it ships, this module
# must reference NO unpinned remote module sources.
terraform {
  required_version = ">= 1.8.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.60"
    }
  }
  # The state backend is CORE-INJECTED (ADR-0105 statestore): the opentofu Actuator fills this empty
  # block via -backend-config from the resolved s3 handle. Provider-agnostic — never hardcode a bucket.
  backend "s3" {}
}
