package adopt

import (
	"context"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/dstout-devops/stratt/core/internal/awximport/awx"
	"github.com/dstout-devops/stratt/core/internal/awximport/awx/awxsim"
)

// fakeCatalog stands in for the projection graph: an identity present in the map is
// "observed" and maps to its native object id — exactly what the graph catalog resolves.
type fakeCatalog struct {
	native map[string]int
	source string
	live   []string // enabled foreign-side executions (schedule names) for the cutover guard
}

func (f fakeCatalog) Resolve(_ context.Context, _, identity string) (int, string, bool, error) {
	id, ok := f.native[identity]
	return id, f.source, ok, nil
}

func (f fakeCatalog) LiveExecutions(_ context.Context, _, _ string) ([]string, error) {
	return f.live, nil
}

// TestAdoptJobTemplateFromProjection drives the whole core loop: resolve from catalog →
// targeted deep-read (against awxsim) → transform → adopted-from lineage.
func TestAdoptJobTemplateFromProjection(t *testing.T) {
	sim := awxsim.New("")
	srv := httptest.NewServer(sim.Handler())
	defer srv.Close()
	sim.SetBase(srv.URL)

	reader := awx.New(awx.Config{Endpoint: srv.URL, Token: "t"})
	cat := fakeCatalog{native: map[string]int{"ctrl-a/10": 10}, source: "ctrl-a", live: []string{"Nightly Deploy"}}

	emit, err := Adopt(context.Background(), cat, reader, Request{Kind: KindTemplate, Identity: "ctrl-a/10"})
	if err != nil {
		t.Fatalf("adopt: %v", err)
	}

	// Job template 10 (Deploy Web) → a Workflow + its View (+ a CredentialRef + survey Contract).
	var wf, view string
	for path := range emit.Files {
		switch {
		case strings.HasPrefix(path, "workflows/"):
			wf = path
		case strings.HasPrefix(path, "views/"):
			view = path
		}
	}
	if wf == "" || view == "" {
		t.Fatalf("expected a workflow + a view; got %v", keys(emit.Files))
	}

	// Must-fix 2: the adopted Named Kind carries adopted-from lineage, not the retired banner.
	if !strings.HasPrefix(emit.Files[wf], "# adopted-from: ctrl-a ctrl-a/10 (native ansible.template/10)") {
		t.Fatalf("workflow missing adopted-from lineage; first line: %q", firstLine(emit.Files[wf]))
	}
	if strings.Contains(emit.Files[wf], "Generated by `stratt import") {
		t.Fatal("adopted file must not carry the retired import banner")
	}
	// The emitted Workflow carries STRUCTURED adoptedFrom (ADR-0087) — what the standing
	// cutover reconciler reads, not just the header comment.
	if !strings.Contains(emit.Files[wf], "adoptedFrom:") || !strings.Contains(emit.Files[wf], "ctrl-a/10") {
		t.Fatalf("workflow missing structured adoptedFrom block:\n%s", emit.Files[wf])
	}
	if !strings.HasPrefix(emit.Report, "# adopted-from: ctrl-a ctrl-a/10") {
		t.Fatalf("report missing adopted-from lineage; first line: %q", firstLine(emit.Report))
	}

	// The cutover guard (ADR-0086 §4): the report names the still-enabled AWX schedule to
	// disable so the object never runs in both places.
	if !strings.Contains(emit.Report, "Cutover — avoid double-execution") ||
		!strings.Contains(emit.Report, "Nightly Deploy") {
		t.Fatalf("report missing the cutover guard / live schedule:\n%s", emit.Report)
	}
}

// TestAdoptRejectsUnobserved: an identity not in the catalog fails loud — nothing to adopt.
func TestAdoptRejectsUnobserved(t *testing.T) {
	reader := awx.New(awx.Config{Endpoint: "http://unused", Token: "t"})
	cat := fakeCatalog{native: map[string]int{}, source: "ctrl-a"}
	_, err := Adopt(context.Background(), cat, reader, Request{Kind: KindTemplate, Identity: "ctrl-a/999"})
	if err == nil || !strings.Contains(err.Error(), "not in the projection catalog") {
		t.Fatalf("expected not-in-catalog error, got %v", err)
	}
}

// TestAdoptRejectsUnsupportedKind: adopt materializes only the kinds it can transform.
func TestAdoptRejectsUnsupportedKind(t *testing.T) {
	cat := fakeCatalog{native: map[string]int{"ctrl-a/1": 1}, source: "ctrl-a"}
	_, err := Adopt(context.Background(), cat, awx.New(awx.Config{}), Request{Kind: "ansible.org", Identity: "ctrl-a/1"})
	if err == nil || !strings.Contains(err.Error(), "unsupported kind") {
		t.Fatalf("expected unsupported-kind error, got %v", err)
	}
}

func keys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}
