package materialize

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	awx "github.com/dstout-devops/stratt/plugins/awx/controller"
)

// ErrGoneAtRead: the object vanished between the catalog resolve (core-side) and the
// deep-read (here) — never emit stale CaC (§1.8).
var ErrGoneAtRead = errors.New("gone at read-time")

// Reader is the targeted, read-only deep-reader for one object's full definition (model (b),
// ADR-0086). *controller.Client satisfies it; a fake satisfies it in tests.
type Reader interface {
	ReadJobTemplate(ctx context.Context, nativeID int) (*awx.Snapshot, error)
}

// Args are the core-resolved coordinates the transform needs — the adopt/materialize Action's
// input (ADR-0088/0089). They carry NO credential and NO graph handle: `kind`/`identity` name
// the object, `nativeId` keys the deep-read, `source` stamps the lineage, and `live` is the
// pre-resolved cutover-guard set (the plugin never touches the graph).
type Args struct {
	Kind     string
	Identity string
	NativeID int
	Source   string
	Live     []string
}

// Materialize is the plugin-side transform (ADR-0089): given a Reader (an AWX Controller
// client built from the pod-resolved token) and the core-resolved coordinates, it does the
// targeted read-only deep-read (definition-truth; fail-loud if gone at read-time), runs the
// Bundle transform, stamps adopted-from lineage, and appends the cutover guard from the
// pre-resolved Live set. It touches NO graph — its only inputs are the Reader and Args. This
// is the AWX-specific breadth that lives in the plugin; core owns only the tool-blind Resolve.
func Materialize(ctx context.Context, reader Reader, args Args) (*Emit, error) {
	// The LIVE targeted read is definition-truth, never the possibly-stale catalog.
	snap, err := reader.ReadJobTemplate(ctx, args.NativeID)
	if err != nil {
		return nil, fmt.Errorf("adopt: deep-read %s native %d: %w", args.Kind, args.NativeID, err)
	}
	if len(snap.JobTemplates) == 0 {
		return nil, fmt.Errorf("adopt: %s %q (native %d) is %w — not adopting stale state", args.Kind, args.Identity, args.NativeID, ErrGoneAtRead)
	}

	emit, err := Bundle(snap, Options{
		// Structured adopt lineage on the emitted Workflow (ADR-0087) — what the standing
		// cutover reconciler reads. Lives on the Named Kind's Git lineage, never a projection facet.
		AdoptedFrom: &AdoptLineage{Kind: args.Kind, Identity: args.Identity, Source: args.Source},
	})
	if err != nil {
		return nil, err
	}
	stampLineage(emit, args, time.Now().UTC())
	cutoverGuard(emit, args.Live)
	return emit, nil
}

// cutoverGuard appends the ADR-0086 §4 anti-double-execution section to the report: once the
// bundle is merged, Stratt owns execution, so any still-live foreign-side execution (an
// enabled AWX schedule) must be disabled or the object runs in BOTH places. The live set was
// pre-resolved core-side by adopt.Resolve (§1.2 graph read) and handed in — making the cutover
// explicit and diagnosable (§1.8), never a silent dual truth. A nil set degrades to a "verify
// manually" note, never a failed adopt.
func cutoverGuard(emit *Emit, live []string) {
	var b strings.Builder
	b.WriteString("\n## Cutover — avoid double-execution (ADR-0086 §4)\n")
	b.WriteString("On merge, Stratt owns execution of this object. Disable its foreign-side execution so it does not run in both places.\n")
	switch len(live) {
	case 0:
		b.WriteString("\nNo enabled AWX schedules were resolved for it. Still verify no manual or other launch remains.\n")
	default:
		b.WriteString("\nDISABLE these still-enabled AWX schedules (they currently launch this object):\n")
		for _, name := range live {
			b.WriteString("  - " + name + "\n")
		}
	}
	emit.Report += b.String()
}

// stampLineage records the adopted-from linkage back to the source object (§1.8 descent /
// audit) as the leading provenance comment of each emitted Named-Kind file, replacing the
// retired "generated by import" banner (ADR-0086). The comment is the durable lineage today
// and rides through desiredstate's KnownFields round-trip untouched. The lineage is also
// prepended to the report. JSON contracts (no comment syntax) carry lineage via their
// referencing Workflow + the report, not a header line.
func stampLineage(emit *Emit, args Args, at time.Time) {
	banner := fmt.Sprintf("# adopted-from: %s %s (native %s/%d) at %s (ADR-0086) — review before merge.\n",
		args.Source, args.Identity, args.Kind, args.NativeID, at.Format(time.RFC3339))
	for path, content := range emit.Files {
		if !strings.HasSuffix(path, ".yaml") {
			continue
		}
		if strings.HasPrefix(content, "# Generated by") {
			if nl := strings.IndexByte(content, '\n'); nl >= 0 {
				content = content[nl+1:]
			}
		}
		emit.Files[path] = banner + content
	}
	emit.Report = banner + emit.Report
}
