package awximport

import yaml "go.yaml.in/yaml/v3"

// These structs mirror the desiredstate parse structs' yaml tags exactly, so a
// marshalled bundle round-trips through desiredstate.ParseDir (which decodes
// with KnownFields(true)). omitempty keeps gate-vs-actuation Steps clean and
// avoids emitting empty known fields.

type yView struct {
	Name     string    `yaml:"name"`
	Selector ySelector `yaml:"selector"`
}

type ySelector struct {
	Kinds  []string          `yaml:"kinds,omitempty"`
	Labels map[string]string `yaml:"labels,omitempty"`
	Facets []yFacet          `yaml:"facets,omitempty"`
}

type yFacet struct {
	Namespace string `yaml:"namespace"`
	Path      string `yaml:"path,omitempty"`
	Equals    any    `yaml:"equals"`
}

type yWorkflow struct {
	Name        string        `yaml:"name"`
	AdoptedFrom *yAdoptedFrom `yaml:"adoptedFrom,omitempty"`
	Steps       []yStep       `yaml:"steps"`
}

// yAdoptedFrom is the adopt-lineage block on an adopted Workflow (ADR-0087); nil (omitted)
// for the legacy full-estate importer, which has no per-object adopt lineage.
type yAdoptedFrom struct {
	Kind     string `yaml:"kind"`
	Identity string `yaml:"identity"`
	Source   string `yaml:"source"`
}

// adoptBlock renders the optional adopt lineage for an emitted Workflow.
func adoptBlock(l *AdoptLineage) *yAdoptedFrom {
	if l == nil {
		return nil
	}
	return &yAdoptedFrom{Kind: l.Kind, Identity: l.Identity, Source: l.Source}
}

type yStep struct {
	Name           string         `yaml:"name"`
	Needs          []string       `yaml:"needs,omitempty"`
	When           string         `yaml:"when,omitempty"`
	Gate           *yGate         `yaml:"gate,omitempty"`
	ViewName       string         `yaml:"viewName,omitempty"`
	Actuator       string         `yaml:"actuator,omitempty"`
	Params         map[string]any `yaml:"params,omitempty"`
	CredentialRefs []string       `yaml:"credentialRefs,omitempty"`
}

type yGate struct {
	Approvers      yApprovers `yaml:"approvers"`
	TimeoutSeconds int        `yaml:"timeoutSeconds,omitempty"`
}

type yApprovers struct {
	Principals []string `yaml:"principals,omitempty"`
	Teams      []string `yaml:"teams,omitempty"`
}

type yCredRef struct {
	Name      string         `yaml:"name"`
	OwnerTeam string         `yaml:"ownerTeam"`
	Backend   string         `yaml:"backend"`
	Locator   map[string]any `yaml:"locator"`
	Injection []yInjection   `yaml:"injection"`
}

type yInjection struct {
	Key  string `yaml:"key"`
	As   string `yaml:"as"`
	Name string `yaml:"name"`
}

// marshalYAML renders a bundle document with a leading provenance comment.
func marshalYAML(v any) (string, error) {
	b, err := yaml.Marshal(v)
	if err != nil {
		return "", err
	}
	return "# Generated by `stratt import awx` (ADR-0025). Review before apply.\n" + string(b), nil
}
