package awximport

import (
	"fmt"
	"sort"
	"strings"

	"github.com/dstout-devops/stratt/core/internal/connectors/awx"
)

// report accumulates per-mapping notes and blocking items. Blocking items must
// be resolved by the operator before `stratt apply` — the migration never
// hides what it could not translate faithfully (§1.8).
type report struct {
	notes    []string // informational per-mapping lines
	blocking []string // must-resolve-before-apply items
}

func newReport() *report { return &report{} }

func (r *report) note(format string, a ...any) { r.notes = append(r.notes, fmt.Sprintf(format, a...)) }
func (r *report) block(format string, a ...any) {
	r.blocking = append(r.blocking, fmt.Sprintf(format, a...))
}

// render builds migration-report.md in Stratt vocabulary. AWX terms appear only
// as "was:" provenance, never as Stratt identifiers.
func (r *report) render(snap *awx.Snapshot) string {
	var b strings.Builder
	b.WriteString("# AWX migration report\n\n")
	b.WriteString("Generated by `stratt import awx` (ADR-0025). Import target frozen at AWX 24.6.1.\n\n")

	b.WriteString("## Summary\n\n")
	fmt.Fprintf(&b, "- Views (from inventories): %d\n", len(snap.Inventories))
	fmt.Fprintf(&b, "- Workflows (from job templates): %d\n", len(snap.JobTemplates))
	fmt.Fprintf(&b, "- Workflows (from workflow job templates): %d\n", len(snap.WorkflowJTs))
	fmt.Fprintf(&b, "- CredentialRefs (from credentials): %d\n", len(snap.Credentials))
	fmt.Fprintf(&b, "- Input Contracts (from surveys): %d\n\n", len(snap.Surveys))

	if len(r.blocking) > 0 {
		b.WriteString("## Blocking items — resolve before `stratt apply`\n\n")
		for _, item := range dedupSorted(r.blocking) {
			fmt.Fprintf(&b, "- [ ] %s\n", item)
		}
		b.WriteByte('\n')
	}

	if len(r.notes) > 0 {
		b.WriteString("## Mapping notes\n\n")
		for _, n := range r.notes {
			fmt.Fprintf(&b, "- %s\n", n)
		}
		b.WriteByte('\n')
	}

	b.WriteString("## Next steps\n\n")
	b.WriteString("1. Resolve every blocking item above.\n")
	b.WriteString("2. Review the emitted `views/`, `workflows/`, and `credential-refs/`.\n")
	b.WriteString("3. Re-broker each CredentialRef's secret into its backend (material is never imported).\n")
	b.WriteString("4. Run `stratt plan -d <this-bundle>` to preview the compiled effect.\n")
	return b.String()
}

func dedupSorted(in []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	sort.Strings(out)
	return out
}
