package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/dstout-devops/stratt/core/internal/packs"
)

// runPack handles `stratt pack …` (ADR-0033): list, show, and install in-tree
// content packs. A pack is a curated grouping of existing Named Kinds — a
// collector Trigger that projects os.hardening.* Facets and facet-observation
// Baselines that assert the expected values. Install materializes the pack into
// the operator's desired-state Git (charter §1.2 stays operator-owned); it
// touches no registry and no platform API.
//
//	stratt pack list
//	stratt pack show <name>
//	stratt pack install <name> --view V [--principal P] [--cred R] -o <cac-dir> [--force]
func runPack(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: stratt pack <list|show|install> …")
	}
	sub := args[0]
	switch sub {
	case "list":
		return packList()
	case "show":
		if len(args) < 2 {
			return fmt.Errorf("usage: stratt pack show <name>")
		}
		return packShow(args[1])
	case "install":
		return packInstall(args[1:])
	default:
		return fmt.Errorf("unknown pack subcommand %q (list|show|install)", sub)
	}
}

func packList() error {
	list, err := packs.List()
	if err != nil {
		return err
	}
	for _, m := range list {
		fmt.Printf("%-10s v%d  %s\n", m.Name, m.Version, m.Title)
	}
	return nil
}

func packShow(name string) error {
	p, err := packs.Load(name)
	if err != nil {
		return err
	}
	fmt.Printf("%s v%d — %s\n", p.Name, p.Version, p.Title)
	fmt.Printf("content-hash: sha256:%s\n\n", p.ContentHash)
	if p.Description != "" {
		fmt.Printf("%s\n\n", strings.TrimSpace(p.Description))
	}
	fmt.Println("required facets (pinned in contracts/facets):")
	for _, f := range p.RequiredFacets {
		fmt.Printf("  - %s\n", f)
	}
	fmt.Println("parameters:")
	for _, param := range p.Parameters {
		req := ""
		if param.Required {
			req = " (required)"
		} else if param.Default != "" {
			req = fmt.Sprintf(" (default %q)", param.Default)
		}
		fmt.Printf("  - %s%s: %s\n", param.Name, req, param.Description)
	}
	fmt.Println("files:")
	rels := make([]string, 0, len(p.Files))
	for rel := range p.Files {
		rels = append(rels, rel)
	}
	sort.Strings(rels)
	for _, rel := range rels {
		fmt.Printf("  - %s\n", rel)
	}
	return nil
}

type credList []string

func (c *credList) String() string { return strings.Join(*c, ",") }
func (c *credList) Set(v string) error {
	*c = append(*c, v)
	return nil
}

func packInstall(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: stratt pack install <name> --view V -o <cac-dir>")
	}
	name := args[0]
	fs := flag.NewFlagSet("pack install", flag.ExitOnError)
	view := fs.String("view", "", "the View selecting hosts to assess (required)")
	principal := fs.String("principal", "", "Principal the collector Run executes as (default from pack)")
	out := fs.String("o", "", "declarations directory to write into (required)")
	force := fs.Bool("force", false, "overwrite existing files")
	var creds credList
	fs.Var(&creds, "cred", "CredentialRef for the collector host connection (repeatable)")
	_ = fs.Parse(args[1:])

	if *view == "" || *out == "" {
		return fmt.Errorf("usage: stratt pack install %s --view V -o <cac-dir>", name)
	}

	p, err := packs.Load(name)
	if err != nil {
		return err
	}
	params := map[string]string{"VIEW": *view}
	if *principal != "" {
		params["PRINCIPAL"] = *principal
	}
	// CRED substitutes as a YAML array literal so an empty install yields
	// `credentialRefs: []` and a set one `credentialRefs: ["ref", …]`.
	if len(creds) > 0 {
		quoted := make([]string, len(creds))
		for i, c := range creds {
			quoted[i] = fmt.Sprintf("%q", c)
		}
		params["CRED"] = "[" + strings.Join(quoted, ", ") + "]"
	}

	files, err := p.Materialize(params)
	if err != nil {
		return err
	}

	header := fmt.Sprintf("# Generated by `stratt pack install %s` (pack %s v%d, sha256:%s).\n"+
		"# This is your desired state now (charter §1.2) — commit it to Git and edit it here;\n"+
		"# re-run install to take a newer pack version as a reviewable diff.\n",
		name, p.Name, p.Version, p.ContentHash[:12])

	rels := make([]string, 0, len(files))
	for rel := range files {
		rels = append(rels, rel)
	}
	sort.Strings(rels)
	for _, rel := range rels {
		dst := filepath.Join(*out, filepath.FromSlash(rel))
		if !*force {
			if _, err := os.Stat(dst); err == nil {
				return fmt.Errorf("refusing to overwrite %s (use --force)", dst)
			}
		}
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(dst, append([]byte(header), files[rel]...), 0o644); err != nil {
			return err
		}
		fmt.Printf("+ %s\n", dst)
	}
	fmt.Printf("\nInstalled %s v%d (%d files) into %s. Review, then `stratt apply -d %s`.\n",
		p.Name, p.Version, len(files), *out, *out)
	return nil
}
