services:
  devcontainer:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE: debian
        VARIANT: trixie
        PYTHON_VERSION: 3.14
    environment:
      PYTHONUNBUFFERED: '1'
      UV_SYSTEM_CERTS: 'true'
      UV_PROJECT: /opt/venv
    volumes:
      - ..:/workspaces/${WORKSPACE_NAME:-workspace}:cached
    command: sleep infinity
networks:
  default:
    ipam:
      config:
        - subnet: 172.200.0.0/16 