#!/bin/sh
# Render the config + the initial zone from the environment, then exec named.
#
# Rendered at START rather than baked at BUILD because the TSIG secret is generated by
# the harness (task dev:dns:key) and must never be committed or layered into an image
# (§2.5). The zone is (re)written on every start, so `dev:down && dev:up` gives a clean
# zone — which the live proof depends on: a leftover record from a previous run would
# satisfy the assertion instantly and prove nothing about THIS run.
set -eu

ZONE="${STRATT_DNS_ZONE:-estate.stratt.test}"
KEY_NAME="${STRATT_DNS_TSIG_NAME:-stratt-dev}"
KEY_SECRET="${STRATT_DNS_TSIG_SECRET:-}"

if [ -z "$KEY_SECRET" ]; then
    echo "dev-dns: STRATT_DNS_TSIG_SECRET is empty — refusing to serve a zone that accepts unsigned updates" >&2
    echo "dev-dns: generate one with 'task dev:dns:key'" >&2
    exit 1
fi

render() {
    sed -e "s|__ZONE__|${ZONE}|g" \
        -e "s|__TSIG_NAME__|${KEY_NAME}|g" \
        -e "s|__TSIG_SECRET__|${KEY_SECRET}|g" "$1"
}

render /etc/bind/named.conf.tmpl >/etc/bind/named.conf
render /etc/bind/zone.tmpl >"/var/bind/${ZONE}.zone"
rm -f "/var/bind/${ZONE}.zone.jnl"
chown -R named:named /var/bind
# named drops to the `named` user before it reads the config, so the key it carries has
# to be readable by that user and nobody else (§2.5) — 640 root:root would fail closed
# with "permission denied", which is the right instinct and the wrong owner.
chown named:named /etc/bind/named.conf
chmod 640 /etc/bind/named.conf

echo "dev-dns: serving ${ZONE} authoritatively; updates and transfers require TSIG key ${KEY_NAME}"
# -g: foreground, log to stderr — the container's logs ARE named's logs (§1.8).
exec named -u named -c /etc/bind/named.conf -g
