// Package stratt.plugin.v1 is the SOVEREIGN PLUGIN PORT — the one versioned,
// hash-pinned wire contract every plugin plugs into (ADR-0046). It is the "USB
// bus" of Stratt: one bus, typed plugin classes. The core owns this contract;
// gRPC is merely the transport beneath it (charter §1.5). A plugin is a
// Connector, an Actuator, or (later, Phase D) a capability-backend — never a
// new Named Kind; `plugin` is the umbrella word (ADR-0046, vocabulary-linter
// 2026-07-16).
//
// THE LOAD-BEARING SHAPE: opaque `Payload` + typed governance `Envelope`.
// The core reads the Envelope and governs on it (routes, authorizes, versions,
// stamps provenance, audits); it hands the Payload to the plugin UNTOUCHED and
// never parses it. The day the core parses a Payload to make a decision,
// content-blindness is dead. This shape can never move.
//
// The message is `Payload`, NEVER `Resource` — `resource` is a §2-banned
// core-model identifier.
//
// ── The 13 t=0 invariants (ADR-0046 §Decision.3) and where each lives ──
//  1. Opaque payload / typed envelope ............ Payload.bytes + Envelope
//  2. Content-blind discovery .................... PluginService.GetManifest
//  3. Identity bound to an authenticated channel . Envelope.principal + transport note
//  4. Streaming + persistent connections ......... stream RPCs (Observe/Apply/…)
//  5. Envelope-vs-payload version decoupling ..... protocol_version ≠ ContractRef.sha256
//  6. Provenance core-stamped, not plugin-claimed  NO provenance field exists (by design)
//  7. Idempotency-by-contract + checkpoint/resume  Envelope.idempotency_key + ApplyRequest.resume_token
//  8. Cursor-delta Observe + content-hash ........ ObserveRequest.cursor + Envelope.content_hash
//  9. Observe tree at true bands + atomic Apply .. Item.children + Apply on the root
// 10. One bus + typed plugin classes ............. this single service + Manifest.class
// 11. Facet-ownership + coordinate-scope pre-write  core-side check on every returned Envelope (note)
// 12. Typed, core-legible diagnostic descent ..... TaskEvent is typed, NOT an opaque blob
// 13. SDK stays permissively licensed ............ out-of-band (the shipped SDK links no copyleft)
//
// PHASE A scope: the domain PluginService below. The capability classes
// (StateStore/EventBus/SecretBroker/DurableExec/ArtifactStore) are siblings on
// the same bus but are Phase D — reserved, not defined here.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: stratt/plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PluginClass names the USB-style class of a plugin. It maps to Stratt's
// existing Named Kinds — no new Kind is minted (ADR-0046 / vocabulary-linter).
type PluginClass int32

const (
	PluginClass_PLUGIN_CLASS_UNSPECIFIED PluginClass = 0
	PluginClass_PLUGIN_CLASS_SYNCER      PluginClass = 1 // Connector/Syncer  — Observe (+ write-back Facets)
	PluginClass_PLUGIN_CLASS_ACTUATOR    PluginClass = 2 // Actuator          — Plan/Apply/Destroy
	PluginClass_PLUGIN_CLASS_ACTION      PluginClass = 3 // Connector/Action  — Invoke (targetless)
	PluginClass_PLUGIN_CLASS_EMITTER     PluginClass = 4 // Connector/Emitter — Subscribe (push)
)

// Enum value maps for PluginClass.
var (
	PluginClass_name = map[int32]string{
		0: "PLUGIN_CLASS_UNSPECIFIED",
		1: "PLUGIN_CLASS_SYNCER",
		2: "PLUGIN_CLASS_ACTUATOR",
		3: "PLUGIN_CLASS_ACTION",
		4: "PLUGIN_CLASS_EMITTER",
	}
	PluginClass_value = map[string]int32{
		"PLUGIN_CLASS_UNSPECIFIED": 0,
		"PLUGIN_CLASS_SYNCER":      1,
		"PLUGIN_CLASS_ACTUATOR":    2,
		"PLUGIN_CLASS_ACTION":      3,
		"PLUGIN_CLASS_EMITTER":     4,
	}
)

func (x PluginClass) Enum() *PluginClass {
	p := new(PluginClass)
	*p = x
	return p
}

func (x PluginClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginClass) Descriptor() protoreflect.EnumDescriptor {
	return file_stratt_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (PluginClass) Type() protoreflect.EnumType {
	return &file_stratt_plugin_v1_plugin_proto_enumTypes[0]
}

func (x PluginClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginClass.Descriptor instead.
func (PluginClass) EnumDescriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

// Verb — the capability a plugin advertises. The core calls only advertised
// verbs (capability negotiation, invariant #2). A plugin may span verbs.
type Verb int32

const (
	Verb_VERB_UNSPECIFIED Verb = 0
	Verb_VERB_OBSERVE     Verb = 1
	Verb_VERB_PLAN        Verb = 2
	Verb_VERB_APPLY       Verb = 3
	Verb_VERB_DESTROY     Verb = 4
	Verb_VERB_INVOKE      Verb = 5
	Verb_VERB_EMIT        Verb = 6
)

// Enum value maps for Verb.
var (
	Verb_name = map[int32]string{
		0: "VERB_UNSPECIFIED",
		1: "VERB_OBSERVE",
		2: "VERB_PLAN",
		3: "VERB_APPLY",
		4: "VERB_DESTROY",
		5: "VERB_INVOKE",
		6: "VERB_EMIT",
	}
	Verb_value = map[string]int32{
		"VERB_UNSPECIFIED": 0,
		"VERB_OBSERVE":     1,
		"VERB_PLAN":        2,
		"VERB_APPLY":       3,
		"VERB_DESTROY":     4,
		"VERB_INVOKE":      5,
		"VERB_EMIT":        6,
	}
)

func (x Verb) Enum() *Verb {
	p := new(Verb)
	*p = x
	return p
}

func (x Verb) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verb) Descriptor() protoreflect.EnumDescriptor {
	return file_stratt_plugin_v1_plugin_proto_enumTypes[1].Descriptor()
}

func (Verb) Type() protoreflect.EnumType {
	return &file_stratt_plugin_v1_plugin_proto_enumTypes[1]
}

func (x Verb) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verb.Descriptor instead.
func (Verb) EnumDescriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

type HealthResponse_Serving int32

const (
	HealthResponse_SERVING_UNSPECIFIED HealthResponse_Serving = 0
	HealthResponse_SERVING_UP          HealthResponse_Serving = 1
	HealthResponse_SERVING_DOWN        HealthResponse_Serving = 2
)

// Enum value maps for HealthResponse_Serving.
var (
	HealthResponse_Serving_name = map[int32]string{
		0: "SERVING_UNSPECIFIED",
		1: "SERVING_UP",
		2: "SERVING_DOWN",
	}
	HealthResponse_Serving_value = map[string]int32{
		"SERVING_UNSPECIFIED": 0,
		"SERVING_UP":          1,
		"SERVING_DOWN":        2,
	}
)

func (x HealthResponse_Serving) Enum() *HealthResponse_Serving {
	p := new(HealthResponse_Serving)
	*p = x
	return p
}

func (x HealthResponse_Serving) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Serving) Descriptor() protoreflect.EnumDescriptor {
	return file_stratt_plugin_v1_plugin_proto_enumTypes[2].Descriptor()
}

func (HealthResponse_Serving) Type() protoreflect.EnumType {
	return &file_stratt_plugin_v1_plugin_proto_enumTypes[2]
}

func (x HealthResponse_Serving) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Serving.Descriptor instead.
func (HealthResponse_Serving) EnumDescriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{12, 0}
}

type TaskEvent_Level int32

const (
	TaskEvent_LEVEL_UNSPECIFIED TaskEvent_Level = 0
	TaskEvent_LEVEL_DEBUG       TaskEvent_Level = 1
	TaskEvent_LEVEL_INFO        TaskEvent_Level = 2
	TaskEvent_LEVEL_WARN        TaskEvent_Level = 3
	TaskEvent_LEVEL_ERROR       TaskEvent_Level = 4
)

// Enum value maps for TaskEvent_Level.
var (
	TaskEvent_Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_DEBUG",
		2: "LEVEL_INFO",
		3: "LEVEL_WARN",
		4: "LEVEL_ERROR",
	}
	TaskEvent_Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_DEBUG":       1,
		"LEVEL_INFO":        2,
		"LEVEL_WARN":        3,
		"LEVEL_ERROR":       4,
	}
)

func (x TaskEvent_Level) Enum() *TaskEvent_Level {
	p := new(TaskEvent_Level)
	*p = x
	return p
}

func (x TaskEvent_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskEvent_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_stratt_plugin_v1_plugin_proto_enumTypes[3].Descriptor()
}

func (TaskEvent_Level) Type() protoreflect.EnumType {
	return &file_stratt_plugin_v1_plugin_proto_enumTypes[3]
}

func (x TaskEvent_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskEvent_Level.Descriptor instead.
func (TaskEvent_Level) EnumDescriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{23, 0}
}

// Envelope is the TYPED half the core reads and governs on. Every field here is
// a governance fact, never domain content. Invariant #1.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Where this lives — routing, authz scope, blast-radius (invariant #10 class
	// aside, this is the coordinate half). `cell`/`kind` are total; `band`/`beam`
	// are OPTIONAL, sparse, platform-computed (ADR-0046 discipline (c)); a plugin
	// that does not compute them leaves them empty and the core does not infer.
	Coordinates *Coordinates `protobuf:"bytes,1,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	// WHICH pinned schema this Payload claims to conform to — a hash-pinned
	// pointer, checked for conformance, NEVER read for content (invariant #2/#5).
	Contract *ContractRef `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	// The asserted acting identity. The core resolved it at its one seam and the
	// plugin trusts it ONLY because the call provably arrived over the
	// authenticated core→plugin channel (mTLS / per-plugin token). A principal on
	// an unauthenticated surface is never trusted — invariant #3, the direct
	// lesson of the cross-Cell auth hardening (ADR-0044 slice 4 / this session).
	Principal *Principal `protobuf:"bytes,3,opt,name=principal,proto3" json:"principal,omitempty"`
	// POINTERS to credentials (§2.5) — names only, never material. The plugin
	// resolves them against ITS OWN broker at point of use; material never
	// crosses the core or a coordinate boundary.
	Creds []*CredentialRef `protobuf:"bytes,4,rep,name=creds,proto3" json:"creds,omitempty"`
	// Idempotency key — the same key + same Payload must converge, never
	// double-apply (invariant #7).
	IdempotencyKey string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Run / correlation id — the §1.8 descent + audit thread.
	CorrelationId string `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Plugin-COMPUTED content hash of the Payload — lets the core detect change
	// WITHOUT reading content, at scale (invariant #8). Content-blind change
	// detection: the core compares hashes, never diffs payloads.
	ContentHash   string `protobuf:"bytes,7,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetCoordinates() *Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *Envelope) GetContract() *ContractRef {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *Envelope) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *Envelope) GetCreds() []*CredentialRef {
	if x != nil {
		return x.Creds
	}
	return nil
}

func (x *Envelope) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Envelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Envelope) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

// Payload is the OPAQUE half — the plugin's domain content. The core never
// parses these bytes. Invariant #1. (Named `Payload`, never `Resource`.)
type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         []byte                 `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *Payload) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

// Item is the OPAQUE Apply-path aggregate: a governance Envelope + opaque
// Payload, plus an OPTIONAL band-honest decomposition into children at their
// true bands (invariant #9). Apply is always issued on the ROOT Item for
// atomicity — the tree is for descent honesty, not partial apply. (The Syncer
// write-back path uses the core-legible ObservedEntity below, not this.)
type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Payload       *Payload               `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Children      []*Item                `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *Item) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Item) GetChildren() []*Item {
	if x != nil {
		return x.Children
	}
	return nil
}

// Coordinates — total residency (`cell`, `kind`) + optional computed residency
// (`band`, `beam`). See ADR-0046 discipline (c): coordinates place, they do not
// classify; band/beam are sparse and platform-computed, never a hand-authored
// precondition.
type Coordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cell          string                 `protobuf:"bytes,1,opt,name=cell,proto3" json:"cell,omitempty"` // region residency (ADR-0044). "" == the LocalCell.
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // Entity kind — total, semantically-empty coordinate.
	Band          string                 `protobuf:"bytes,3,opt,name=band,proto3" json:"band,omitempty"` // OPTIONAL computed stack band (Seven-Spectra S1..S7). "" if uncomputed.
	Beam          string                 `protobuf:"bytes,4,opt,name=beam,proto3" json:"beam,omitempty"` // OPTIONAL computed service beam. "" if uncomputed.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Coordinates) GetCell() string {
	if x != nil {
		return x.Cell
	}
	return ""
}

func (x *Coordinates) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Coordinates) GetBand() string {
	if x != nil {
		return x.Band
	}
	return ""
}

func (x *Coordinates) GetBeam() string {
	if x != nil {
		return x.Beam
	}
	return ""
}

// ContractRef pins a Facet/Payload schema by id + content hash. The core checks
// CONFORMANCE against the pinned, hash-verified schema (invariant #5, §1.5 —
// "schema drift is blocking, never silently absorbed"); it never reads the
// schema to interpret content.
type ContractRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"` // e.g. "vcenter.vm.v1"
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`                     // hex content hash of the pinned schema document
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractRef) Reset() {
	*x = ContractRef{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractRef) ProtoMessage() {}

func (x *ContractRef) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractRef.ProtoReflect.Descriptor instead.
func (*ContractRef) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ContractRef) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *ContractRef) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// Principal — the asserted acting identity (id + kind). Kind is the graph's
// existing string kind (e.g. "agent", "user", "service"), not a new enum, to
// stay byte-consistent with authz/provenance. Trust derives from the
// authenticated channel (invariant #3), not from these fields alone.
type Principal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *Principal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Principal) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// CredentialRef — a NAME only (§2.5). Never carries secret material.
type CredentialRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialRef) Reset() {
	*x = CredentialRef{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialRef) ProtoMessage() {}

func (x *CredentialRef) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialRef.ProtoReflect.Descriptor instead.
func (*CredentialRef) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *CredentialRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

// ContractDecl — a schema this plugin OWNS (single-writer per §2.1). The BAND
// lets one plugin honestly span bands. id + sha256 are hash-pinned (invariant
// #5). The core enforces §2.1 ownership from the channel identity before any
// write (invariant #11).
type ContractDecl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Band          string                 `protobuf:"bytes,3,opt,name=band,proto3" json:"band,omitempty"` // the band this contract's data lives at ("" if band-agnostic)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractDecl) Reset() {
	*x = ContractDecl{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractDecl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractDecl) ProtoMessage() {}

func (x *ContractDecl) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractDecl.ProtoReflect.Descriptor instead.
func (*ContractDecl) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ContractDecl) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *ContractDecl) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ContractDecl) GetBand() string {
	if x != nil {
		return x.Band
	}
	return ""
}

type Manifest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PluginId        string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`                      // stable plugin identity (NOT "device_id")
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // this port's wire version — decoupled from ContractDecl.sha256 (invariant #5)
	Class           PluginClass            `protobuf:"varint,3,opt,name=class,proto3,enum=stratt.plugin.v1.PluginClass" json:"class,omitempty"`
	Verbs           []Verb                 `protobuf:"varint,4,rep,packed,name=verbs,proto3,enum=stratt.plugin.v1.Verb" json:"verbs,omitempty"` // advertised capabilities
	Contracts       []*ContractDecl        `protobuf:"bytes,5,rep,name=contracts,proto3" json:"contracts,omitempty"`                            // facet namespaces it REQUESTS to own (advertisement, not grant)
	// Identity schemes this Source tombstones by (the full-sync seen-set is
	// accumulated per scheme; ADR-0042). REQUESTED — the core honors these only
	// where the operator grant allows, and the tier/grant gate applies (finding #4).
	TombstoneSchemes []string `protobuf:"bytes,6,rep,name=tombstone_schemes,json=tombstoneSchemes,proto3" json:"tombstone_schemes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *Manifest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *Manifest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Manifest) GetClass() PluginClass {
	if x != nil {
		return x.Class
	}
	return PluginClass_PLUGIN_CLASS_UNSPECIFIED
}

func (x *Manifest) GetVerbs() []Verb {
	if x != nil {
		return x.Verbs
	}
	return nil
}

func (x *Manifest) GetContracts() []*ContractDecl {
	if x != nil {
		return x.Contracts
	}
	return nil
}

func (x *Manifest) GetTombstoneSchemes() []string {
	if x != nil {
		return x.TombstoneSchemes
	}
	return nil
}

// GetManifestResponse wraps the Manifest so the RPC has a dedicated,
// independently-evolvable response type (buf STANDARD) while Manifest stays the
// reusable domain value.
type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *Manifest              `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *GetManifestResponse) GetManifest() *Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

type HealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          HealthResponse_Serving `protobuf:"varint,1,opt,name=status,proto3,enum=stratt.plugin.v1.HealthResponse_Serving" json:"status,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetStatus() HealthResponse_Serving {
	if x != nil {
		return x.Status
	}
	return HealthResponse_SERVING_UNSPECIFIED
}

func (x *HealthResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

// ObserveRequest — cursor-delta enumeration (invariant #8). An empty cursor is
// a full sync; a returned next_cursor resumes the delta. The core NEVER asks
// the plugin to interpret; it just streams Items back.
type ObserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"` // opaque resume token from a prior Observe; "" == full sync
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveRequest) Reset() {
	*x = ObserveRequest{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveRequest) ProtoMessage() {}

func (x *ObserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveRequest.ProtoReflect.Descriptor instead.
func (*ObserveRequest) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *ObserveRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// ObservedEntity is the core-LEGIBLE write-back shape — the Syncer carve-out
// (ADR-0046 findings #3/#5). The core reads kind/identity_keys/labels/facet-
// namespaces STRUCTURALLY to route, correlate, own-check, and tombstone; each
// facet VALUE is a plugin blob the core validates against the pinned Facet
// schema at the write path (contract.ValidateFacet) and never interprets
// further. This is deliberately NOT the opaque Apply-path payload — and it
// carries NO principal/provenance field, so a plugin cannot claim provenance
// (invariant #6): the host stamps it from the authenticated channel identity.
type ObservedEntity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // Entity kind — core-legible coordinate
	// identity scheme -> value. Each scheme is gated by tier + operator grant
	// (finding #4): an ungranted scheme, or a shared cross-source scheme from a
	// community-tier plugin, is rejected with a Finding, never written.
	IdentityKeys  map[string]string `protobuf:"bytes,2,rep,name=identity_keys,json=identityKeys,proto3" json:"identity_keys,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels        map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // label key -> value; owned per-key (ADR-0041)
	Facets        map[string][]byte `protobuf:"bytes,4,rep,name=facets,proto3" json:"facets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // namespace -> value blob, schema-validated core-side
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservedEntity) Reset() {
	*x = ObservedEntity{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservedEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservedEntity) ProtoMessage() {}

func (x *ObservedEntity) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservedEntity.ProtoReflect.Descriptor instead.
func (*ObservedEntity) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *ObservedEntity) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ObservedEntity) GetIdentityKeys() map[string]string {
	if x != nil {
		return x.IdentityKeys
	}
	return nil
}

func (x *ObservedEntity) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ObservedEntity) GetFacets() map[string][]byte {
	if x != nil {
		return x.Facets
	}
	return nil
}

// GoneEntity signals a delta 'leave': an Entity the Source no longer reports, by
// the identity scheme+value it tombstones on (ADR-0042). Empty on a pure
// full-sync window.
type GoneEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheme        string                 `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoneEntity) Reset() {
	*x = GoneEntity{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoneEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoneEntity) ProtoMessage() {}

func (x *GoneEntity) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoneEntity.ProtoReflect.Descriptor instead.
func (*GoneEntity) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *GoneEntity) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *GoneEntity) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ObserveResponse is one window of the Syncer stream. The core accumulates a
// per-scheme seen-set from `entities`; on full_sync_complete it tombstones
// everything absent for each granted tombstone scheme (liveness crosses the
// wire, ADR-0042). `gone` carries delta leaves. The plugin holds no DB path —
// the core is the sole writer under enforce_write_path.
type ObserveResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Entities         []*ObservedEntity      `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`                                            // present entities (upserts) in this window
	Gone             []*GoneEntity          `protobuf:"bytes,2,rep,name=gone,proto3" json:"gone,omitempty"`                                                    // delta leaves to tombstone; empty on full-sync
	FullSyncComplete bool                   `protobuf:"varint,3,opt,name=full_sync_complete,json=fullSyncComplete,proto3" json:"full_sync_complete,omitempty"` // true on the window that ends a full sync
	NextCursor       string                 `protobuf:"bytes,4,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`                      // opaque delta resume token; set on the last message of a window
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ObserveResponse) Reset() {
	*x = ObserveResponse{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveResponse) ProtoMessage() {}

func (x *ObserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveResponse.ProtoReflect.Descriptor instead.
func (*ObserveResponse) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *ObserveResponse) GetEntities() []*ObservedEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ObserveResponse) GetGone() []*GoneEntity {
	if x != nil {
		return x.Gone
	}
	return nil
}

func (x *ObserveResponse) GetFullSyncComplete() bool {
	if x != nil {
		return x.FullSyncComplete
	}
	return false
}

func (x *ObserveResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// PlanRequest asks the plugin for the DOMAIN diff (device-only knowledge). The
// desired-state Payload is opaque to the core.
type PlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Desired       *Payload               `protobuf:"bytes,2,opt,name=desired,proto3" json:"desired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanRequest) Reset() {
	*x = PlanRequest{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRequest) ProtoMessage() {}

func (x *PlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRequest.ProtoReflect.Descriptor instead.
func (*PlanRequest) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *PlanRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *PlanRequest) GetDesired() *Payload {
	if x != nil {
		return x.Desired
	}
	return nil
}

// PlanResponse is the plugin's domain diff, returned as an opaque Payload the core
// stores and can descend into (§1.8) but never interprets. summary is a typed,
// core-legible one-line gist for descent screens (never the mechanism of
// diagnosis-hiding — invariant #12 spirit). (Named PlanResponse, not Plan, so the
// message never shadows the PluginService.Plan RPC in the service scope.)
type PlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diff          *Payload               `protobuf:"bytes,1,opt,name=diff,proto3" json:"diff,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Empty         bool                   `protobuf:"varint,3,opt,name=empty,proto3" json:"empty,omitempty"` // true == no change (converged)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *PlanResponse) GetDiff() *Payload {
	if x != nil {
		return x.Diff
	}
	return nil
}

func (x *PlanResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PlanResponse) GetEmpty() bool {
	if x != nil {
		return x.Empty
	}
	return false
}

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Desired       *Payload               `protobuf:"bytes,2,opt,name=desired,proto3" json:"desired,omitempty"`                            // opaque; applied atomically on the ROOT (invariant #9)
	ResumeToken   string                 `protobuf:"bytes,3,opt,name=resume_token,json=resumeToken,proto3" json:"resume_token,omitempty"` // optional checkpoint/resume (invariant #7); "" == fresh
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *ApplyRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *ApplyRequest) GetDesired() *Payload {
	if x != nil {
		return x.Desired
	}
	return nil
}

func (x *ApplyRequest) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

type DestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *DestroyRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

// InvokeRequest — a targetless Action (RunAction). Args are opaque.
type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Args          *Payload               `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *InvokeRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *InvokeRequest) GetArgs() *Payload {
	if x != nil {
		return x.Args
	}
	return nil
}

// SubscribeRequest — an Emitter opens a long-lived push stream (invariant #4).
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"` // opaque resume token; "" == from-now
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *SubscribeRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// TaskEvent is the TYPED, CORE-LEGIBLE descent/diagnostic unit (invariant #12).
// It is deliberately NOT an opaque blob: §1.8 one-click descent (Intent →
// Blueprint → Workflow → Run → task event) must survive the port. Diagnostics
// ride this typed channel; only DESIRED-STATE payloads are opaque.
type TaskEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         TaskEvent_Level        `protobuf:"varint,1,opt,name=level,proto3,enum=stratt.plugin.v1.TaskEvent_Level" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // human/core-legible line
	At            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`                                        // mirrors Envelope.correlation_id
	Fields        map[string]string      `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // structured, legible fields — NOT an opaque blob
	Terminal      bool                   `protobuf:"varint,6,opt,name=terminal,proto3" json:"terminal,omitempty"`                                                                      // true on the final event of the stream
	Ok            bool                   `protobuf:"varint,7,opt,name=ok,proto3" json:"ok,omitempty"`                                                                                  // meaningful only when terminal == true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *TaskEvent) GetLevel() TaskEvent_Level {
	if x != nil {
		return x.Level
	}
	return TaskEvent_LEVEL_UNSPECIFIED
}

func (x *TaskEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskEvent) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *TaskEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *TaskEvent) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *TaskEvent) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

func (x *TaskEvent) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Per-RPC response wrappers keep each streaming verb independently evolvable
// (buf STANDARD RPC_REQUEST_RESPONSE_UNIQUE — aids invariant #5's additive-only
// evolution) while TaskEvent stays the single shared, core-legible diagnostic
// type each one carries.
type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *TaskEvent             `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *ApplyResponse) GetEvent() *TaskEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type DestroyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *TaskEvent             `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyResponse) Reset() {
	*x = DestroyResponse{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyResponse) ProtoMessage() {}

func (x *DestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyResponse.ProtoReflect.Descriptor instead.
func (*DestroyResponse) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *DestroyResponse) GetEvent() *TaskEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *TaskEvent             `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *InvokeResponse) GetEvent() *TaskEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// EmittedEvent — an Emitter's push: governance Envelope + opaque Payload,
// exactly like an observed Item (the core routes on the envelope, never the
// payload).
type EmittedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Payload       *Payload               `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"` // resume token the core persists for at-least-once replay
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmittedEvent) Reset() {
	*x = EmittedEvent{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmittedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmittedEvent) ProtoMessage() {}

func (x *EmittedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmittedEvent.ProtoReflect.Descriptor instead.
func (*EmittedEvent) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *EmittedEvent) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *EmittedEvent) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EmittedEvent) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *EmittedEvent          `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stratt_plugin_v1_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_stratt_plugin_v1_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *SubscribeResponse) GetEvent() *EmittedEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_stratt_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_stratt_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1dstratt/plugin/v1/plugin.proto\x12\x10stratt.plugin.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x02\n" +
	"\bEnvelope\x12?\n" +
	"\vcoordinates\x18\x01 \x01(\v2\x1d.stratt.plugin.v1.CoordinatesR\vcoordinates\x129\n" +
	"\bcontract\x18\x02 \x01(\v2\x1d.stratt.plugin.v1.ContractRefR\bcontract\x129\n" +
	"\tprincipal\x18\x03 \x01(\v2\x1b.stratt.plugin.v1.PrincipalR\tprincipal\x125\n" +
	"\x05creds\x18\x04 \x03(\v2\x1f.stratt.plugin.v1.CredentialRefR\x05creds\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\x12!\n" +
	"\fcontent_hash\x18\a \x01(\tR\vcontentHash\"\x1f\n" +
	"\aPayload\x12\x14\n" +
	"\x05bytes\x18\x01 \x01(\fR\x05bytes\"\xa7\x01\n" +
	"\x04Item\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.stratt.plugin.v1.EnvelopeR\benvelope\x123\n" +
	"\apayload\x18\x02 \x01(\v2\x19.stratt.plugin.v1.PayloadR\apayload\x122\n" +
	"\bchildren\x18\x03 \x03(\v2\x16.stratt.plugin.v1.ItemR\bchildren\"]\n" +
	"\vCoordinates\x12\x12\n" +
	"\x04cell\x18\x01 \x01(\tR\x04cell\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04band\x18\x03 \x01(\tR\x04band\x12\x12\n" +
	"\x04beam\x18\x04 \x01(\tR\x04beam\"B\n" +
	"\vContractRef\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"/\n" +
	"\tPrincipal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"#\n" +
	"\rCredentialRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x14\n" +
	"\x12GetManifestRequest\"W\n" +
	"\fContractDecl\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04band\x18\x03 \x01(\tR\x04band\"\xa0\x02\n" +
	"\bManifest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x123\n" +
	"\x05class\x18\x03 \x01(\x0e2\x1d.stratt.plugin.v1.PluginClassR\x05class\x12,\n" +
	"\x05verbs\x18\x04 \x03(\x0e2\x16.stratt.plugin.v1.VerbR\x05verbs\x12<\n" +
	"\tcontracts\x18\x05 \x03(\v2\x1e.stratt.plugin.v1.ContractDeclR\tcontracts\x12+\n" +
	"\x11tombstone_schemes\x18\x06 \x03(\tR\x10tombstoneSchemes\"M\n" +
	"\x13GetManifestResponse\x126\n" +
	"\bmanifest\x18\x01 \x01(\v2\x1a.stratt.plugin.v1.ManifestR\bmanifest\"\x0f\n" +
	"\rHealthRequest\"\xc3\x01\n" +
	"\x0eHealthResponse\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.stratt.plugin.v1.HealthResponse.ServingR\x06status\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\"D\n" +
	"\aServing\x12\x17\n" +
	"\x13SERVING_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"SERVING_UP\x10\x01\x12\x10\n" +
	"\fSERVING_DOWN\x10\x02\"(\n" +
	"\x0eObserveRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\"\xc0\x03\n" +
	"\x0eObservedEntity\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12W\n" +
	"\ridentity_keys\x18\x02 \x03(\v22.stratt.plugin.v1.ObservedEntity.IdentityKeysEntryR\fidentityKeys\x12D\n" +
	"\x06labels\x18\x03 \x03(\v2,.stratt.plugin.v1.ObservedEntity.LabelsEntryR\x06labels\x12D\n" +
	"\x06facets\x18\x04 \x03(\v2,.stratt.plugin.v1.ObservedEntity.FacetsEntryR\x06facets\x1a?\n" +
	"\x11IdentityKeysEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vFacetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\":\n" +
	"\n" +
	"GoneEntity\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xd0\x01\n" +
	"\x0fObserveResponse\x12<\n" +
	"\bentities\x18\x01 \x03(\v2 .stratt.plugin.v1.ObservedEntityR\bentities\x120\n" +
	"\x04gone\x18\x02 \x03(\v2\x1c.stratt.plugin.v1.GoneEntityR\x04gone\x12,\n" +
	"\x12full_sync_complete\x18\x03 \x01(\bR\x10fullSyncComplete\x12\x1f\n" +
	"\vnext_cursor\x18\x04 \x01(\tR\n" +
	"nextCursor\"z\n" +
	"\vPlanRequest\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.stratt.plugin.v1.EnvelopeR\benvelope\x123\n" +
	"\adesired\x18\x02 \x01(\v2\x19.stratt.plugin.v1.PayloadR\adesired\"m\n" +
	"\fPlanResponse\x12-\n" +
	"\x04diff\x18\x01 \x01(\v2\x19.stratt.plugin.v1.PayloadR\x04diff\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05empty\x18\x03 \x01(\bR\x05empty\"\x9e\x01\n" +
	"\fApplyRequest\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.stratt.plugin.v1.EnvelopeR\benvelope\x123\n" +
	"\adesired\x18\x02 \x01(\v2\x19.stratt.plugin.v1.PayloadR\adesired\x12!\n" +
	"\fresume_token\x18\x03 \x01(\tR\vresumeToken\"H\n" +
	"\x0eDestroyRequest\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.stratt.plugin.v1.EnvelopeR\benvelope\"v\n" +
	"\rInvokeRequest\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.stratt.plugin.v1.EnvelopeR\benvelope\x12-\n" +
	"\x04args\x18\x02 \x01(\v2\x19.stratt.plugin.v1.PayloadR\x04args\"*\n" +
	"\x10SubscribeRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\"\xbb\x03\n" +
	"\tTaskEvent\x127\n" +
	"\x05level\x18\x01 \x01(\x0e2!.stratt.plugin.v1.TaskEvent.LevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x02at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\x12?\n" +
	"\x06fields\x18\x05 \x03(\v2'.stratt.plugin.v1.TaskEvent.FieldsEntryR\x06fields\x12\x1a\n" +
	"\bterminal\x18\x06 \x01(\bR\bterminal\x12\x0e\n" +
	"\x02ok\x18\a \x01(\bR\x02ok\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vLEVEL_DEBUG\x10\x01\x12\x0e\n" +
	"\n" +
	"LEVEL_INFO\x10\x02\x12\x0e\n" +
	"\n" +
	"LEVEL_WARN\x10\x03\x12\x0f\n" +
	"\vLEVEL_ERROR\x10\x04\"B\n" +
	"\rApplyResponse\x121\n" +
	"\x05event\x18\x01 \x01(\v2\x1b.stratt.plugin.v1.TaskEventR\x05event\"D\n" +
	"\x0fDestroyResponse\x121\n" +
	"\x05event\x18\x01 \x01(\v2\x1b.stratt.plugin.v1.TaskEventR\x05event\"C\n" +
	"\x0eInvokeResponse\x121\n" +
	"\x05event\x18\x01 \x01(\v2\x1b.stratt.plugin.v1.TaskEventR\x05event\"\x93\x01\n" +
	"\fEmittedEvent\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.stratt.plugin.v1.EnvelopeR\benvelope\x123\n" +
	"\apayload\x18\x02 \x01(\v2\x19.stratt.plugin.v1.PayloadR\apayload\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"I\n" +
	"\x11SubscribeResponse\x124\n" +
	"\x05event\x18\x01 \x01(\v2\x1e.stratt.plugin.v1.EmittedEventR\x05event*\x92\x01\n" +
	"\vPluginClass\x12\x1c\n" +
	"\x18PLUGIN_CLASS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PLUGIN_CLASS_SYNCER\x10\x01\x12\x19\n" +
	"\x15PLUGIN_CLASS_ACTUATOR\x10\x02\x12\x17\n" +
	"\x13PLUGIN_CLASS_ACTION\x10\x03\x12\x18\n" +
	"\x14PLUGIN_CLASS_EMITTER\x10\x04*\x7f\n" +
	"\x04Verb\x12\x14\n" +
	"\x10VERB_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fVERB_OBSERVE\x10\x01\x12\r\n" +
	"\tVERB_PLAN\x10\x02\x12\x0e\n" +
	"\n" +
	"VERB_APPLY\x10\x03\x12\x10\n" +
	"\fVERB_DESTROY\x10\x04\x12\x0f\n" +
	"\vVERB_INVOKE\x10\x05\x12\r\n" +
	"\tVERB_EMIT\x10\x062\x96\x05\n" +
	"\rPluginService\x12Z\n" +
	"\vGetManifest\x12$.stratt.plugin.v1.GetManifestRequest\x1a%.stratt.plugin.v1.GetManifestResponse\x12K\n" +
	"\x06Health\x12\x1f.stratt.plugin.v1.HealthRequest\x1a .stratt.plugin.v1.HealthResponse\x12P\n" +
	"\aObserve\x12 .stratt.plugin.v1.ObserveRequest\x1a!.stratt.plugin.v1.ObserveResponse0\x01\x12E\n" +
	"\x04Plan\x12\x1d.stratt.plugin.v1.PlanRequest\x1a\x1e.stratt.plugin.v1.PlanResponse\x12J\n" +
	"\x05Apply\x12\x1e.stratt.plugin.v1.ApplyRequest\x1a\x1f.stratt.plugin.v1.ApplyResponse0\x01\x12P\n" +
	"\aDestroy\x12 .stratt.plugin.v1.DestroyRequest\x1a!.stratt.plugin.v1.DestroyResponse0\x01\x12M\n" +
	"\x06Invoke\x12\x1f.stratt.plugin.v1.InvokeRequest\x1a .stratt.plugin.v1.InvokeResponse0\x01\x12V\n" +
	"\tSubscribe\x12\".stratt.plugin.v1.SubscribeRequest\x1a#.stratt.plugin.v1.SubscribeResponse0\x01B?Z=github.com/dstout-devops/stratt/sdk/stratt/plugin/v1;pluginv1b\x06proto3"

var (
	file_stratt_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_stratt_plugin_v1_plugin_proto_rawDescData []byte
)

func file_stratt_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_stratt_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_stratt_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stratt_plugin_v1_plugin_proto_rawDesc), len(file_stratt_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_stratt_plugin_v1_plugin_proto_rawDescData
}

var file_stratt_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_stratt_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_stratt_plugin_v1_plugin_proto_goTypes = []any{
	(PluginClass)(0),              // 0: stratt.plugin.v1.PluginClass
	(Verb)(0),                     // 1: stratt.plugin.v1.Verb
	(HealthResponse_Serving)(0),   // 2: stratt.plugin.v1.HealthResponse.Serving
	(TaskEvent_Level)(0),          // 3: stratt.plugin.v1.TaskEvent.Level
	(*Envelope)(nil),              // 4: stratt.plugin.v1.Envelope
	(*Payload)(nil),               // 5: stratt.plugin.v1.Payload
	(*Item)(nil),                  // 6: stratt.plugin.v1.Item
	(*Coordinates)(nil),           // 7: stratt.plugin.v1.Coordinates
	(*ContractRef)(nil),           // 8: stratt.plugin.v1.ContractRef
	(*Principal)(nil),             // 9: stratt.plugin.v1.Principal
	(*CredentialRef)(nil),         // 10: stratt.plugin.v1.CredentialRef
	(*GetManifestRequest)(nil),    // 11: stratt.plugin.v1.GetManifestRequest
	(*ContractDecl)(nil),          // 12: stratt.plugin.v1.ContractDecl
	(*Manifest)(nil),              // 13: stratt.plugin.v1.Manifest
	(*GetManifestResponse)(nil),   // 14: stratt.plugin.v1.GetManifestResponse
	(*HealthRequest)(nil),         // 15: stratt.plugin.v1.HealthRequest
	(*HealthResponse)(nil),        // 16: stratt.plugin.v1.HealthResponse
	(*ObserveRequest)(nil),        // 17: stratt.plugin.v1.ObserveRequest
	(*ObservedEntity)(nil),        // 18: stratt.plugin.v1.ObservedEntity
	(*GoneEntity)(nil),            // 19: stratt.plugin.v1.GoneEntity
	(*ObserveResponse)(nil),       // 20: stratt.plugin.v1.ObserveResponse
	(*PlanRequest)(nil),           // 21: stratt.plugin.v1.PlanRequest
	(*PlanResponse)(nil),          // 22: stratt.plugin.v1.PlanResponse
	(*ApplyRequest)(nil),          // 23: stratt.plugin.v1.ApplyRequest
	(*DestroyRequest)(nil),        // 24: stratt.plugin.v1.DestroyRequest
	(*InvokeRequest)(nil),         // 25: stratt.plugin.v1.InvokeRequest
	(*SubscribeRequest)(nil),      // 26: stratt.plugin.v1.SubscribeRequest
	(*TaskEvent)(nil),             // 27: stratt.plugin.v1.TaskEvent
	(*ApplyResponse)(nil),         // 28: stratt.plugin.v1.ApplyResponse
	(*DestroyResponse)(nil),       // 29: stratt.plugin.v1.DestroyResponse
	(*InvokeResponse)(nil),        // 30: stratt.plugin.v1.InvokeResponse
	(*EmittedEvent)(nil),          // 31: stratt.plugin.v1.EmittedEvent
	(*SubscribeResponse)(nil),     // 32: stratt.plugin.v1.SubscribeResponse
	nil,                           // 33: stratt.plugin.v1.ObservedEntity.IdentityKeysEntry
	nil,                           // 34: stratt.plugin.v1.ObservedEntity.LabelsEntry
	nil,                           // 35: stratt.plugin.v1.ObservedEntity.FacetsEntry
	nil,                           // 36: stratt.plugin.v1.TaskEvent.FieldsEntry
	(*timestamppb.Timestamp)(nil), // 37: google.protobuf.Timestamp
}
var file_stratt_plugin_v1_plugin_proto_depIdxs = []int32{
	7,  // 0: stratt.plugin.v1.Envelope.coordinates:type_name -> stratt.plugin.v1.Coordinates
	8,  // 1: stratt.plugin.v1.Envelope.contract:type_name -> stratt.plugin.v1.ContractRef
	9,  // 2: stratt.plugin.v1.Envelope.principal:type_name -> stratt.plugin.v1.Principal
	10, // 3: stratt.plugin.v1.Envelope.creds:type_name -> stratt.plugin.v1.CredentialRef
	4,  // 4: stratt.plugin.v1.Item.envelope:type_name -> stratt.plugin.v1.Envelope
	5,  // 5: stratt.plugin.v1.Item.payload:type_name -> stratt.plugin.v1.Payload
	6,  // 6: stratt.plugin.v1.Item.children:type_name -> stratt.plugin.v1.Item
	0,  // 7: stratt.plugin.v1.Manifest.class:type_name -> stratt.plugin.v1.PluginClass
	1,  // 8: stratt.plugin.v1.Manifest.verbs:type_name -> stratt.plugin.v1.Verb
	12, // 9: stratt.plugin.v1.Manifest.contracts:type_name -> stratt.plugin.v1.ContractDecl
	13, // 10: stratt.plugin.v1.GetManifestResponse.manifest:type_name -> stratt.plugin.v1.Manifest
	2,  // 11: stratt.plugin.v1.HealthResponse.status:type_name -> stratt.plugin.v1.HealthResponse.Serving
	33, // 12: stratt.plugin.v1.ObservedEntity.identity_keys:type_name -> stratt.plugin.v1.ObservedEntity.IdentityKeysEntry
	34, // 13: stratt.plugin.v1.ObservedEntity.labels:type_name -> stratt.plugin.v1.ObservedEntity.LabelsEntry
	35, // 14: stratt.plugin.v1.ObservedEntity.facets:type_name -> stratt.plugin.v1.ObservedEntity.FacetsEntry
	18, // 15: stratt.plugin.v1.ObserveResponse.entities:type_name -> stratt.plugin.v1.ObservedEntity
	19, // 16: stratt.plugin.v1.ObserveResponse.gone:type_name -> stratt.plugin.v1.GoneEntity
	4,  // 17: stratt.plugin.v1.PlanRequest.envelope:type_name -> stratt.plugin.v1.Envelope
	5,  // 18: stratt.plugin.v1.PlanRequest.desired:type_name -> stratt.plugin.v1.Payload
	5,  // 19: stratt.plugin.v1.PlanResponse.diff:type_name -> stratt.plugin.v1.Payload
	4,  // 20: stratt.plugin.v1.ApplyRequest.envelope:type_name -> stratt.plugin.v1.Envelope
	5,  // 21: stratt.plugin.v1.ApplyRequest.desired:type_name -> stratt.plugin.v1.Payload
	4,  // 22: stratt.plugin.v1.DestroyRequest.envelope:type_name -> stratt.plugin.v1.Envelope
	4,  // 23: stratt.plugin.v1.InvokeRequest.envelope:type_name -> stratt.plugin.v1.Envelope
	5,  // 24: stratt.plugin.v1.InvokeRequest.args:type_name -> stratt.plugin.v1.Payload
	3,  // 25: stratt.plugin.v1.TaskEvent.level:type_name -> stratt.plugin.v1.TaskEvent.Level
	37, // 26: stratt.plugin.v1.TaskEvent.at:type_name -> google.protobuf.Timestamp
	36, // 27: stratt.plugin.v1.TaskEvent.fields:type_name -> stratt.plugin.v1.TaskEvent.FieldsEntry
	27, // 28: stratt.plugin.v1.ApplyResponse.event:type_name -> stratt.plugin.v1.TaskEvent
	27, // 29: stratt.plugin.v1.DestroyResponse.event:type_name -> stratt.plugin.v1.TaskEvent
	27, // 30: stratt.plugin.v1.InvokeResponse.event:type_name -> stratt.plugin.v1.TaskEvent
	4,  // 31: stratt.plugin.v1.EmittedEvent.envelope:type_name -> stratt.plugin.v1.Envelope
	5,  // 32: stratt.plugin.v1.EmittedEvent.payload:type_name -> stratt.plugin.v1.Payload
	31, // 33: stratt.plugin.v1.SubscribeResponse.event:type_name -> stratt.plugin.v1.EmittedEvent
	11, // 34: stratt.plugin.v1.PluginService.GetManifest:input_type -> stratt.plugin.v1.GetManifestRequest
	15, // 35: stratt.plugin.v1.PluginService.Health:input_type -> stratt.plugin.v1.HealthRequest
	17, // 36: stratt.plugin.v1.PluginService.Observe:input_type -> stratt.plugin.v1.ObserveRequest
	21, // 37: stratt.plugin.v1.PluginService.Plan:input_type -> stratt.plugin.v1.PlanRequest
	23, // 38: stratt.plugin.v1.PluginService.Apply:input_type -> stratt.plugin.v1.ApplyRequest
	24, // 39: stratt.plugin.v1.PluginService.Destroy:input_type -> stratt.plugin.v1.DestroyRequest
	25, // 40: stratt.plugin.v1.PluginService.Invoke:input_type -> stratt.plugin.v1.InvokeRequest
	26, // 41: stratt.plugin.v1.PluginService.Subscribe:input_type -> stratt.plugin.v1.SubscribeRequest
	14, // 42: stratt.plugin.v1.PluginService.GetManifest:output_type -> stratt.plugin.v1.GetManifestResponse
	16, // 43: stratt.plugin.v1.PluginService.Health:output_type -> stratt.plugin.v1.HealthResponse
	20, // 44: stratt.plugin.v1.PluginService.Observe:output_type -> stratt.plugin.v1.ObserveResponse
	22, // 45: stratt.plugin.v1.PluginService.Plan:output_type -> stratt.plugin.v1.PlanResponse
	28, // 46: stratt.plugin.v1.PluginService.Apply:output_type -> stratt.plugin.v1.ApplyResponse
	29, // 47: stratt.plugin.v1.PluginService.Destroy:output_type -> stratt.plugin.v1.DestroyResponse
	30, // 48: stratt.plugin.v1.PluginService.Invoke:output_type -> stratt.plugin.v1.InvokeResponse
	32, // 49: stratt.plugin.v1.PluginService.Subscribe:output_type -> stratt.plugin.v1.SubscribeResponse
	42, // [42:50] is the sub-list for method output_type
	34, // [34:42] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_stratt_plugin_v1_plugin_proto_init() }
func file_stratt_plugin_v1_plugin_proto_init() {
	if File_stratt_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stratt_plugin_v1_plugin_proto_rawDesc), len(file_stratt_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stratt_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_stratt_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_stratt_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_stratt_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_stratt_plugin_v1_plugin_proto = out.File
	file_stratt_plugin_v1_plugin_proto_goTypes = nil
	file_stratt_plugin_v1_plugin_proto_depIdxs = nil
}
